### ISSUE TITLE
Is there a way for "hierarchical" meshes?

### ISSUE THREAD

**Issue by yarikoptic** [niivue/niivue#1007]
I don't know much but have  a visitor at the booth with a use case where the mesh is very detailed so they downscale the mesh for browser to cope (directly webgl).  I wonder if there is , similarly how it is done with microscopy data/zarr format, to have multiple mesh resolutions so the more detailed mesh is "partially" loaded for the region of interest as you zoom in.

Cheers

**Comment by neurolabusc** [comment]
@yarikoptic this is easy for any developer to add, but out of scope as a core feature for NiiVue. You can see how voxel-to-mesh conversion and mesh simplification can be combined in JavaScript from [my repository and live demo](https://github.com/neurolabusc/nii2mesh). For just the mesh simplification, see the JavaScript demos [here](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification). However, be aware that [the fastest methods have limitations](https://github.com/neurolabusc/nii2mesh?tab=readme-ov-file#limitations).

It is worth saying that FreeSurfer meshes **are** hierarchical and therefore one can [easily subdivide them](https://brainder.org/2016/05/31/downsampling-decimating-a-brain-surface/). This property of FreeSurfer meshes is not typical of most meshes: most meshes are more efficient by using [adaptive simplification](https://www.alecjacobson.com/weblog/4444.html) where fewer triangles are used for flatter regions (a more subtle inefficiency of hierarchical meshes is GPU memory locality).

The biggest problem with mesh simplification or decimation is how to interpolate mesh colors. In our domain, we often have meshes in some files, and vertex overlays in others. For example, a tool like PALM will create a per-vertex statistical map. So if the number of vertices in a mesh is reduced, we need to be careful in considering how the per-vertex colors contribute to these new vertices.

My own sense is that these topics should be dealt with at the time when meshes are generated, when one can inform decisions on the voxel data. The full FreeSurfer meshes are massively oversampled for the SNR and resolution of our tools. I do think [my repository and live demo](https://github.com/neurolabusc/nii2mesh) demonstrate how to create adaptive meshes that handle these tradeoffs effectively.

Therefore, we leave these decisions to the developers, as they are easy to implement but require clear tradeoffs. Rather, we have focused on making NiiVue super fast at rendering meshes, and even the most complex FreeSurfer mesh should render rapidly on a phone. Our [live demos](https://niivue.github.io/niivue/) do also illustrate choices that developers can make to provide better performance or better quality. For example:
 - A NiiVue instance can have [antialiasing off](https://niivue.github.io/niivue/features/mesh.freesurfer.aaOFF.html) or [on](https://niivue.github.io/niivue/features/mesh.freesurfer.aaON.html).
 - One can turn [on or off High-DPI support](https://niivue.github.io/niivue/features/mesh.freesurfer.html) for [`retina` displays](https://www.khronos.org/webgl/wiki/HandlingHighDPI).
 - One can turn [on or off mesh X-Ray](https://niivue.github.io/niivue/features/mesh.freesurfer.html) to provide some mesh translucency with a big performance hit.

**Comment by yarikoptic** [comment]
Thank you @neurolabusc for all the exhaustive reply!
