### ISSUE TITLE
Custom Text Annotations

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#1016]
NiiVue already allows connectomes to have interactive legends, as seen in thie [live demo](https://niivue.github.io/niivue/features/labels.connectomes.html). @cdrake suggested we could reuse the underlying functions to allow custom text annotations. This could be used in many creative ways. Two usages are:
 - Allow callbacks when a user clicks on an annotation. This could allow the user to unhide the tool panel for our desktop application (as we discussed in today's main meeting).
 - Allow image annotations, similar to [Horos](https://horosproject.org/about/) (Shown below). Similar to our [mosaic strings](https://niivue.github.io/niivue/features/mosaics.html) this could allow custom formatting. I was thinking that we could use the % symbol for image specific text (e.g. `%c` for window center, `%w` for window width, etc). The developer should be able to specify how the annotation is anchored on the image.

 
![Horos](https://github.com/niivue/niivue/assets/8930807/40a310ce-d6a9-4bc4-bf6b-a361950a2843)

**Comment by hanayik** [comment]
This is closed by the recent UIKit features (see #1089)
