### ISSUE TITLE
mosaic view should center slices or use equal space between slices to make use of full canvas width

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#1017]
Currently, the niivue mosaic view uses a left justified layout like this:

<img width="1207" alt="image" src="https://github.com/niivue/niivue/assets/5217720/a8e8809f-9f64-4d23-9ed8-dbdcc4400168">

However, it would look nicer (and better on various device widths) if the slices could have equal space between them while occupying the full width of the canvas. Alternatively, they could have equal "space around" on the left and right most slices so that the mosaic is centered.

**Comment by neurolabusc** [comment]
@hanayik I have added boolean property which defaults to `nv.centerMosaic = false`. If set to true, the mosaic is centered. I leave it in your capable hands on how to proceeed:
1. If you want to make centered the only or default behavior, you need to update regression tests like `niivue-demo-file-mosaics-html-chromium.png`.
2. If you want to allow developers to decide if a mosaic is centered, this needs to be stored in the document, and the definition should probably be in `nvdocument.ts`.

To illustrate the new (experimental) behavior, I have added a `center` checkbox to the [mosaic demo](https://niivue.github.io/niivue/features/mosaics.html):

![centerMosaic](https://github.com/niivue/niivue/assets/8930807/81dd315c-3c19-44be-955d-33bd26258a03)
