### ISSUE TITLE
all image rendering broken in Safari 13.1.3

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#102]
@neurolabusc and @cdrake, all image rendering is broken in Safari on macOS. We can still render lines and text, so that means we do successfully get a webgl2 context on Safari.

@neurolabusc, if you have the safari tech preview on Big Sur could you test our demos there (just load the GitHub pages demos). 

Unfortunately it is difficult to say when this happened. I will try going back in the commit history in order to find a commit where it still worked. 

Chrome and Firefox are still fine.

**Comment by hanayik** [comment]
Ah, that's very interesting. I was testing Safari 13.1.3 on macOS Catalina (intel chip). I can confirm niivue does not work in that environment, but DOES work on my other mac (Safari 14.0.3, macOS Big Sur, intel chip). This is prob fine since Safari webgl 2 is listed as experimental, however, niivue used to work in both environments. Experimental webgl 2.0 support was enabled in both. So, it appears that Safari 14 on macOS Big Sur + seems to be less experimental, and supports NiiVue better. 

I think we should make this clear on the Readme in case users with older Safari versions encounter this. I'm not too worried about it now that we've confirmed it works in Safari 14+ and macOS Big Sur. Thanks for doing the iPhone test as well!

**Comment by neurolabusc** [comment]
Curious. Since only you can replicate this, you have to decide if this is something you want to fix. There really have not been many changes to the rendering for a while in the main branch. You might want to see if [rolling back this one](https://github.com/niivue/niivue/commit/a5f5a1d7f3f42c9662118c76b8e1ce1b9ca56016) resolves the issue. @cdrake's upcoming depth picking will further test experimental webGL implementations, as power user features like gl_FragDepth are probably real edge cases that rarely get tested.

**Comment by neurolabusc** [comment]
@hanayik I do not see a difference between old and new versions of NiiVue. It does not seem to me like we broke something, rather Safari does not have good WebGL support on Intel CPUs.

BatCave MacOS machines. 

MacOS 10.15 iMac19,1 (i7, Radeon GPU): 
 - Chrome 93: seems to work fine
 - Safari 13.1: only fonts and lines work, no 2D slices even with older versions of NiiVue

MacOS 10.13 iMac12,2 (i7, Radeon GPU): 
 - Chrome 92: seems to work fine
 - Safari 13.12: only fonts and lines work, no 2D slices even with older versions of NiiVue

MacOS 10.11 MacPro4,1 (i7, Nvidia GPU): 
 - Chrome 93: rendering is messed up for old and new versions of NiiVue
 - Safari 11.1: thisSafari does not support WebGL2 at all
