### ISSUE TITLE
allow developers to hide 3D render in multiplanar layout mode

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#1024]
Currently, NiiVue detects the aspect ratio of the canvas and chooses to show the 3D render tile if space allows. Even if space doesn't allow, the option `opts.multiplanarForceRender` can be used to force the 3D render tile to be visible. 

However, there is no equivalent option to force the 3D render tile to _never_ show the 3D render in multiplanar layout mode. 

I propose a new option: `opts.multiplanarShowRender`. By default the value can be `true` to preserve the current behaviour, but users can set this to `false` to ensure the 3D render tile never gets drawn even if the canvas aspect ratio allows for it. 

I imagine this should be implemented in [`drawSceneCore`](https://github.com/niivue/niivue/blob/04802ee7f32ed28290da32250aa7939f8a1717cc/src/niivue/index.ts#L10019)

**Comment by neurolabusc** [comment]
@hanayik my main concern when having multiple interacting booleans is giving precedence when they are conflicting. In your suggestion, `opts.multiplanarForceRender = true` demands a rendering, but `opts.multiplanarShowRender = false` vetos a 3D rendering. The precedence between these two options will not be obvious to a developer. I understand the desire for backward compatibility, but we may want to carefully consider this. I am not completely committed to this, but one idea is to use ternary logic for `opts.multiplanarForceRender`, so it can be true (force render), false (rendering is not forced but optional) and null (prevent rendering).

**Comment by hanayik** [comment]
@neurolabusc, your point is a good one and I agree that the two variables would introduce confusion. 

Instead, how about this?

- update the use of `multiplanarForceRender`, where the possible values are strings being: `"always"`, `"never"`, or `"auto"`. 
- a value of `"never"` would always hide the render tile in multiplanar mode
- a value of `"always"` would always show it (similar to `multiplanarForceRender=true`)
- a value of `"auto"` would allow the canvas aspect ratio to determine if the render tile is shown (similar to `multiplanarForceRender=false`). 

I think the use of strings indicating the desired behaviour is more interpretable than the using boolean and null, but it does mean the API changes (but for the better I think).

**Comment by neurolabusc** [comment]
Seems reasonable, if this is a breaking change, I would call it `multiplanarShowRender`.
