### ISSUE TITLE
Decimating down doesn't allow to go back up on demo

### ISSUE THREAD

**Issue by yarikoptic** [niivue/niivue#1037]
Thanks for working out performant mesh multi resolution support!  Looking at https://niivue.github.io/niivue/features/mesh.atlas.html , if I select Decimation to go lower (e.g. 5) from `7`, after I select it , there is no higher decimations (6, 7) available any longer.  Is that a limitation, a feature, or a bug? ;-)

**Comment by neurolabusc** [comment]
It is a feature. When downsampling you are reducing resources by decimating the mesh. While one could theoretically upsample with a naive subdivision tessellation, it would not provide the same accuracy as when the mesh was created. A developer can always retain a hidden high resolution mesh or reload a high resolution mesh to upsample.

**Comment by yarikoptic** [comment]
Gotcha, indeed original use case "of mine" was asking for the latter -- to increase resolution while zooming in to a specific loci. It is when zooming in, higher resolution becomes needed

**Comment by neurolabusc** [comment]
@yarikoptic it is easy to write your own code to tesselate and upsample. For each iteration, each parent triangle is subdivided into four children triangles. Example JavaScript is the [NiiVue subdivide](https://github.com/niivue/niivue/blob/c0a701cc11ed554f17c165064c4d76d30dc33a6b/src/niivue-object3D.ts#L297) code that starts with a [icosahedron](https://prideout.net/blog/octasphere/) and subdivides to better represent a sphere. This subdivision of one triangle into four is shown here:

![Screenshot 2024-07-18 at 10 20 05 AM](https://github.com/user-attachments/assets/1dc2cccc-2871-4204-9ea3-5049463bf2d4)

The only trick is deciding where to place the new vertices. If new vertices are merely the linearly interpolated position of the parents, the result will be faceted and does not improve rendering (as the fragment shader already linearly interpolates from the vertex shader). Presumably, FreeSurfer subdivision is guided by voxel data to make a precise estimate of the surface being modeled (e.g. pial surface). However, it sounds like you want upsample a mesh without any additional information. You could try [Laplacian Smoothing](https://doi.org/10.1111/1467-8659.00334) of your subdivided triangle positions such as [this JavaScript](https://github.com/niivue/niivue-mesh/blob/7261977ebb1d969dc687a5cea29bf3bb96999f0b/marching-cubes.js#L795), though this will necessarily lose high frequencies. Further, such niave methods may lead to self intersecting surfaces. I suspect there are [better methods for upsampling](https://github.com/fangq/iso2mesh/blob/aa78f3a1c9ffdc9dfd41b1ae290161d3233110a5/remeshsurf.m#L7), but it is outside my expertise and the mission for the NiiVue project. 

@fangq may have insight into upsampling meshes of cortical surfaces.

**Comment by fangq** [comment]
@neurolabusc, thanks for the mention. I agree everything you said - without additional volumetric data, subdivision followed by a smoothing would be the most common way to "upsample" a mesh. unless performing tetrahedral mesh generation is needed afterwards, fixing self-intersection may not be necessary for visualization purposes.

what you mentioned in an earlier reply - retaining a hidden high-res copy, and re-decimate based on the current zoom level - would also be a close solution to what @yarikoptic had in mind.
