### ISSUE TITLE
Custom nifti viewer

### ISSUE THREAD

**Issue by anazzani** [niivue/niivue#1048]
Hello.

I'm trying to customise the way nifti files are shown and manipulated.

The first thing I'd like to do is simulate mouse wheel behaviour using an html slider (input type="range") but I'm unable to figure out how to properly achieve this.

Can somebody share some insight or point me to the relevant API page(s)?

TIA.

**Comment by hanayik** [comment]
Hi @anazzani 

You can achieve this using the `moveCrosshairInVox` method.

Here's the API info:

https://niivue.github.io/niivue/devdocs/classes/Niivue.html#moveCrosshairInVox

And a demo showing it being used (you can view the page source to access the JavaScript)

https://niivue.github.io/niivue/features/draw2.html

**Comment by anazzani** [comment]
@hanayik thank you very much for your reply.

I'm not familiar with medical image manipulation: would have been impossible for me to find the correct solution without your input. :)

Would it be possible to change the mousewheel behaviour? I'd like to use it to control image zoom level.

**Comment by neurolabusc** [comment]
NiiVue provides several patterns for mouse/touch interaction, [you can try them out by using the `drag mode` pull-down menu in this live demo](https://niivue.github.io/niivue/features/dragCallback.html). View that page's source code to see how to change the behavior. These provide different gesture sets for interactions. I would say in general, as the developers of NiiVue we try to restrict how much customization is done to the gestures - we want users to be able to transfer their skills between different usages. This means that a user's motor memory works regardless of whether they are using AFNI, FSL, FreeSurfer's FreeView, OpenNeuro, etc. If you do find the existing presets inappropriate for your application, you can always make a fork.

Notice that the demo shows that you can set the dragging mode to `none` and create a custom callback. So we allow customized dragging but not scroll wheels. The one issue is that scroll wheels are limited to mouse input, while the drag gesture works across devices (mouse, touch, pen).

**Comment by anazzani** [comment]
@neurolabusc

Thanks Chris, with your additional help I was able to quickly change the UI as desired.

I understand the potential problems caused by excessive customization but, just to clarify my position, we are developing a web Nifti viewer for one of our customers and those request are coming from them (I suppose it's their personal preference and/or it's the way they are working currently).

Since this is our first experience with medical imaging, NiiVue seems the right tool because it offers so much out of the box and, so far at least, "it just works". ;)

I will take into consideration your concerns in the future to try and limit as much as possible "deviations" from what is considered industry standard practice.

Regards.
