### ISSUE TITLE
Load nifti + lesions files

### ISSUE THREAD

**Issue by anazzani** [niivue/niivue#1049]
Hi all.

I'm trying to load in the viewer a nifti file AND the associated lesions file.

I thought this could be what I'm looking for https://niivue.github.io/niivue/devdocs/classes/Niivue.html#loadDrawingFromUrl

But when I inspect the source code of the linked live demo ( https://niivue.github.io/niivue/features/draw.ui.html ) the only mention I see of loadDrawingFromUrl is commented.

Is this the correct approach and is there a working demo I can take inspiration from?

TIA.

**Comment by hanayik** [comment]
@anazzani , You can get some inspiration from this demo:

https://niivue.github.io/niivue/features/draw2.html

Here is the source in git:
https://github.com/niivue/niivue/blob/main/demos/features/draw2.html

All demos sources are here as well:
https://github.com/niivue/niivue/tree/main/demos/features

Let us know if you have a use case that isn't covered in those demos.

**Comment by anazzani** [comment]
@hanayik thanks for your prompt assistance: everything works as expected.

Just one follow-up question: I see a couple of warnings in the browser's console both in your demo and in my app ("voxels not aligned with world space" and "99% of voxels are zero: ignoring zeros for cal_max"). Can they be ignored or is it something I should be concerned about?

Regards.

**Comment by hanayik** [comment]
@anazzani , Those are warnings, so it is up to you how to treat them 😉. In general, niivue provides sensible logic for handling many types of images. 

If you want to suppress warnings, then you can set the logLevel when you initialise a new niivue instance like this:

```js
const config = { logLevel: 'error' } // or 'silent' (not recommended). You can add other options too. See demos. 
const nv = new Niivue(config)
```

**Comment by neurolabusc** [comment]
@anazzani @hanayik is correct. For more details:
 - Raw images from MRI/CT scanners are often aligned to the participant anatomy, not world space. This means you may want to choose if the scan is visualized in image space or interpolated to world space. The `world` check-box [live demo](https://niivue.github.io/niivue/features/worldspace.html) illustrates these options.
 - Raw MRI images often have a few voxel intensities that are extreme outliers. Therefore, it is common to clamp voxel colors the 2% and 98% thresholds to maximize visual dynamic range (e.g. the contrast from black to white, to maximize contrast between tissues). However, with lesion maps and pre-thresholded images, there are often a huge number of voxels at the minimum and maximum intensity values, so it makes sense to use a different heuristic. This warning is expected with these sorts of images.

**Comment by anazzani** [comment]
Thank you very much Taylor and Chris for taking time to reply.

I'm really impressed by the level of support you offer, even to newbies like me.

I will have to digest this all, one bite at a time. :)

Cheers!
