### ISSUE TITLE
Is there an equivalent of setGamma for brightness / contrast?

### ISSUE THREAD

**Issue by anazzani** [niivue/niivue#1053]
Hi all.

I made a custom slider controlling gamma through the [setGamma](https://niivue.github.io/niivue/devdocs/classes/Niivue.html#setGamma) method.

I'd like to do the same for brightness and contrast: is this possible?

TIA.

**Comment by anazzani** [comment]
Anyone?

**Comment by neurolabusc** [comment]
There are a lot of ways to change the birghtness and contrast. 
 - the user can drag over the image area to optimize the brightness/contrast for the selected region
 - you can load a colormap that specifies a color range. MRI scans have relative brightness, so it is hard to have universal values, but CT scans have calibrated intensities. Therefore the `ct_*` colormaps explicitly set the color range. For an example, look at the [test image live demo](https://niivue.github.io/niivue/features/test_images.html), choose a `ct_*` image from the top toolbar and then select the different `ct_*` colormaps from the bottom toolbar.
 - You can explicitly set the cal_min and cal_max. Make sure you use the updateGLVolume() function after you have applied your changes - this allows you to change a lot of properties and defer the computationally expensive processes until all is done.

```
      calMinSlider.oninput = function () {
        nv1.volumes[0].cal_min = this.value
        nv1.updateGLVolume()
      };
```

Note that neuroimaging and NiiVue use the min and max values to specify the colormap range. For medical imaging it is typical to specify the window center (brightness) and window width (contrast). The window center is the midpoint between min and max, and the width is the range between min and max.
