### ISSUE TITLE
feature: allow equally sized quadrants for multiplanar slice view

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#1054]

**Comment by neurolabusc** [comment]
@hanayik can you test out this commit? When you run `npm run dev` the live demo has an `EqualSize` check box. The crosshairs are still constrained to the voxels, but voxel based images are each in equally sized tile. Not sure if this is desired for the mosaic view as well.

![Screenshot 2024-09-02 at 1 21 32 PM](https://github.com/user-attachments/assets/ccdff607-4fd0-471e-8d08-56a73b74e600)
