### ISSUE TITLE
Support for Freesurfer thickness files

### ISSUE THREAD

**Issue by bwagnerwork** [niivue/niivue#1056]
Would it be possible to add support for Freesurfer thickness maps?  I'd like to overlay the thickness information on a pial image.

If this already exists, could you help point out the error in the following code?  I'm getting a runtime error: niivue-warn Unknown layer overlay format lh.thickness.

```
        STImage = new niivue.Niivue();
        STImage.attachTo('THICKNESS');
        let loadSTPromise = STImage.loadVolumes([
            {
                url: '741/T1.mgz',
                name: 'T1.mgz',
                opacity: 0,
            },
        ]);
        let loadSTMeshPromise = STImage.loadMeshes([
            {
                url: '741/lh.pial',
                name: 'lh.pial',
                layers: [
                    {
                        url: '741/lh.thickness',
                        colormap: 'warm',
                        cal_min: 0,
                        cal_max: 4,
                        opacity: 0.7,
                    }
                ],
            },
        ]);
        STImage.setRadiologicalConvention(true);
        STImage.setSliceType(STImage.sliceTypeRender);

```

**Comment by neurolabusc** [comment]
This is a limitation of FreeSurfer files, that do not use a consistent file naming extension. The solution is to prove an extension hint as the `name` (which is distinct from URL) - use `.curv` to flag a FreeSurfer format scalar layer:


```
      var meshLHLayersList1 = [
        {
          url: "./lh.thickness",
          name: "thick.curv",
          cal_min: 0.0,
          cal_max: 0.8,
          colormap: "actc"
        },
      ];
      await nv1.loadMeshes([
        {
          url: "./lh.pial",
          rgba255: [255, 255, 255, 255],
          layers: meshLHLayersList1,
        },
      ]);
```
<img width="416" alt="Screenshot 2024-08-29 at 3 17 18 PM" src="https://github.com/user-attachments/assets/bc8665d7-8c56-4d7f-9b02-75d7495132ad">

**Comment by neurolabusc** [comment]
Latest commit will assume a layer is FreeSurfer if it has the extension `curv`, `crv`, `area` or `thickness`. As a Hail Mary, if the extension is not recognized it will read as FreeSurfer if first three bytes of the file are 0xFFFFFF.

**Comment by bwagnerwork** [comment]
Thanks for the updates.  Providing a name seems the most stable solution.  Hopefully the hail mary solution doesn't cause too many headaches.

**Comment by neurolabusc** [comment]
This image re-emerges with the new loadImages() function. We need a way to detect double-barreled extensions "lh.sphere.reg",  "lh.sphere.left_right", "mesh.iwm.cbor", "img.nii.gz". There are also ambiguous cases where a .vtk file could be an image or mesh. I am submitting a commit that improves the situation,  but it might be worth refactoring. A major feature is our ability to handle diverse formats, but the detection of some formats is challenging.
