### ISSUE TITLE
Support ASCII NRRD encoding

### ISSUE THREAD

**Issue by MattTheCuber** [niivue/niivue#1057]
Moved from https://github.com/niivue/niivue-vscode/issues/68

Here is an example scan from pynrrd: https://github.com/mhe/pynrrd/blob/master/nrrd/tests/data/test2d_ascii.nrrd

**Comment by neurolabusc** [comment]
NiiVue supports voxel based images using binary data. [NRRD](https://teem.sourceforge.net/nrrd/format.html) can support either ASCII or binary encoding. While ASCII image data may be useful to illustrate a format, it imposes severe penalties with regards to file size, i/o times and precision for floating point data.  NiiVue is open source, so feel free to make a PR to address this. However, I regard this as out of scope for our development team. We have really focused on making NiiVue lean  and high performance. Supporting inherently poor variations of formats can undermine this emphasis. Thankfully, ASCII based NRRD adoption seems vanishingly rare beyond a few examples. It is worth noting that NiiVue does support a few ASCII-based mesh format variations: FreeSurfer, GIFTI, OBJ, PLY, STL, and VTK. Our support for these reflects their popularity, and should not be seen as a recommendation for their adoption.
