### ISSUE TITLE
can't set opacity of background image to zero in 3D view

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#107]
see an example here: https://niivue.github.io/niivue-ui/ and try to hide the background image in 3D mode.

**Comment by neurolabusc** [comment]
The typical way would be to apply a color transfer function to the volume that sets all the alpha values of the 3D texture to 0. This is computationally costly. One easy hack would be to provide a special value for the clip plane to skip the background volume, e.g.:

```
vec4 applyClip (vec3 dir, inout vec4 samplePos, inout float len) {
	if  ((clipPlane.a < -1.0) return len + 1.0;
....
```

**Comment by hanayik** [comment]
@cdrake , could this be related to the new way the 3D object render loop is working?
