### ISSUE TITLE
windowing of 4D images

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#1073]
When a 4D image is opened, it seems like the windowing (right mouse button window drawing for contrast adjustment) is always performed on the first echo/timepoint.

Steps to reproduce:
Open this link: https://niivue.github.io/niivue-vscode/?images=https://korbinian90.github.io/Shared_Data/test4D.nii.gz
Select View -> Multiplanar + Time Series
Test: Windowing works fine on first timepoint
Problem: Selecting a later time point, the windowing does not work

**Comment by neurolabusc** [comment]
I will investigate. This is particularly relevant for DWI scans, where the b=0 volumes have a lot more signal than the b-weighted volumes.

**Comment by hanayik** [comment]
@neurolabusc , and @korbinian90, perhaps we should add the 4th dimension [here](https://github.com/niivue/niivue/blob/ee66d4a6b7f3d35c83fd919aef9b4d68ef2c4ef8/src/niivue/index.ts#L1266) in `calculateNewRange`. And use the `.frame4d` property as the offset so we calculate `hi` and `lo` from the specific volume in the time series.

**Comment by korbinian90** [comment]
I noticed as well that when first opening a 4D image with the intensity reducing over the 4th dimension, the first volume is scaled too bright. Probably it calculates the scaling from all the 4D data.
Would your approach help in that case as well @hanayik?
Would it make sense to store one scaling per 3D volume? But that might make it overly complicated..

**Comment by neurolabusc** [comment]
@korbinian90 I believe that the intensity is scaled based on the first volume. If the first volume is much brighter than the subsequent ones, it is likely one of two reasons that are inherent to the MR sequences: 

1. for 4D MRI timeseries the first volume appears brighter than subsequent volumes due to T1 relaxation effects. On some scanners, you can adjust the number of dummy volumes acquired before volumes are stored to minimize this effect.
2. For DWI images, most sequences start with a b=0 volume, with subsequent volumes using b-weighting. The b=0 volumes always have a lot more signal than b-weighted images.

**Comment by korbinian90** [comment]
@neurolabusc I still think the image is scaled based on all 4D data and not only the first 3D volume. You can test it here: https://niivue.github.io/niivue-vscode/?images=https://korbinian90.github.io/Shared_Data/test4D.nii.gz
This is just a gradient image getting larger for later time points. When opening, the first 3D volume is quite dark. It's intensity goes from 1 to 32, but it is scaled to about the range [2;120]. The last time point goes up to 128, so that is why I think the whole 4D volume is used for scaling.
Maybe this does make sense? With that scaling, all 3D volumes can be viewed somewhat fine without needing rescaling.

**Comment by neurolabusc** [comment]
@korbinian90 you are correct, the current algorithm uses [all loaded voxels](https://github.com/niivue/niivue/blob/ee66d4a6b7f3d35c83fd919aef9b4d68ef2c4ef8/src/nvimage/index.ts#L2654) to calculate the robust range. I do think there will be edge cases where using values from one or all volumes will be better.
 
```javascript
const nVox = this.img.length
```
My thought is that we update the function `calMinMax()` to be `calMinMax(vol: number = 0)` where `vol` defines the volume used for calculation (indexed from zero) and a negative value uses voxels from all volumes for the calculation. I do think for most use cases, it is good to keep the same contrast/brightness (window width/center) across volumes to see relative changes in intensity, with callbacks allowing a way to deal with special use cases.
