### ISSUE TITLE
Measure tool text placement

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#1090]
Our clinical users have provided feedback that it's contradicting to put the measurement tool's text right over what the user is trying to measure.

![image](https://github.com/user-attachments/assets/897cb7f2-c5b0-4f02-9819-e084e47d6d08)

I wrote some code which places the text a distance away from either the drag point origin or the mouse.

https://github.com/user-attachments/assets/99f6ef3a-98a1-4abd-9cfc-2b5997d56a7d

https://github.com/user-attachments/assets/2fdfc2d0-60e0-475b-9213-ac39e98fcf3a

Could we consider putting these functionality as standard features of NiiVue? Here's the code:

```typescript
import {Niivue} from "@niivue/niivue";

class CustomNiivue extends Niivue {
  drawTextBetween(startXYendXY: number[], str: string, scale?: number, color?: number[] | null) {
    const [x0, y0, x1, y1] = startXYendXY;
    const [x, y] = extendTo(x0, y0, x1, y1, 30);
    const modifiedPos = [x, y, x + 1, y + 1];
    super.drawTextBetween(modifiedPos, str, scale, color);
  }
}

/**
 * Return a point a specified distance away from (x0, y0) in the direction of the vector from
 * (x0, y0) to (x1, y1).
 */
function extendTo(x0: number, y0: number, x1: number, y1: number, distance: number): [number, number] {
  const x = x0 - x1;
  const y = y0 - y1;
  if (x === 0 && y === 0) {
    return [x1 + distance, y1];
  }
  const c = Math.sqrt(x * x + y * y);
  const dX = distance * x / c;
  const dY = distance * y / c;

  return [x0 + dX, y0 + dY];  // next to start point
  // return [x1 - dX, y1 - dY];  // next to end point
}

export default CustomNiivue;
```

**Comment by rudolphpienaar** [comment]
Not sure if it this is a separate issue but it seems at least linked:  the default font size. It is rather large and might be better if smaller.

**Comment by jennydaman** [comment]
@rudolphpienaar regarding the default font size, @neurolabusc commented on it before https://github.com/niivue/niivue/issues/857#issuecomment-1908825571

**Comment by rudolphpienaar** [comment]
Accounting for my nativity, I see the font size and cross hair width is closed. I read the explanation of _why_ and _how_ it work(ed) the way it did but it wasn't entirely clear if the demonstrable observation of fonts just generally being too big was addressed. This is of course very apparent on very high resolution screens...

If you have a second, is an absolute size spec now available? I'm thinking of the measure tool in cornerstone that we use. Numbers are small but very legible. This is closer to the expected behavior.

**Comment by neurolabusc** [comment]
We discussed this yesterday. Consensus was to allow font size to be specified either by relative size or by pixel size, similar to CSS. The linked measurement tool PR shows how this can be implemented with backward compatibility. I am happy to take the lead on this. However, lets wait for the new [uikit font](https://github.com/niivue/niivue/pull/1089) features to be adopted. So deferring work on this for a week or so...

**Comment by cdrake** [comment]
The uikit adds a draw calipers function.  This keeps the area visible.  The offset is a parameter allowing a caller to move the text further away.
<img width="189" alt="Screenshot 2024-11-03 at 12 19 51 PM" src="https://github.com/user-attachments/assets/d666eed5-91c7-41a1-9083-32b8ba887b85">
<img width="174" alt="Screenshot 2024-11-03 at 12 20 08 PM" src="https://github.com/user-attachments/assets/879887e9-da5f-4984-b342-ac3b2a348612">

**Comment by neurolabusc** [comment]
Related to the caliper tool, we should decide how rulers aredrawn with multi-pixel line thicknesses. The [DICOM standard](https://dicom.nema.org/dicom/2013/output/html/part03_withmml.html#sect_C.10.5.1.3.8) provides little guidance. With high-dpi display the single-pixel lines drawn by many tools can be fine hairlines. Does ruler length include the width of the line, or does this inflate the length. So is length inclusive of tick marks?



![ruler](https://github.com/user-attachments/assets/22b2947f-e5a6-49e3-ac3d-4ed682612a2a)

**Comment by cdrake** [comment]
My two cents is that I like the points (3rd drawing). It will allow us to be precise in our measurements.

**Comment by francopestilli** [comment]
1 and 3 seem better to me. I wonder whether a version of 3 with arrow-heads for each tick in the ruler has been considered.

**Comment by anibalsolon** [comment]
I found the 3rd option interesting, too-- wondering if the arrow needs to extend below the other ticks

**Comment by dipterix** [comment]
```
| |---+---+---+---+---+---+---+---+---+---| |
| |   |   |   |   |   |   |   |   |   |   | |
| |                   |                   | |
 v                                         v
```

**Comment by cdrake** [comment]
Here's my first go at the ruler. Please feel free to provide feedback.
<img width="351" alt="Screenshot 2024-11-07 at 10 38 19 PM" src="https://github.com/user-attachments/assets/98d348b2-52ce-4872-9cf7-67a10543f18e">

**Comment by hanayik** [comment]
[This](https://github.com/niivue/niivue/issues/1090#issuecomment-2463694543) is now the default measure tool, and will be available in the next NPM release.
