### ISSUE TITLE
update github pages action to build and deploy

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#111]
currently niivue.js (the bundled version of niivue) is stored in /docs and /demos and causes merge conflicts occasionally. It would be nice to add this to gitignore and have github pages run a build and then deploy rather than storing the files in the source code purely for github pages.

**Comment by neurolabusc** [comment]
I suggest /tests, /docs and /demos be made submodules, in the same way that dcm2niix uses submodules like /dcm_qa to test the core code. The core code that can be embedded into other projects should be kept as lean as possible.

**Comment by hanayik** [comment]
Hi @neurolabusc, submodules can be useful sometimes, but I'd prefer not to use them for this. I often find they can overly complicate development and management. I should be able to remove the offending build files (by putting them in.gitignore) and keep our dev workflow identical. Just need to update the github action that deploys our demos

**Comment by neurolabusc** [comment]
Understood. Your view is clearly justified.
