### ISSUE TITLE
Disabling the Crosshair for now Render Slices

### ISSUE THREAD

**Issue by Philip-Isaacs** [niivue/niivue#1111]
Is it possible to completely disable the cross hairs? I know it can be done for the Render mode (show3Dcrosshair: Boolean), but I am unable to do the same for the other slices. Is it possible to do? If not is there any work around?

**Comment by neurolabusc** [comment]
You can set `crosshairWidth` property - the [hero image live demo](https://niivue.github.io/niivue/features/hero.html) includes an interactive demo that lets you adjust this. To hide the crosshair, you set the `crosshairWidth` to zero:

```
nv1.opts.crosshairWidth = 0
```

**Comment by Philip-Isaacs** [comment]
Yup, this works. Thank you
