### ISSUE TITLE
MRIcroGL colormaps

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#112]
Here is a collection of all MRIcroGL colormaps [converted to NiiVue JSON format](https://drive.google.com/file/d/1rGPcVkRzUhL328vflY2IUPey2JmYD_0S/view?usp=sharing). I suggest discretion in including some of these. Tools like [JetFighter](https://elifesciences.org/labs/c2292989/jetfighter-towards-figure-accuracy-and-accessibility) will nag people who use color schemes which are considered to have poor accessibility and accuracy features. I include many of these merely for historical purposes. A better curated list would help. Some of the color maps are not perfect copies of original 256-color tables: those use interpolation for each index to coerce integer values of 0..255, and also can model non-linear functions. Here, the color tables are created with a small number of nodes, with linear interpolation between nodes.

The MRIcroGL color editor allows users to interactively modify colormaps. It also allows user to save colormaps (see Help/MouseGestures for OS dependent modifier keys). In future releases, if the user specifies saving the file with the extension '.json', it will export the color map to NiiVue format.

**Comment by hanayik** [comment]
@neurolabusc, these new JSON colormaps omit the alpha channel. Is this intentional? The existing NiiVue colormaps include alpha, and the MRIcroGL luts also seem to include the alpha channel in the node definitions.

**Comment by neurolabusc** [comment]
Try [these](https://drive.google.com/file/d/1LX5PGQdmhDfLhRwB_DrQBL7Il08h9ksY/view?usp=sharing)
