### ISSUE TITLE
Support for color-coded ODF files in MRtrix (.mif) format

### ISSUE THREAD

**Issue by MoniDoerig** [niivue/niivue#1120]
Hi NiiVue team,

I am currently working on translating some of your NiiVue examples from the live demos to ipyniivue, such as the **modulateTrix** example. This example works well for tensor data, but I am encountering challenges when trying to work with ODF files in the MRtrix (.mif) format.

The issue lies in the ODF ```.mif``` file so that colors are encoded based on direction, similar to the tensor example. I’ve been unable to find a method to prepare the file in a way to achieve this, as the ```.mif``` matrix stores voxel data in a different representation compared to ```FSL```.

Here is a code snippet from the ipyniivue implementation. Currently, wmfod.mif is displayed in grayscale (or I could use any of the available colormaps).

```javascript
import ipyniivue as nv

nv1 = nv.NiiVue(
    back_color=[0.0, 0.0, 0, 1], 
    show_3D_crosshair=True,
    crosshair_width=0.1,
    drag_mode=nv.DragMode.PAN,
    yoke_3D_to_2D_zoom=True,
    is_force_mouse_click_to_voxel_centers=True,
    is_nearest_interpolation=True,
    is_v1_slice_shader=True
)

volume_list = [
    {"path": "vf.mif", "colormap": "gray", "opacity": 0.6},
    {"path": "wmfod.mif", "opacity": 1.0}   
]

nv1.load_volumes(volume_list)
display(nv1)
``` 

I would like to request the development of tools or functionality within NiiVue to support ODF ```.mif``` files with the ability to process and visualize them with appropriate color encoding for directionality.

**Comment by Lestropie** [comment]
Hi @MoniDoerig,

@neurolabusc pinged me regarding your question.

1. ODF files do not "encode colour" in any way. Each voxel contains a spherical harmonic function, from which a glyph can be produced by sampling the amplitudes of that function along a large number of directions. That glyph can then have colours attributed to each vertex based on the directions of those samples.

2. If what you are looking for is strictly a directionally-encoded colour image, that is a 4D image with 3 volumes corresponding to RGB components, then take a look at [the `fod2dec` command](https://mrtrix.readthedocs.io/en/3.0.4/reference/commands/fod2dec.html) (method described [here](https://www.researchgate.net/publication/276412466_Time_to_move_on_an_FOD-based_DEC_map_to_replace_DTI's_trademark_DEC_FA). If `niivue` supports data encoded in this way, then it should be able to display such agnotically to how it was produced.
   Note that in these data (as with all MRtrix3 commands), the RGB components are defined with respect to "real" / "scanner" space, agnostic to the orientation of the voxel grid. This is contrary to eg. tensor eigenvectors from FSL, which define their components with respect to the image axes (there can be an annoying hidden sign flip in there also, but for displaying as an RGB colour image, as long as the software takes the absolute value as the intensity it shouldn't matter).

3. If what you're looking for is discrete orientations to be displayed as lines within each voxel, then you need to perform the requisite calculations to get from the ODF spherical harmonics functions in S2 to discrete orientations in R3. The fastest is `sh2peaks`; the more advanced method is `fod2fixel`, which you would then likely need to convert from our [fixel directory format](https://mrtrix.readthedocs.io/en/3.0.4/fixel_based_analysis/fixel_directory_format.html) to the more conventional format, being a 4D image where triplets of volumes encode 3-vectors, via `fixel2peaks`.

**Comment by MoniDoerig** [comment]
Hi @Lestropie and @neurolabusc 

Thank you for your detailed explanations!

The goal was to create a visualization similar to [this ODF example](https://andysbrainbook.readthedocs.io/en/latest/MRtrix/MRtrix_Course/MRtrix_05_BasisFunctions.html#fiber-orientation-density-fod), but simplified by displaying only the predominant (discrete) direction as a color-coded image instead of full glyphs. This would effectively combine the outputs of ```fod2dec``` and ```sh2peaks``` by:

1. Rendering the DEC map as the background image, and
2. Overlaying the fiber direction lines, color-coded using the DEC map's RGB values.

I’ve already tried visualizing the output of ```fod2dec``` using ipyniivue, but it appears that ipyniivue does not support rendering such 4D volumes (with RGB components encoded this way). The output is displayed as a grayscale image instead.

That's why I was wondering if it would it be possible to consider adding support in niivue to render the output of ```fod2dec``` as a proper color image?

**Comment by Lestropie** [comment]
The background images there are encoding the results of a multi-tissue decomposition, not ODF orientation. From what you are describing, I think that what you are looking for possesses neither the background image nor the glyph overlay of the example you linked, in which case referencing it here as an example is causing more confusion than it is resolving.

Within MRtrix we both generate DEC images as 4D images with 3 volumes, and automatically interpret incoming images that possess 3 volumes as RGB components for the purpose of visualisation. This is however known to not the case for many other softwares. Some may demand that the three colour components appear along the fifth rather than fourth axis; others may demand that the relevant "intent code" in the NIfTI header be activated (MRtrix neither reads nor writes from these as all of our commands are compatible with many image formats besides NIfTI). Such massaging may be all you need here.

> displaying only the predominant (discrete) direction as a color-coded image instead of full glyphs

There is perhaps a distinction being overlooked here. `fod2dec` does *not* produce an RGB colour per voxel that corresponds to "the predominant direction". What it produces is a voxel aggregate colour as a weighted mean across the entire sphere. This avoids the artifactual discontinuities where a single unique direction per image voxel can transition sharply between adjacent voxels.

If what you want is a single discrete direction per image voxel from an ODF, then you should be using either `sh2peaks`, or `fod2fixel` followed by `fixel2peaks`. If the image content stored within each image voxel is three values corresponding to an orientation in R3, then that can be interpreted by visualisation software either to set the fill colour of voxels or to draw a coloured line within each voxel; but the data are the same.

> Rendering the DEC map as the background image, and
> Overlaying the fiber direction lines, color-coded using the DEC map's RGB values.

If the fibre direction lines being overlaid were to be the same colour as the underlying voxel, then the lines would be completely invisible (absent any clever lighting effects that would only make them a little less invisible).

**Comment by neurolabusc** [comment]
@MoniDoerig NiiVue has a custom shader to render the principal eigenvector (V1) as seen in the [FSL](https://niivue.github.io/niivue/features/modulate.html), [DSI studio](https://niivue.github.io/niivue/features/modulateDSI.html), and [MRTrix](https://niivue.github.io/niivue/features/modulateTrix.html). It can show streamlines created by all these tools including colors that represent global direction, local direction, per-vertex scalar and per-streamline scalar values as shown in [this live demo](https://niivue.github.io/niivue/features/tracts.html). I think a typical use case is to use V1 to ensure that diffusion directions have been correctly determined and then test that the derived streamlines perform well at locations where fiber bundles cross (e.g. in voxels with crossing, one can observe low FA and streamline algorithms need to disambiguate crossing versus kissing fibers).

The custom fragment shader for V1 only models a single direction, so you would need to develop your own custom shader for the full MRtrix FOD. An elegant property of the V1 is that we can represent it with four components (3 directions: X,Y,Z and the fractional anisotropy) which maps perfectly onto the WebGL2 3D textures that can store up to four components (RGBA). This allows the NiiVue fragment shader to infer the fixel natively and in parallel. I note that the MRtrix FOD format stores 45 components per voxel - so a custom shader will need to represent this across many textures, or some stage will need to map these onto a triangulated mesh. A key design feature of WebGL2 is it is the lowest common denominator across modern graphics APIs (it is implemented using the devices native API: OpenGL ES, Vulkan, Metal and DirectX). Therefore it lacks powerful but power-hungry features such as a geometry shader that would aid showing the FOD.

The problem you are trying to solve is outlined in [this publication](https://www.researchgate.net/publication/276412466_Time_to_move_on_an_FOD-based_DEC_map_to_replace_DTI's_trademark_DEC_FA), and my sense is that the renderings shown in the bottom panels of Figures 3 and 4 would be very hard to do interactively on all the devices that support WebGL2. The current live demos show the background image as the bottom panel of Figure 2 (the DEC FA) and you should be simply able to load your FOD-based DEC map (with RGBA colors) and use this to modulate the V1 map. However, while this will ensure that fibers are salient in voxels with fiber crossing, it will only show V1, without information regarding the competing directions. So this solution is easy to implement, but may have more limited utility. My sense is that there needs to be a clear understanding if the benefits and limitations of this approach meets the needs of your user base.

**Comment by MoniDoerig** [comment]
Thank you @Lestropie and @neurolabusc 
Indeed, all I needed was to convert the output of ```fod2dec``` to NIfTI format and activate the "intent code" in the NIfTI header (set to 1007). Once this adjustment is made, the directionally-encoded color image is displayed correctly in ipyniivue, which allows for quick visual inspection and control of intermediate analysis steps during interactive tutorials within Jupyter Notebooks.
