### ISSUE TITLE
Suggestion for "Downscaling" NIfTI volume for displaying in Niivue

### ISSUE THREAD

**Issue by thangngoc89** [niivue/niivue#1126]
Hi,

Thank you for continuing to develop and add features to Niivue—it’s a fantastic tool!

I’m currently using Niivue for a website that runs AI-based segmentation on CT/MRI images. Some of the volumes, after conversion to NIfTI, are quite large (200–300 MB is typical), which makes the Niivue interface slow, even on high-end hardware (my workstation is an i9 with an RTX 4090).

Do you have any suggestions for downscaling these volumes? I’d prefer a Python-based solution since my processing pipeline is already server-based.

Thanks again!

**Comment by neurolabusc** [comment]
@thangngoc89 downsampling data depends a lot on your source images. For T1-weighted magnitude MRI scans of the brain, where the size of the object is known, the origin of the image is typically know (either iso-center or anterior commissure) and the image contrast falls into a narrow dynamic range, people often conform the data to UINT8 (voxel intensity 0..255,  scaling for 0..99% of voxel intensities) with 1mm isotropic is sufficient with a 256x256x256 resolution resulting in a compact 16mb image. The FreeSurfer executable [mri_convert](https://surfer.nmr.mgh.harvard.edu/fswiki/mri_convert) will conform data very rapidly, while [niibabel](https://nipy.org/nibabel/reference/nibabel.processing.html) provides a Python port.

Things are more tricky for CT - here the voxel intensity is scaled in Hounsfield units with air at -1000 and bone at +1000, with metal fillings much brighter. However, if you are interested in soft tissue, the difference in terms of intensity fills a tiny part of this dynamic range, with CSF, gray matter, white matter, and muscle all in the 0..50 range (with blood ~150 for images with contrast). So for CT, if you are only interested in bone, the UINT8 is sufficient, but for soft tissue you need to either clamp you window width or use higher precision (e.g. UINT16). The SNR of bone to other tissues is very high, so you will want to retain high spatial resoultion if you are interested in bone. On the other hand, the SNR of different soft tissues relative to each other is much lower for CT than a T1 scan, and therefore spatially downsampling makes sense. Further, with CT scans the DICOM origin is the table center, not the isocenter, so this varies a lot with different individuals (e.g. with height of participant). Therefore, you may want to use the volume center as your origin.

Another challenge is that different body parts may have fields of view. So the 1mm isotropic with 256^3 dimensions useful for T1 scans may not be suitable.

Downsampling data is [challenging](https://neurostars.org/t/downsample-image/16677/7) as one needs to avoid high frequencies aliasing as lower frequenceis. A common solution to this is to use trilinear interpolation (B = 1, C = 0) or even a Gaussian blur prior to resampling. Both of these remove high frequencies. I also like the [Mitchell–Netravali](https://en.wikipedia.org/wiki/Mitchell%E2%80%93Netravali_filters) filter where B = 1/3	and C = 1/3 which balances blurring to avoid aliasing and a mexican-hat kernel to retain high frequencies.

If you know the anatomy (e.g. head) and modality (e.g. CT without contrast), you can spatially normalize (coregister) every image to a common template of known resolution and dimensions. I would suggest [ANTsPy](https://github.com/ANTsX/ANTsPy) as a nice Python wrapper for the robust and high performance (though slow) ANTS.

I do think that nibabel and ANTsPy provide the Python tools you need, but you will need to use them wisely depending on your source data and application.

**Comment by thangngoc89** [comment]
Thank you for your very detailed answer. For context, I’m mostly dealing with dental CBCT. My first attempt was scaling to uint8 but I loss a lot of contrast and details. I will experiment with the techniques you mentioned. My aim is sub 30MB for most volumes.
