### ISSUE TITLE
How to adjust mesh opacity

### ISSUE THREAD

**Issue by thangngoc89** [niivue/niivue#1127]
I’m using NiiVue to render multiple meshes (PLY format) based on the [mesh example](https://niivue.github.io/niivue/features/meshes.html).

Everything works well except for controlling the opacity of individual meshes.

Here’s what I’ve tried:
- Setting the opacity property when loading meshes using URL options.
- Modifying the opacity later with the following code:

```ts
nv1.setMeshProperty(nv1.meshes[0].id, "opacity", 0.2)
```

However, neither approach seems to have any effect.

The only method that works is enabling meshXRay on the nv1 instance, but this affects all meshes globally, which isn’t what I need.

Is there a way to control the opacity of individual meshes, similar to how the [mesh layers opacity example](https://niivue.github.io/niivue/features/mesh.layers.html) demonstrates?

**Comment by neurolabusc** [comment]
Our primary focus is to keep NiiVue fast even on low power phones and old hardware. Specifically, we try to have good performance on 1.1GHz thermally constrained [MacBook ](https://support.apple.com/en-us/111991) which is very imbalanced by combining a poor GPU with a high-DPI display (2560×1600). For this reason, have not focused on mesh translucency. In general, graphics shaders are designed to run in massively in parallel, with only the nearest vertex creating a pixel color. In other words, when looking at millions of triangles, the depth buffer is used to find the one that is closest to the camera for every pixel, and only that fragment influences the final color. A strength and weakness of WebGL2 is that it is designed to be the [lowest common denominator for modern graphics languages](https://en.wikipedia.org/wiki/ANGLE_(software)) - the advantage is that a single code base targets Vulkan, Metal and DirectX. However, it does mean that you do not have access to some very powerful but energy inefficient stages such as the geometry shader.

For this reason, NiiVue does not provide true mesh translucency. It does provide a feature called `meshXRay` that you can interactively try out with the sliders in this [live demo](https://niivue.github.io/niivue/features/mesh.loader.html) as well as this [live demo](https://niivue.github.io/niivue/features/pointset.html). The concept is [similar to what is described here](https://www.shapediver.com/blog/solving-a-common-webgl-issue-transparency-fixed). Be aware that setting a meshXray great than 0 typically halves the speed of rendering. Also, as you can see by using a high level in [this live demo](https://niivue.github.io/niivue/features/mesh.loader.html) you can see artifacts relating to the ordering of the parallel fragment shaders (which can be hardware specific).

Another option is the `outline` shader which you can selectively apply to a subset of your meshes - you can see this by pressing the `outline` button in [this live demo](https://niivue.github.io/niivue/features/mesh.loader.html). 
<img width="929" alt="Screenshot 2024-12-23 at 9 57 02 AM" src="https://github.com/user-attachments/assets/cff71a8f-df9c-4292-9fb1-98212fc59ff3" />

**Comment by thangngoc89** [comment]
@neurolabusc Thank you for your response. The reason I would like to control **individual** mesh opacity is because the meshes are overlapping. I would like to render something below (screenshot from 3D Slicer)
![https://raw.githubusercontent.com/gaudot/SlicerDentalSegmentator/main/Screenshots/dentalsegmentator_example.png](https://raw.githubusercontent.com/gaudot/SlicerDentalSegmentator/main/Screenshots/dentalsegmentator_example.png)

The bones are 0.5 opacity to display the teeth roots anatomy. Using meshXRay would make everything translucent. 

Is there anyway that I could construct my meshes to be able to load as layers just like the [mesh layers](https://niivue.github.io/niivue/features/mesh.layers.html) example? 

Or meshes are generated from NIFTI label file using vtk so even changing output format is doable.

Thanks.

**Comment by neurolabusc** [comment]
Yoou can load multiple meshes - view the source code of the  [mesh layers live demo](https://niivue.github.io/niivue/features/mesh.layers.html) to see how you can load multiple independent meshes and give them each unique properties including color, shader (e.g. the `outline` button only influences the cortex, not other properties:

```javascript
await nv1.loadMeshes([
	{
		url: "../images/BrainMesh_ICBM152.lh.mz3",
		rgba255: [255, 255, 255, 255],
	},
	{
		url: "../images/CIT168.mz3",
		rgba255: [0, 0, 255, 255]
	},
]);
```

You can apply XRay to this scene below you see none, light and heavy. With the heavy you can see a lot of artifacts from the fragment shader:

![xray](https://github.com/user-attachments/assets/908fab1d-58c6-4935-9974-4f1cf857e030)

I do think to replicate the behavior of Slicer3D you will want to develop your own shader: presumably you render both images as well as their depth buffers to offscreen textures, and then run a shader the blends the multiple images. NiiVue is open source, so feel free to develop this.

**Comment by thangngoc89** [comment]
Understood. Thank you for your detailed answer.
