### ISSUE TITLE
submit nifti writing PR to nifti-reader-js repo

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#135]

**Comment by neurolabusc** [comment]
@hanayik [see this](https://github.com/rii-mango/NIFTI-Reader-JS/issues/4). I had no problem using nifti-reader-js to write NIfTIs using [node.js](https://github.com/rordenlab/niimath/blob/a2f2d2825c6d1d934d98385d7dfe0b274d8b20e8/src/niimath.js#L211), I assume it is the same with a web page.
