### ISSUE TITLE
Load PNG as main image

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#144]
Currently, NiiVue only supports NIfTI volumes. @mrneont had noted that 3D NIfTI images can have large file sizes, making them slow to load. We already load 2D PNG files for our font rendering. I would suggest that we allow loading of PNGs for the main image. This would allow the server to rapidly load a 2D image for quality assurance, and the user could then request a 3D volume if they wanted to inspect it better.

When we implement this, the user can still adjust the alpha just like any other image. A nice use for this is quality assurance images. Consider the two images below: rather than load two different bitmaps, a single bitmap could store the grayscale image as the RGB components and the red outline as the Alpha component. By interactively changing the alpha, one could allow the outline to `bleed through`, and an animation could adjust the alpha allowing the flicker to show edges.

![amosaic](https://user-images.githubusercontent.com/8930807/136694453-1cb48ba4-d4d0-4046-9532-023383ee5e65.png)
![mosaic](https://user-images.githubusercontent.com/8930807/136694455-930c5731-227c-4842-9750-b2c412ef08ea.png)

This topic is related to a [niimath topic](https://github.com/rordenlab/niimath/issues/5)

**Comment by vincenzoml** [comment]
Can niivue load png files at the moment, as main images and overlays?

**Comment by neurolabusc** [comment]
You can load a PNG as a thumbnail, as [shown here](https://niivue.github.io/niivue/features/timeseries.html). PNG was designed as a 2D format, while NiiVue is really designed for 3D and 4D datasets. While PNG includes tags for [Physical Scale ](http://www.libpng.org/pub/png/book/chapter11.html#png.ch11.div.9) (e.g. pixdim) it does not provide an origin or angulation details, so it is under-specified for this use case.

The number of voxel-based formats has expanded a lot since this issue was first posted. NiiVue's currently supported native voxel-based formats [are listed here](https://github.com/niivue/niivue?tab=readme-ov-file#supported-formats). 

You an always create a custom loader plugin, as demonstrated by the [cbor loader](https://github.com/niivue/cbor-loader).

**Comment by vincenzoml** [comment]
Is any of these formats capable of showing coloured images? Is niivue itself able to do that?

**Comment by neurolabusc** [comment]
@vincenzoml yes, NiiVue can support RGB images. DICOM, NIfTI and NRRD define RGB images. A nice example is the [test_images live demo](https://niivue.github.io/niivue/features/test_images.html) where you can select the `visiblehuman` test image, which is a RGB NIfTI. Another example is the [minimal UI live demo](https://niivue.github.io/niivue/features/ui.html), where choosing the Script/CTCBF menu item loads a RGB NIFTI.

**Comment by vincenzoml** [comment]
Thanks a lot! Am I correct in thinking that selecting a colormap in this case has no effect? For those reading this issue and like me, not being sure, a simple way to convert a coloured PNG to a nifti is to just use SimpleITK primitives to load and then save the image (meaning that also my own tool voxlogica does that directly).

**Comment by neurolabusc** [comment]
@vincenzoml the colormapping for rgb images is explicit, so any provided colormap is ignored. You can observe this with the [test images live demo](https://niivue.github.io/niivue/features/test_images.html) - note that the colormap buttons on the lower panel influence all the selections of images from the top panel, with the exception of the RGB visible human. For completeness, the `gamma` property is also ignored for RGB images.
