### ISSUE TITLE
Image loading use cases and interactions

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#149]
There are multiple approaches to loading images in a viewer. This issue is meant to define the behaviour of NiiVue when various image loading actions take place. 

Comments from all are welcomed. Pinging some interested users here: @nellh, @cdrake, @neurolabusc, @soichih, @rogiedodgie, @pieper, @mrneont, @afni-dglen

## Loading multiple images programmatically

Images can be loaded programmatically by supplying an array of objects with image sources. If the array contains more than one image then the images are loaded and overlayed in order of appearance in the array. The first image (item 0) is the background image. 

example:

```
let niivue = new NiiVue()
niivue.loadVolumes(
  [
    {
      url: "some_image.nii.gz"
    },
    {
      url: "another_image.nii.gz"
    }
  ]
)

// as long as each object has a resolvable "url" property, the objects will be converted to NVImage instances. 
```

## adding a single image programmatically

If there are no existing images in the canvas, then the loaded image will become the background. If there are existing images in the canvas then the loaded image will become an overlay. It is the user's responsibility to be mindful of different image spaces when adding image as overlays. If you want to load a single image programmatically and remove all existing images, the supply a value of `true` as the second argument to `addVolume`. 

```
niivue.addVolume(NVImage.loadFromUrl("some_new_image.nii.gz"))

niivue.addVolume(NVImage.loadFromUrl("some_new_image.nii.gz"), true) // remove all existing images. The default is false

// or

niivue.addVolume(NVImage.loadFromFile(FileObject))

niivue.addVolume(NVImage.loadFromFile(FileObject), true) // remove all existing images. The default is false

```

## drag and drop a single image file or URL

Dropping a single image file or a single URL onto the canvas will remove all existing images and load the new image. The new image will become the background image in the stack. 

## drag and drop a single image file or URL while holding SHIFT

Dropping a single image file or URL onto the canvas while holding the SHIFT key will add the new image as an overlay. It will become the top image in the stack of all loaded images. If there are no existing images then the new image becomes the background. 

## drag and drop multiple image files or URLs

Dropping multiple image files or URLs onto the canvas will remove all existing images and load all new images in the order of the received file or URL list. The first image in the received list will become the background image, and all others will be loaded as overlays in the order of the received list. 

## drag and drop multiple image files or URLs while holding SHIFT

Dropping multiple image files or URLs onto the canvas while holding the SHIFT key will add the new images as overlays. The images will be added in the order of the received list of files or URLs. If there are no existing images then the new images are loaded in order of the received list, and the first image in the list becomes the background.   

## loading a single local file from a dialog

Loading a single file from a file selection dialog will remove all existing images and load the new image. The new image will become the background image in the stack. 

## loading multiple files from a dialog

Loading multiple files from a file selection dialog will remove all existing images and load the new images. The new images will be loaded in the order of the array of selected files from the dialog. The first image will become the background. All others will be loaded as overlays in the order of the received list.

**Comment by afni-dglen** [comment]
These all look pretty reasonable choices to me. Be careful of different storage orientations and obliquity among layers. The background layer should probably define the resolution and field of view, so the other layers will need to be interpolated onto that. I like a mostly fixed view of superior - up, inferior -down. For the background layer, oblique data could be viewed as stored with closest cardinal equivalents to determine which orthogonal plane gets shown as axial, sagittal or coronal. Different groups prefer left on left or left on the right of the image view, so should account for that.

Besides the drag and drop method, a file chooser method would be good.

**Comment by hanayik** [comment]
@afni-dglen , Good points. I have added two new behaviours in the list above to account for file selections via a dialog.

**Comment by neurolabusc** [comment]
@afni-dglen the expectation is that the background image is losslessly rotated to roughly match RAS alignment. All overlays are resliced to match the resolution of the background image. Since JavaScript is slow, this is done using a [WebGL shader](https://github.com/niivue/niivue/blob/0fb3b8c19bcdc9ef1f8a2128d6cbc4b38c098d1c/src/shader-srcs.js#L297). Therefore, interpolation is either `gl.NEAREST` (nearest neighbor) or `gl.LINEAR` (trilinear).  Note for anisotropic data the data stored on the GPU remains anisotropic, and we scale the images as they are drawn to screen.

**Comment by pieper** [comment]
Yes, resampling in the shader makes the most sense.  I don't think it's realistic to have the user know the sampling geometry of the volumes, since that information is very opaque in the nii.gz files; this should be done automatically.  Also there are times when you want to view in patient-referenced planes (axial, sagittal, coronal) or in scan-referenced planes.  Also sometimes you want to use the axes of the background and sometimes you want to use the planes of the foreground (e.g. when the foreground is sparsely sampled compared to the background).
