### ISSUE TITLE
One-Click Brain Masking To Show Only Plausible Results

### ISSUE THREAD

**Issue by rogiedodgie** [niivue/niivue#174]
Not sure we have thought about this yet, but it would be nice to retain a way to exclude spurious activity on overlay maps in normal space (MNI + SPM) (similar to 'Mask with Background' in MRIcroGL12) and make this option easy to access. For example, right now, I am overlaying an activation map generated from CBF data, which I had to smooth considerably, on the MNI template. Excluding these odd activations near the top of the brain (where we only have data for a few participants due to lack of whole brain coverage on these scans) is great for visualization. Additionally, could we include Ventricle maps in standard space to mask out spurious activations there? The attached illustrates ventricle activation (not a perfect example as the activation only partially overlaps with ventricles, but good to get an idea I hope).

![ventricleActivation](https://user-images.githubusercontent.com/26310853/142912310-1e42e3ea-99b2-4dc6-aad7-b4e9459905e9.png)

**Comment by hanayik** [comment]
@rogiedodgie , can you upload an example screenshot? Just for reference.

**Comment by rogiedodgie** [comment]
Yes, I am not sure if this should be a separate issue, but I would also think it would be extremely useful to make it VERY easy to only show results for only SPECIFIC atlas regions. For example, researchers will often have _apriori ROIs_ which they pick out at the beginning of a study (in order to reduce the multiple comparison problem). Right now, it is not at all easy/intuitive to mask your results with a few ROIs. I mean, sure, I can use some other programs to construct a custom mask, but that is beyond what most people will be able to do easily. I would think something like a dropdown where you choose the ATLAS, then a checkbox where you choose the ROIs to inclusively/exclusively mask with, would be the right option for that situation. I think this is probably a high-likelihood/use scenario for modern day neuroimagers.
