### ISSUE TITLE
Ability to Independently Change Color of Mesh and Face (of a cut)

### ISSUE THREAD

**Issue by rogiedodgie** [niivue/niivue#177]
Just looking at this video. It is a striking visual contrast to have the faces of a cut be presented in a different color than the brain mesh. This would be great to have! See: https://www.youtube.com/watch?v=ShvEzf8eXUk

**Comment by neurolabusc** [comment]
closing. This feature is implemented, see the [`shade volume not background` option of the clip plane demo](https://niivue.github.io/niivue/features/clipplanes.html).
