### ISSUE TITLE
niimath wasm command generation

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#194]

**Comment by neurolabusc** [comment]
Here is [my proposal](https://github.com/neurolabusc/niimath_wasm/tree/main/minimal). The niimath commands are passed as a string, matching the command line calls. Therefore, the niimath command line call `niimath T1 -dehaze -5 -dog 2 3.2 dT1 ` would be simply `-dehaze 5 -dog 2 3.2`. This means that there is always a one-to-one correspondence between niimath and wasm functions, and we do not need to revisit the header.
