### ISSUE TITLE
Show "Loading.." while the volume is being loaded?

### ISSUE THREAD

**Issue by soichih** [niivue/niivue#196]
Thanks to #167 I was able to incorporate niivue (experimentally) to ezBIDS.

![image](https://user-images.githubusercontent.com/923896/144331390-283448db-13cb-4d1a-bc67-ba8e0cc517e9.png)

I did notice, however, that while the image is loaded, it just shows a blank screen. I think it would be nice if it shows the "Loading.. 34%" type progress bar.

**Comment by soichih** [comment]
Correction.. it's not completely a "blank" screen while the data is loaded. I see the red lines with blank image.

**Comment by hanayik** [comment]
The canvas should show "Loading...", That feature was introduced a few versions ago. However, I think I may have introduced a bug in the recent bundling changes related to loading the initial font assets, before an image is loaded.

I'll look into this today.

The "loading %" idea is a good one though, and does convey more info to the user. It would be good to try and enable that in the future.
________________________________
