### ISSUE TITLE
Setting of image orientation radiological/neurological

### ISSUE THREAD

**Issue by fk128** [niivue/niivue#201]
Nice work on the viewer. It's been nice having a viewer that can easily work with vuejs. 

I was wondering whether there might be a way to change the displayed image orientation? It seems it might be reorienting the images to RAS only according to https://github.com/niivue/niivue/blob/17141333c7d6a456bdbe2390f198f8d07d8d50a2/src/nvimage.js#L114

When I do load in an RAS image https://github.com/rordenlab/NIfTIspace/blob/main/NIfTI/RAS.nii.gz

I get this in the viewer

![image](https://user-images.githubusercontent.com/6595674/145441169-e9011087-2923-4c6b-ac5f-a79f1e992206.png)

But it would be nice to be able to change to a radiological display orientation as in 3dSlicer

![image](https://user-images.githubusercontent.com/6595674/145443954-78899a19-c5bc-4e35-a7a9-21fa86fbd95b.png)

**Comment by neurolabusc** [comment]
You can choose either [neurological or radiological convention](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage#Neurological_versus_radiological_convention):


[this.isRadiologicalConvention = false;](https://github.com/niivue/niivue/blob/4d530ea74f0f1fd9c63ff2dab5a025311cf3a9b1/src/niivue.js#L120)

**Comment by hanayik** [comment]
Hi,

Glad you like NiiVue. It's not exposed in a nice way yet, but you could set isRadiologicalConvention= true on the niivue instance.

So:

nv = new Niivue()
nv.isRadiologicalConvention=true

If you want, you could submit a PR to add this in via a setter method. Happy to add you to the contribution list on the readme. An issue would also be good, and I could add this in if you don't want to submit a PR!

Cheers,

Taylor
________________________________
From: Fahdi Kanavati ***@***.***>
Sent: Thursday, December 9, 2021 5:44:13 PM
To: niivue/niivue ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [niivue/niivue] Setting of image orientation radiological/neurological (Issue #201)


Nice work on the viewer. It's been nice having a viewer that can easily work with vuejs.

I was wondering whether there might be a way to change the displayed image orientation? It seems it might be reorienting the images to RAS only according to https://github.com/niivue/niivue/blob/17141333c7d6a456bdbe2390f198f8d07d8d50a2/src/nvimage.js#L114

When I do load in an RAS image https://github.com/rordenlab/NIfTIspace/blob/main/NIfTI/RAS.nii.gz

I get this in the viewer

[image]<https://user-images.githubusercontent.com/6595674/145441169-e9011087-2923-4c6b-ac5f-a79f1e992206.png>

But it would be nice to be able to change to a radiological display orientation as in 3dSlicer

[image]<https://user-images.githubusercontent.com/6595674/145443954-78899a19-c5bc-4e35-a7a9-21fa86fbd95b.png>

**Comment by fk128** [comment]
Great! Thanks for the quick replies Chris and Taylor. My colleague @dazzag24 will have a go at making a PR for this.

**Comment by dazzag24** [comment]
Hi,
PR submitted. It allows flipping of the images in the basic.multiplanar demo and in the index.html demo used by the hot reload dev tool.

**Comment by neurolabusc** [comment]
@dazzag24 Thanks. As an aside, it seems like NiiVue might be a nice component for your [ct_annotation](https://github.com/dazzag24/ct_annotation) project. Providing users with methods to evaluate images is crucial. I wonder if there is some opportunity for collaboration with [niviz](https://github.com/TIGRLab/niviz), which is a very different use case, but may share a lot of similarity in implementation.

**Comment by hanayik** [comment]
Thanks! I have merged it in, and it’s now part of the latest version on npm. You may need to update you niivue npm package to the latest version.

I also added in a test for this, and the option to pass isRadiologicalConvention on the options object passed to the Niivue constructor.

So you can now do: nv = new Niivue({isRadiologicalConvention:true})

From: dazzag24 ***@***.***>
Date: Friday, 10 December 2021 at 10:48 am
To: niivue/niivue ***@***.***>
Cc: Taylor Hanayik ***@***.***>, Comment ***@***.***>
Subject: Re: [niivue/niivue] Setting of image orientation radiological/neurological (Issue #201)

Hi,
PR submitted. It allows flipping of the images in the basic.multiplanar demo and in the index.html demo used by the hot reload dev tool.
