### ISSUE TITLE
How to delete volumes?

### ISSUE THREAD

**Issue by vincenzoml** [niivue/niivue#228]
I tried to remove a volume as follows:

    let idx = nv.volumes.findIndex(img => img.url == url)
      if (idx) {
        console.log("REMOVE VOLUME",idx)
        nv.volumes.splice(idx, 1)
        nv.updateGLVolume()
      }

(the `url` property is added by me on volume creation). However the display does not get updated. I log also `nv.volumes` and it changes, but the corresponding image is still displayed.

**Comment by hanayik** [comment]
@vincenzoml , I had just added a new PR to enable removing volumes. It should be published to npm as a new NiiVue version by the end of the day. 

you will be able to remove a volume like this:

nv.removeVolume(someVolume). 

By the way, you can use nv.getVolumeIndexByID(someVolume.id)// each volume has an id property in niivue that we add, and all volumes are instances of NVImage after they are loaded.

**Comment by vincenzoml** [comment]
Thanks a lot!

**Comment by vincenzoml** [comment]
By now I received the update to `^0.17.0`, but I don't have `removeVolume` ("is not a function").

**Comment by hanayik** [comment]
Hi @vincenzoml, the feature is in version `0.18.0`. Just published
