### ISSUE TITLE
moveVolumeToTop and moveVolumeToBottom duplicate volumes

### ISSUE THREAD

**Issue by vincenzoml** [niivue/niivue#230]
Hi, running the following produces "0" and then "1" in the console, whereas **uncommenting** nv.moveVolumeToTop produces "0" and then "2" and in fact the volumes appear duplicated. Moving to bottom seems to triplicate (!!). Probably a bug?

          console.log(nv.volumes.length)
          var img = await NVImage.loadFromUrl(url)
          nv.addVolume(img)
          // nv.moveVolumeToTop(img)
          console.log(nv.volumes.length)

**Comment by hanayik** [comment]
Hi @vincenzoml this is likely a bug due to my recent remove volume changes. I will look into it.

**Comment by hanayik** [comment]
This is resolved in version `0.18.1` available on npm
