### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/niivue#252]
Warnings and bugs:
For the vue example, I get a warning `Do not use empty rulesetscss(emptyRules)` (https://stackoverflow.com/a/32464333)
Also, for the react example, the first import statement should be `import { useRef, useEffect } from 'react'`

Enhancement:
It'd be nice to have a codesandbox or codepen url for the vue and react examples so people can quickly test niivue before using it. It's still useful to have the markdown code; however, it'd be neat to be able to interact with niivue in an online code editor.

**Comment by hanayik** [comment]
@AnthonyAndroulakis, yep the react example should be updated. Good catch. 

For the Vue example, I suspect removing the `#app` will fix the warning. 

Would you like to submit a PR with the fixes? Make sure you have the most up to date main branch first. You will be immortalised in the list of contributors for doing so ;)

the Codepen/sandbox idea sounds promising. Would you like to try and set up a simple example for one of those platforms, and then add the link to the NiiVue readme?

**Comment by AnthonyAndroulakis** [comment]
Sure, I made a pr. I'm still testing niivue out in sandbox but haven't gotten it to work yet.

**Comment by hanayik** [comment]
Thanks! it's merged in.
