### ISSUE TITLE
document/implement click, touch, and key canvas interactions

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#268]
This issue serves as a discussion forum and documents the niivue canvas click and touch interactions

# interactions

## switching between 2D and 3D on Desktop/laptop

- [x] press the "v" key on the keyboard to cycle through views (2D sagittal, 2D coronal, 2D axial, 2D multiplanar, 3D render)

### change crosshair location

- [x] single left mouse click
- [x] single finger touch-up event (touch screens)
- [x] left click and drag continuously 
- [x] single finger touch and drag (touch screens)

### change slices

- [x] scroll wheel up or down (mouse)
- [x] scroll up or down (touch pad)
- [x] two finger pinch in/out (touch screens)

### change display intensity 

- [x] ~single right click sets min/max display to clicked voxel~ (feature removed in PR #269)
- [x] right click and drag draws intensity selection rectangle and a release sets the min/max display to min and max within the rect
- [x] double touch-down and drag draws intensity selection rectangle and a touch-up sets the min/max display to min and max within the rect (touch screens)
- [x] double left click resets display intensity to cal_min/cal_max
- [x] long touch resets display intensity to cal_min/cal_max (touch screens)

### zoom image

- [x] scroll wheel up or down (mouse)
- [x] scroll up or down touch pad
- [x] two finger pinch in/out (touch screens)

### change crosshair location

- [x] double left mouse click
- [x] double single finger touch-up. A "double tap" (touch screens)

### rotate 3D image

- [x] left click and drag
- [x] single finger touch and drag (touch screens)

### manipulate 3D clip planes

- [x] press "c" key to activate clip planes (desktop/laptop)
- [x] ~long touch in same location (3 sec) on touch screens to activate clip planes?~
- [x] ~if clip planes active on touch screens, double tap then drag to rotate clip planes?~
- [x] right click and drag rotates clip plane (azimuth and elevation)
- [x] scroll wheel or touch-pad on desktop/laptop changes clip depth

**Comment by neurolabusc** [comment]
Can I suggest a different interaction for [triple clicks](https://stackoverflow.com/questions/6480060/how-do-i-listen-for-triple-clicks-in-javascript). I think this should work like the `v` key in cycling through views. However, I think that it should toggle between two different render views: one with and one without a clip plane, so the order would be `2D Axial`, `2D Coronal`, `2D Sagittal`, `2D MPR`, `3D Render without clipping`, `3D Render with clipping`. I would suggest this toggle only changes the clip depth (e.g. between center `0.0` and outside volume (`2.0`) ), and preserves the angle/azimuth of the clip plane.

**Comment by neurolabusc** [comment]
I am not convinced of the behavior `single right click sets min/max display to clicked voxel`. We can adjust both the brightness (window center) and contrast (window width). So the single click sets the window center but preserves the window width? E.G. Consider a minimum-maximum intensity of 0 and 255. The WW is 255 and the WC is 127.5. So if a user right clicks on a pixel with an intensity of 27.5, the new setting is -100..155? I am not saying this is wrong, its just hard to know what the best approach for contrast/brightness given a single intensity value.

**Comment by hanayik** [comment]
@neurolabusc , the single right click action has actually been removed in PR #269 anyways. So I think it's fine to leave it out.

**Comment by hanayik** [comment]
> Can I suggest a different interaction for [triple clicks](https://stackoverflow.com/questions/6480060/how-do-i-listen-for-triple-clicks-in-javascript). I think this should work like the `v` key in cycling through views. However, I think that it should toggle between two different render views: one with and one without a clip plane, so the order would be `2D Axial`, `2D Coronal`, `2D Sagittal`, `2D MPR`, `3D Render without clipping`, `3D Render with clipping`. I would suggest this toggle only changes the clip depth (e.g. between center `0.0` and outside volume (`2.0`) ), and preserves the angle/azimuth of the clip plane.

This is a neat idea. This could work nicely for touch screens. Although, we'd need to implement our our touch event timer to detect triple touches. touch events don't have event.detail like clicks do from what I've read.
