### ISSUE TITLE
Dense connectome support on surface

### ISSUE THREAD

**Issue by SeanFitzgibbon** [niivue/niivue#301]
It would be useful to have support for the dense connectome on the surface where the user could click on a vertex and the connectivity of the selected vertex to all other vertices would be displayed on the surface (i.e. a single row/col in the dense connectivity matrix).  

Similar to what can be done with connectome workbench, for example, here is the connectivity to the vertex indicated but the dot/sphere annotation:

![image](https://user-images.githubusercontent.com/30693091/161778432-cd9c6bc1-54f4-40b2-8098-8022ec978e33.png)

**Comment by neurolabusc** [comment]
Do you want to provide an example dataset? This might be a nice feature for the [NiiVue](https://niivue.github.io/niivue/) team.

**Comment by SeanFitzgibbon** [comment]
I can't provide the data for this image because it was calculated dynamically in workbench. 

The file format in question is CIFTI `*.dconn.nii` for dense connectome, and `*.pconn.nii` for parcellated connectome.  Both really just contain a connectivity matrix in a nifti2 (vertex-by-vertex, or parcel-by-parcel).  It will also require a surface, we usually use `*.surf.gii`, but any surface with vertex correspondence would suffice.  

I will try to locate some data and share it directly with @hanayik

**Comment by neurolabusc** [comment]
@SeanFitzgibbon NiiVue can now read some CIfTI data. A concrete example where we can compare our results with workbench seems like the best way forward. Without a sample dataset, I vote we should close this issue as too abstract.
