### ISSUE TITLE
colormap for atlas lookup table

### ISSUE THREAD

**Issue by ChinHui-Chen** [niivue/niivue#322]
Would it be possible to have the lookup table colormap function for Atlas files (E.g. aparc.DKTatlas+aseg.mgz from freesurfer recon-all)

<img width="297" alt="image" src="https://user-images.githubusercontent.com/625355/170741457-60d36e68-d475-49cf-ba92-418302767a51.png">

I found that you can find the lookup table file in /usr/local/freesurfer/FreeSurferColorLUT.txt. 

<img width="286" alt="image" src="https://user-images.githubusercontent.com/625355/170743321-71001d6e-1303-41df-bd42-2a67aec724b6.png">

And based on the following document, could we map each voxel value to the corresponding RGB value? I'm going to implement the function. Could anyone share some suggestions or point out the code segments related to this implementation?

<img width="691" alt="image" src="https://user-images.githubusercontent.com/625355/170742192-e8f218b0-c31e-4216-ae98-6a603c433200.png">

**Comment by hanayik** [comment]
@ChinHui-Chen , I have added a simplified Freesurfer colormap (a direct translation from ASegStatsLUT.txt). To support the larger set of regions will require some changes to the colormap code, so this is the easy solution for now. 

you can use the colormap by specifying the `colorMap: 'freesurfer'` option when loading an image. If all tests pass on #332 then I will update the niivue package on NPM and the latest version will have this available.
