### ISSUE TITLE
feature: support multiple undo steps in drawing

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#328]

**Comment by neurolabusc** [comment]
How many undo steps do we want to store? The drawings are 3D volumes, so the RAM demands for each undo map is pretty extensive.

**Comment by neurolabusc** [comment]
You could save the differences. Alternatively, drawings often compress well with one-pass run-length encoding like [PackBits](https://en.wikipedia.org/wiki/PackBits). Whatever method would be used to compress the data would need to be done very quickly, as one wants to save the current state when the user starts drawing a new line segment and we want to keep the drawing interactive.

**Comment by neurolabusc** [comment]
@hanayik the latest commit to the `drawing` branch uses [Packbits](https://en.wikipedia.org/wiki/PackBits) to compress undo maps. This supports 8-bit drawings (each voxel color 0..255). In practice this simple one-pass compression offers a factor x40 reduction in RAM usage. 

The undo buffer is cyclical. The number of undo steps is set by `maxDrawUndoBitmaps` (currently 8). My analogy for this is the number of chambers in a revolver. Once you exceed this number of undo steps, you go back to the drawing prior to the initial undo selection. This allows the user to `undo` an accidental undo.
