### ISSUE TITLE
drawings do not appear in 3D render

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#339]
example images ( blue drawing does not appear in 3D)

@neurolabusc, just starting these issues as a list of "todo" items for us all. Issues are nice in this way because they ping everyone in the repo via an email notification. 

![Screenshot 2022-06-07 at 4 21 54 pm](https://user-images.githubusercontent.com/5217720/172418977-15c3b284-ee81-424f-8f1c-cb71f9a63825.png)
![Screenshot 2022-06-07 at 4 22 07 pm](https://user-images.githubusercontent.com/5217720/172418988-86795635-2ae6-4cab-8400-d58a75e57e83.png)

**Comment by neurolabusc** [comment]
@hanayik this reflects a tradeoff: handling an additional texture will have a dramatic performance impact on the 3D render. My thought was that the drawing is designed for fluid editing on the 2D slices. One can always save the drawing to disk and load it as a basic overlay.

**Comment by hanayik** [comment]
Hi @neurolabusc , I was considering adding a new function `drawingToNVImage` to Niivue that can conveniently add the finished drawing to the `volumes` array. What do you think?

**Comment by neurolabusc** [comment]
Implemented in the render shader. I have not implemented the drawing in the picking shader or the MIP shader. My sense is that one wants to pick a volume not the drawing. This does complicate the shader substantially, but I guess modern GPUs are fast. Do check for unintended consequences to clip planes and traditional overlays
![gpu](https://user-images.githubusercontent.com/8930807/179052786-8227d4f8-dd89-42a1-8bd0-fc8636150932.png)
.
