### ISSUE TITLE
move slice orientation labels to corner

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#340]
When the planar slice orientation labels are centered on the panel edges, they often cover brain data.  How about moving that information to the upper left corner, as a pair of letters, such as ``LS``, ``RA``, etc.?

This could be done by commenting out src/niivue.js lines 4385-4416:
```
  if (isMirrorLR)
    this.drawTextRight(
 ...
      "S"
    );
```
with the following:
```
  if (isMirrorLR) {
    var txtAxi = "RA";
    var txtCor = "RS";
  } else {
    var txtAxi = "LA";
    var txtCor = "LS";
  }
  var txtSag = "AS";

  if (axCorSag === this.sliceTypeSagittal)
    this.drawTextBelow(
      [
        leftTopWidthHeight[0] + 1, 
        leftTopWidthHeight[1] + 1
      ],
      txtSag
    );
  if (axCorSag === this.sliceTypeAxial)
    this.drawTextBelow(
      [
        leftTopWidthHeight[0] + 1, 
        leftTopWidthHeight[1] + 1
      ],
      txtAxi
    );
  if (axCorSag === this.sliceTypeCoronal)
    this.drawTextBelow(
      [
        leftTopWidthHeight[0] + 1,
        leftTopWidthHeight[1] + 1
      ],
      txtCor
    );
```

--pt

**Comment by hanayik** [comment]
@mrneont, this is a neat suggestion. 

making some notes for future implementation:

- add a new option to the niivue constructor so that changing this behaviour is optional. 
- I suggest something like: `labelType: 0 | 1 | 2` where 0 is off, 1 is the current implementation (default), and 2 is your new suggestion.

**Comment by mrneont** [comment]
Hi, @hanayik -

In my local version, at your suggestion, I have added the following variable to the `this.defaults { ...}` to control/toggle the location of the slice labels:
```
    sliceLabelLoc: 1, // 0=no_display; 1=edge_centered; 2=top_left_corner
```

I then merged/extended the labelling code (as well as fixing the sagittal labelling, as you noted in our meeting, to be dependent on that value:
```
  if ( this.opts.sliceLabelLoc === 1 ) {
    if (isMirrorLR)
      this.drawTextRight(
        [
          leftTopWidthHeight[0] + leftTopWidthHeight[2] + 1,
          leftTopWidthHeight[1] + 0.5 * leftTopWidthHeight[3],
        ],
        "R"
      );
    else if (axCorSag < this.sliceTypeSagittal)
      this.drawTextRight(
        [
          leftTopWidthHeight[0] + 1,
          leftTopWidthHeight[1] + 0.5 * leftTopWidthHeight[3],
        ],
        "L"
      );
    if (axCorSag === this.sliceTypeAxial)
      this.drawTextBelow(
        [
          leftTopWidthHeight[0] + 0.5 * leftTopWidthHeight[2],
          leftTopWidthHeight[1] + 1,
        ],
        "A"
      );
    if (axCorSag > this.sliceTypeAxial)
      this.drawTextBelow(
        [
          leftTopWidthHeight[0] + 0.5 * leftTopWidthHeight[2],
          leftTopWidthHeight[1] + 1,
        ],
        "S"
      );
  } 
  else if ( this.opts.sliceLabelLoc === 2 ) {
    if (isMirrorLR) {
      var txtAxi = "RA";
      var txtCor = "RS";
    } else {
      var txtAxi = "LA";
      var txtCor = "LS";
    }
    var txtSag = "PS";

    if (axCorSag === this.sliceTypeSagittal)
      this.drawTextBelow(
        [
          leftTopWidthHeight[0] + 1, 
          leftTopWidthHeight[1] + 1
        ],
        txtSag
      );
    if (axCorSag === this.sliceTypeAxial)
      this.drawTextBelow(
        [
          leftTopWidthHeight[0] + 1, 
          leftTopWidthHeight[1] + 1
        ],
        txtAxi
      );
    if (axCorSag === this.sliceTypeCoronal)
      this.drawTextBelow(
        [
          leftTopWidthHeight[0] + 1,
          leftTopWidthHeight[1] + 1
        ],
        txtCor
      );
  }
  if (axCorSag !== this.sliceTypeAxial) return;
```
I am not certain about where that last if-condition (`  if (axCorSag !== this.sliceTypeAxial) return;`) should go, actually, but the above code seems to provide the desired behavior.

--pt

**Comment by hanayik** [comment]
Hi Paul, can you created a new NiiVue branch (or fork) and submit your enhancements as a new PR? It should be a pretty straightforward one. I can also add this in a few days if you don't get to it.
________________________________

**Comment by neurolabusc** [comment]
@hanayik and @mrneont it might be worth deferring this until we have closed issues [56](https://github.com/niivue/niivue/issues/56), [57](https://github.com/niivue/niivue/issues/57), [337](https://github.com/niivue/niivue/issues/337), and [338](https://github.com/niivue/niivue/issues/337). The slice drawing will change and be more modular in the future.

**Comment by mrneont** [comment]
Hi, @hanayik and @neurolabusc -

I am happy to make a fork+PR for this, as well as to do so once those Issues have cleared.  I will await the Bat-signal here.

--pt
