### ISSUE TITLE
some notes about OS dependency/installation

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#341]
Howdy-

In being able to compile+run niivue on my Ubuntu 20.04 OS, I have the following notes (which might be of use to others):

* The NPM dependency is known:
```sudo apt-get install npm```

I also had to add flask and nodejs.  I did this by adding them to a fairly minimal pre-existing environment for running AFNI.  Importantly, it seemed like getting `node --version` > v10 was a requirement for happy compiling of niivue.  I have different Python-version environments, and I note that adding nodejs and flask from conda-forge to a Python v3.9 environment like this:
```
conda install -n CONDA_ENV_PY39 -c conda-forge nodejs flask
```
... got me a modern `node` version v14.18.3;  but if I tried the above with a Python 3.7 environment, I only got node v6.13.1.  Rather than try forcing the version, I simply used my updated Python 3.9 env.

Also, when I compile, I remove the `puppeteer` dependency, because it wasn't necessary for me to compile the code (as discussed with @hanayik).  I have a script to pull the latest "niivue" code repo and copy it to a clean "niivue_build" directory for me to develop in (as well as backup my previous build directory), in which I simply used grep to excise the puppeteer dependence from package.json.  My full script for this, in case it is useful to anyone, is:

```
#!/bin/tcsh

# local file/repo names (all local dirs)
set repo    = niivue
set new_bld = ${repo}_build
set remote  = main

# temp/labeling stuff
set here    = $PWD
set thedate = `date +%Y_%m_%d_%H_%m_%s`
set dir_tmp = BUILDNEW

\mkdir -p ${dir_tmp}

# make sure git repo is uptodate
cd  ${here}/${repo}

git fetch
git checkout ${remote}
git pull origin ${remote}

# copy over src 
cd ${here}

echo "++ Sync git repo '${repo}' (${remote}) to build "
rsync -av --exclude=".*" ${repo}/ ${dir_tmp}

cd ${dir_tmp}

echo "++ remove one line/dependency about puppeteer"
\cp package.json package.json_BACKUP
cat package.json | grep -v '"puppeteer"' > __tmp.txt
\mv __tmp.txt package.json

echo "++ Do build"
# from:
### https://github.com/niivue/niivue#install-niivue-into-your-project-via-npm
# ... this gets dependencies (should only be slow first time through)
npm install |& tee ${here}/o.build_src_${thedate}.txt

# do actual build
npm run build

if ($status) then
    echo "** ERROR IN BUILD"
    echo "   e ${here}/o.build_src_${thedate}.txt"
    exit 1
endif

echo "++ Done with build--- continuing"

# push into new spot
cd ${here}

echo "++ Put in final spot"
if ( -e ${new_bld} ) then
    mv ${new_bld} ${new_bld}_${thedate}
endif

mv ${dir_tmp} ${new_bld}
touch ${new_bld}

echo "++ DONE"
exit 0
```
... after which I go into the niivue_build and work on things there.

--pt

**Comment by hanayik** [comment]
@mrneont,

(as of this writing) I would definitely recommend nodejs 14 or greater. All NiiVue tests build and run with nodejs 14 since it is the oldest LTS version still supported. It's probably a good idea to use an LTS version, (16 is the current LTS version but 14 is still in LTS maintenance mode). https://nodejs.org/en/about/releases/

You can install NiiVue into an existing project (e.g. some reporting interface project) without the development dependencies (no testing bloat) via:

```
npm install --only=prod @niivue/niivue
```

I added that to the READme recently (but prob wasn't there when you tried this). 

Your Conda install seems like a good idea, and can probably produce a more re-producible environment when ever you switch machines. 

I have not replicated the python3.7 issue you mentioned, but it's likely we are trying different things (and I'm testing via conda on macOS). Here's what the "package plan" is for me when I install nodejs, python3.7 and flask into a new env:

`conda create -n py37node -c conda-forge python=3.7 nodejs flask`

```
## Package Plan ##

  environment location: <redacted>

  added / updated specs:
    - flask
    - nodejs
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.5.18.1|       h033912b_0         145 KB  conda-forge
    click-8.1.3                |   py37hf985489_0         145 KB  conda-forge
    flask-2.1.2                |     pyhd8ed1ab_1          70 KB  conda-forge
    icu-70.1                   |       h96cf925_0        13.1 MB  conda-forge
    importlib-metadata-4.11.4  |   py37hf985489_0          33 KB  conda-forge
    itsdangerous-2.1.2         |     pyhd8ed1ab_0          16 KB  conda-forge
    jinja2-3.1.2               |     pyhd8ed1ab_1          99 KB  conda-forge
    libcxx-14.0.4              |       hc203e6f_0         1.3 MB  conda-forge
    libffi-3.4.2               |       h0d85af4_5          50 KB  conda-forge
    libuv-1.43.0               |       h0d85af4_0         429 KB  conda-forge
    libzlib-1.2.12             |       h6c3fc93_0          62 KB  conda-forge
    markupsafe-2.1.1           |   py37h69ee0a8_1          21 KB  conda-forge
    ncurses-6.3                |       h96cf925_1         915 KB  conda-forge
    nodejs-17.9.0              |       h40ae9cc_0        11.4 MB  conda-forge
    openssl-3.0.3              |       hfe4f2af_0         2.5 MB  conda-forge
    pip-22.1.2                 |     pyhd8ed1ab_0         1.5 MB  conda-forge
    python-3.7.12              |hf3644f1_100_cpython        24.3 MB  conda-forge
    python_abi-3.7             |          2_cp37m           4 KB  conda-forge
    readline-8.1               |       h05e3726_0         266 KB  conda-forge
    setuptools-62.3.3          |   py37hf985489_0         1.4 MB  conda-forge
    sqlite-3.38.5              |       hd9f0692_0         1.7 MB  conda-forge
    tk-8.6.12                  |       h5dbffcc_0         3.4 MB  conda-forge
    typing_extensions-4.2.0    |     pyha770c72_1          27 KB  conda-forge
    werkzeug-2.1.2             |     pyhd8ed1ab_1         237 KB  conda-forge
    wheel-0.37.1               |     pyhd8ed1ab_0          31 KB  conda-forge
    xz-5.2.5                   |       haf1e3a3_1         228 KB  conda-forge
    zipp-3.8.0                 |     pyhd8ed1ab_0          12 KB  conda-forge
    zlib-1.2.12                |       h6c3fc93_0          91 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        63.5 MB
```

Thanks for pointing out that there are still some teething issues on some machines. I think it would be great to update the NiiVue install/development instructions to address these cases. I will do that soon!

**Comment by neurolabusc** [comment]
@hanayik great that the tests always check version 14 compatibility. The regression testing you have developed is a great asset.

I note that [fflate](https://github.com/101arrowz/fflate/blob/80c12de8f495b11fd64aae22932eee6b82c9a5b5/package.json#L76) suggests `node` version "^14.11.2"

**Comment by hanayik** [comment]
@neurolabusc, thanks! I think it would be a good idea to also add in a new test for nodejs 16 (current LTS) and 18. 18 will be the active LTS in October. I can do this (it's as simple as adding 16 and 18 to [this array](https://github.com/niivue/niivue/blob/50ccc1aa38ef01eff381c224e9899b4d4f81b977/.github/workflows/test-macOS.yml#L19)

**Comment by hanayik** [comment]
> 

BTW, I'm not sure the node > 14.11.2 matters much for NiiVue in the browser (since there's no node in the browser). We only use node to build the NiiVue package. Regardless, I have added node 16 and 18 to our tests so that we verify that niivue can be built using each version (and tested).
