### ISSUE TITLE
3D rendering failed

### ISSUE THREAD

**Issue by BastienCagna** [niivue/niivue#344]
Hi,
The 3D rendering of https://niivue.github.io/niivue/features/basic.3d.html failed on my computer with firefox and chrome:
![image](https://user-images.githubusercontent.com/22853356/174103242-df4e68fb-2fb2-4dce-ae78-6db1ad202671.png)

Here are the webglreport for WebGL 2 with firefox:
![image](https://user-images.githubusercontent.com/22853356/174102464-71fe00d3-86c2-4e0d-a7eb-2cb127b34958.png)

With chrome:
![image](https://user-images.githubusercontent.com/22853356/174102736-23a2c97b-e77c-4e5f-82bf-fd21968fe964.png)

Finally, my computer infos
![image](https://user-images.githubusercontent.com/22853356/174102993-dc283d3b-372f-4a4f-aa19-2e743ed5ffea.png)

**Comment by alexisthual** [comment]
I have the exact same problem!
Here is my GPU info:
ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) , OpenGL 4.5)

**Comment by hanayik** [comment]
Hi @alexisthual ,

can you try running this in a terminal session:

```
MESA_GL_VERSION_OVERRIDE=3.3 firefox # or brave, chrome, etc.
```

then navigate to the niivue 3D demo. 

https://niivue.github.io/niivue/features/basic.3d.html

**Comment by alexisthual** [comment]
> can you try running this in a terminal session: 
> ```
> MESA_GL_VERSION_OVERRIDE=3.3 firefox # or brave, chrome, etc.
> ```

I just did and unfortunately got the same rendering artefact as before!

**Comment by alexisthual** [comment]
Actually, I tried different browsers: https://niivue.github.io/niivue/features/basic.3d.html displays correctly for me in firefox and chrome, but not in brave.

**Comment by neurolabusc** [comment]
@cdrake can you replicate this on your system? I think we can fix this if we have access to a system that shows this bug. Reminds me of the [MRIcroGL kludge for Mesa](https://github.com/rordenlab/MRIcroGL/blob/4c21503f4fb5cd10ed59382ad8085084ea6a54f2/glvolume2.pas#L321) which adds a GLSL conditional that is never executed but make Mesa behave nicely.

**Comment by hanayik** [comment]
@BastienCagna and @alexisthual, could you try the latest 3D demo page and let me know if the 3D rendering still fails? 

https://niivue.github.io/niivue/features/basic.3d.html

**Comment by alexisthual** [comment]
> @BastienCagna and @alexisthual, could you try the latest 3D demo page and let me know if the 3D rendering still fails?
> 
> https://niivue.github.io/niivue/features/basic.3d.html

I just tried, and it still fails in brave and succeeds in firefox (I tried a hard refresh in both cases).

**Comment by hanayik** [comment]
@alexisthual , and @BastienCagna , can you try once more please? @pauldmccarthy has submitted a fix since he was able to replicate the issue on his ubuntu machine. 

https://niivue.github.io/niivue/features/basic.3d.html
