### ISSUE TITLE
feat: support surface vertex picking

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#345]

**Comment by neurolabusc** [comment]
This is a bit harder in WebGL than OpenGL, as the depth buffer is write only. Currently, our depth picking shader only works for voxel-based volumes. We encode the X,Y,Z coordinates as the Red, Green and Blue components of a color. This limits us to 8-bit precision per dimension.

For meshes, we should use the 'picking buffer` strategy of [papaya](https://github.com/rii-mango/Papaya/blob/782a19341af77a510d674c777b6da46afb8c65f1/src/js/viewer/screensurface.js#L89), where the 32-bit depth is packed into a 32-bit red, green, blue, alpa value and the inverse of the model view projection matrix provides the world space coordinates.

@hanayik this might be a good WebGl project for you. You can port the WebGL 1 Papaya code to WebGL 2 for NiiVue.

**Comment by neurolabusc** [comment]
I added a WebGL 2 depth shader that can be invoked with 
```
 nv1.setMeshShader("Depth")
```
The rest of the work is JavaScript, cloning the [Papaya](https://github.com/rii-mango/Papaya/blob/782a19341af77a510d674c777b6da46afb8c65f1/src/js/viewer/screensurface.js#L1364) code to unpack the float32 value and invert the model view projection matrix to determine the XYZ coordinates (in millimeters) where the mouse clicked.

**Comment by hanayik** [comment]
Amazing! Thanks @neurolabusc . Maybe we can get to this at the end of the Hackathon, but if not, I am happy to work on this.

**Comment by neurolabusc** [comment]
@hanayik I looked at this in more detail. Our current volume rendering depth shader uses 24-bit precision. The Papaya method requires 32-bit precision. An issue is that [for the Windows operation system the WebGL2 implementation has a bug](https://github.com/niivue/niivue/pull/263) that will not support this trick.  Should we adopt a method that will break Windows support until [ANGLE](https://en.wikipedia.org/wiki/ANGLE_(software)) is fixed?
