### ISSUE TITLE
support DTIFIT tensor images (displayed as ellipses at each voxel)

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#35]
@neurolabusc, figured creating this shader might be a worthwhile task. Shall we meet to discuss?

**Comment by reddydpusc** [comment]
Interesting.  So the ellipses would have an eccentricity proportional to the magnitude of the tensor and in the direction of the tensor, and would visually aggregate to form ribbon-like structures, correct?  How would you select the optimum scaling factor so the ellipses were neither discontinuous nor "spiky"?

**Comment by hanayik** [comment]
@reddydpusc, it would look somewhat like how FSLeyes displays this data. The somewhat simpler alternative would be to represent them as lines (also inspired by FSLeyes). 


![spheres](https://user-images.githubusercontent.com/5217720/128999541-0f7e4502-a6a1-4431-8c1e-f1e5cc74c628.png)

**Comment by neurolabusc** [comment]
NiiVue will now display DTI V1 images as RGB. I do think streamlines can provide more information, so we may want to reopen this issue when we want to employ a more sophisticated visualization.

![V1_DTI](https://user-images.githubusercontent.com/8930807/171669661-c450a5ec-52fa-457b-aec9-09b625aa4f3d.jpg)
