### ISSUE TITLE
callback to enable the "setDrawingEnabled(true)"

### ISSUE THREAD

**Issue by sablejr** [niivue/niivue#386]
Using "setDrawingEnabled(true)" seems to work when using the dev tools (in browser), but as soon as I add this line into my actual code, I keep getting the following error:

niivue.umd.js:1171 
        
       Uncaught TypeError: Cannot set properties of null (setting '31064347')
    at Niivue.drawPt (niivue.umd.js:1171:197272)
    at Niivue.mouseClick (niivue.umd.js:1171:231184)
    at Niivue.mouseLeftButtonHandler (niivue.umd.js:1171:164972)
    at Niivue.mouseDownListener (niivue.umd.js:1171:164701)

what could be causing this issue?

**Comment by hanayik** [comment]
Hi @sablejr, 

Try updating to the latest NiiVue version (`0.29.0`), and see if that works for you. If you still have errors, could you share some example code where things are failing?

**Comment by hanayik** [comment]
@sablejr, is this still an issue for you?
