### ISSUE TITLE
Is it possible to add APIs that load files from array buffer?

### ISSUE THREAD

**Issue by YuxiangChai** [niivue/niivue#390]
Hi, this project is excellent and when I am using it, I think I need some APIs that load files from ArrayBuffer. Right now I think only URL is supported for loading drawings. When the user wants to upload a local drawing file, there is no simple way to do it since the path is not accessible. Thank you

**Comment by hanayik** [comment]
Hi @YuxiangChai,

There is a `loadFromFile` method that is part of `NVImage`. 

You should be able to import it as use it like:

```
myImage = NVImage.loadFromFile(SomeFileObject) // files can be from dialogs or drag and drop
```

If you want users to add drawings to a scene, Niivue also readily supports drag and drop onto the canvas. You can drop an image onto the canvas and it will reset the scene, with only that image being shown, or you can drop an image on the canvas while holding SHIFT and the image will be added to the scene as an overlay.

**Comment by YuxiangChai** [comment]
Yes I saw that API but the thing is that if I directly drag and drop the drawing file to the canvas, the canvas won't display the drawings in the color I drew them (I guess it's because the drawing file is another .nii which is considered an ordinary 3D image). If I use `loadDrawing` to load a drawing file from a cloud URL, this drawing can be displayed in the correct color. Thank you
