### ISSUE TITLE
NVImage.loadFromUrl unable to handle more complex URLs

### ISSUE THREAD

**Issue by alexander-w-ross** [niivue/niivue#392]
## Description
I am using this library in a Next.js app and was testing out loading images from a local folder - `/public/images/<filename.nii.gz>` - which worked great. To replicate a production environment, the nifti URLs I would be passing into `NVImage.loadFromUrl` would be signed URLs. The signed URLs I would be getting are from Google Cloud and take the form:

```
https://storage.googleapis.com/example-bucket/nifti_image_filename.nii.gz?X-Goog-Algorithm=
GOOG4-RSA-SHA256&X-Goog-Credential=example%40example-project.iam.gserviceaccount
.com%2F20181026%2Fus-central1%2Fstorage%2Fgoog4_request&X-Goog-Date=20181026T18
1309Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=247a2aa45f16
9edf4d187d54e7cc46e4731b1e6273242c4f4c39a1d2507a0e58706e25e3a85a7dbb891d62afa849
6def8e260c1db863d9ace85ff0a184b894b117fe46d1225c82f2aa19efd52cf21d3e2022b3b868dc
c1aca2741951ed5bf3bb25a34f5e9316a2841e8ff4c530b22ceaa1c5ce09c7cbb5732631510c2058
0e61723f5594de3aea497f195456a2ff2bdd0d13bad47289d8611b6f9cfeef0c46c91a455b94e90a
66924f722292d21e24d31dcfb38ce0c0f353ffa5a9756fc2a9f2b40bc2113206a81e324fc4fd6823
a29163fa845c8ae7eca1fcf6e5bb48b3200983c56c5ca81fffb151cca7402beddfc4a76b13344703
2ea7abedc098d2eb14a7
```
After passing that signed URL into `loadVolumes()` I was getting the error:
```
TypeError: Cannot read properties of undefined (reading 'isMosaic')
```
Which I believe is being caused by [these couple lines here](https://github.com/niivue/niivue/blob/e7c774217c7c7e07d9ba97b25180301573e52b9c/src/nvimage.js#L2375).

```javascript
let urlParts = url.split("/"); // split url parts at slash
name = urlParts.slice(-1)[0]; // name will be last part of url (e.g. some/url/image.nii.gz --> image.nii.gz)
```
In my case, `name` will end up being `nifti_image_filename.nii.gz?X-Goog-Algorithm...` which will eventually get passed into `NVImage` [here](https://github.com/niivue/niivue/blob/e7c774217c7c7e07d9ba97b25180301573e52b9c/src/nvimage.js#L2390).  `NVImage` will try and determine the file extension by using this regular expression `var re = /(?:\.([^.]+))?$/` ([here](https://github.com/niivue/niivue/blob/e7c774217c7c7e07d9ba97b25180301573e52b9c/src/nvimage.js#L156)). This won't parse the signed URL as expected thus `NVImage` will try and read it as a DICOM.

## To Reproduce
Try and pass in any URL that doesn't end in `.nii.gz` or the file extension accepted by this package.

## Proposed Solution
My proposed solution is to use the [`URL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) constructor instead of splitting on `/`  like shown in the lines above (`urlParts`).

The new code would look like
```javascript

// current code
let urlParts = url.split("/"); // split url parts at slash
name = urlParts.slice(-1)[0]; // name will be last part of url (e.g. some/url/image.nii.gz --> image.nii.gz)

// suggested patch
// ----new---
let urlParts
try {
  urlParts = (new URL(url)).pathname.split("/");
} catch (e) {
  urlParts = url.split("/");
}
//--------
name = urlParts.slice(-1)[0]; // name will be last part of url (e.g. some/url/image.nii.gz --> image.nii.gz)
```
I believe `URL().pathname` is a more robust way of getting the filename that `NVImage` is expecting while maintaining current functionality. The `try/catch` block is there because `URL()` will raise an error if you're only passing in one parameter and that parameter isn't a complete URL (ex. `https://www.google.com/...`). Thus if you're still passing a URL that ends in the filename, it will still be handled as expected.

**Comment by hanayik** [comment]
@alexander-w-ross , thanks for the detailed description and suggested patch. I have incorporated your changes. A new version should be available on NPM within the hour
