### ISSUE TITLE
add method to get NIFTI file header info from image ID

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#403]
something like:

`getNiftiHeader(id)`

returns and object with key:value pairs of header info

**Comment by neurolabusc** [comment]
@hanayik  the volumes `hdr` stores the key:value pairs. You can also convert this to a formatted string. To see an example of the latter as a dialog message, try this [papaya demo](https://www.fmrib.ox.ac.uk/ukbiobank/group_means/index.html) and click on the layer (color gradient button on upper right) and choose `Show Header`.

```
console.log(nv1.volumes[0].hdr);
console.log(nv1.volumes[0].hdr.toFormattedString());
```
