### ISSUE TITLE
add new layout option for A+C+S+R regardless of screen aspect ratio

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#404]
This adds the ability to always see the A+C+S+R panels, but must disable time series, and colorbar rendering if we force the 3D view in the bottom left quadrant of the canvas

@neurolabusc, Can you handle implementing this? Similar to the view option already present in MRIcroGL

**Comment by neurolabusc** [comment]
Upcoming PR will include boolean option `multiplanarForceRender`
