### ISSUE TITLE
change brush size and opacity

### ISSUE THREAD

**Issue by haehn** [niivue/niivue#414]
Hi all,

is it possible to change the brush size and opacity during drawing mode?

Thanks so much!
Daniel

**Comment by neurolabusc** [comment]
The `drawing opacity` slider in the [drawing demo](https://niivue.github.io/niivue/features/draw.html) demonstrates the drawing opacity. At the moment the brush is always one pixel wide, but you have the option to create filled objects (choose `Filled Red` from the pull down menu in the [drawing demo])(https://niivue.github.io/niivue/features/draw.html). My sense is that users often select wide pens when trying to fill regions.

**Comment by haehn** [comment]
Thanks!
