### ISSUE TITLE
Fix min max functions for RGB/RGBA images 

### ISSUE THREAD

**Issue by cdrake** [niivue/niivue#42]
Images with RGB/RGBA value use 3 and 4 values respectively.  Min and max functions currently only use single values to determine min and max for voxels.

**Comment by neurolabusc** [comment]
@cdrake your new drag-drop feature makes it easy to test corner case images. I think you are aware of this, but there is still something wrong with the rendering of RGBA volumes. They look fine in the 2D slices, but the rendering look like we are not estimating alpha well. Perhaps make alpha about 25% of the luminance (Y), or if you prefer of the green channel. The example below is the visible human which is included with MRIcroGL. 

https://github.com/neurolabusc/MRIcro/blob/cc3e2b6b7fee69fa2eb55157b383c92d8b93ae2f/MRIcroX/nii_label.mm#L13

![visiblehuman](https://user-images.githubusercontent.com/8930807/135724194-c832f4fb-76db-4396-af3e-288cceb949f5.png)
