### ISSUE TITLE
Getting the value of a pixel of an image

### ISSUE THREAD

**Issue by fib** [niivue/niivue#433]
Hi, is there a way to get the value of a pixel by its coordinates?

I want to implement thresholding for annotations, and in order to compare nearby pixels against a threshold I need to probe their value in the image.

Thanks!

**Comment by neurolabusc** [comment]
This is timely, as we have been working on new features. Please try out the [drawing user interface demo](https://niivue.github.io/niivue/features/draw.ui.html). 
 1. Note that when you move the mouse cursor over a voxel, the voxel intensity is reported at the bottom of the screen. 
 2. You can try the Draw/Otsu feature that will that shows JavaScript for [multi-otsu segmentation](https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_multiotsu.html)

**Comment by fib** [comment]
Thank you! I am able to get the intensity of the current pixel this way.

Is there a way to access arbitrary pixel values by ijk coordinates? I want to compare neighboring pixels to the current one for implementing thresholding, but as far as I can tell this method only reports on the current pixel. Thanks again!

**Comment by neurolabusc** [comment]
You can access all the image data directly. Regardless of how an image is stored on disk, the voxel data is loaded to memory as [RAS](http://www.grahamwideman.com/gw/brain/orientation/orientterms.htm). The code below also shows how to apply the [NIfTI data scaling slope and intercept](https://brainder.org/2012/09/23/the-nifti-file-format/).

[paste the code below into the scripting demo](https://niivue.github.io/niivue/features/scripts.html) and press `run script`.

```
function voxelIJK(r,a,s) {
	//voxel intensity for given column (l->r), row (p->a) and slice (i->s) 
	let hdr = nv1.volumes[0].hdr;
	let img = nv1.volumes[0].img;
	let dimsRAS = nv1.volumes[0].dimsRAS; //image always oriented as RAS
	//convert 0-indexed 3D ras to 1D array address
	let vx = r + a * dimsRAS[1] + s * dimsRAS[1] * dimsRAS[2];
	//raw intensity value (assumes scalar image, beware of rgba images)
	let raw = img[vx];
	//convert raw value to scaled value
	let cal = (raw * hdr.scl_slope) + hdr.scl_inter;
	console.log('dimensions', dimsRAS , 'intensity', cal);
	alert('intensity: '+ cal);
}
voxelIJK(103, 128, 112);
```

**Comment by hanayik** [comment]
@neurolabusc, what are your thoughts on adding a new helper function to get the value at an arbitrary voxel location? Essentially, adding your example `voxelIJK` function to NiiVue. I can implement if you're onboard.

**Comment by neurolabusc** [comment]
@hanayik I am fine with this, but this is a computationally inefficient if the developer wants to read a whole array of voxels. One might also want a variation (or have an overloaded argument) to choose between returning the `raw` value saved to disk versus the scaled `cal`ibrated value.

**Comment by haehn** [comment]
Does `nv.volumes[0].getValue(x,y,z)` offer this functionality?

**Comment by neurolabusc** [comment]
@haehn yes. `getValue()` will provide the same result. In addition, `getValue()` can handle 4D data and provide a scalar intensity value for RGB images. I suspect that getValue()` is not very efficient if you want to read a large array of voxels.
