### ISSUE TITLE
separate overlay (=coloration) and thresholding (= see/not see, or transparency) into separate volumes

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#436]
In some datasets, we have two types of complementary information per voxel:  1) an effect estimate, which might have physical units of BOLD % signal change, and 2) a statistical, which is unitless and carries information of likelihood and is related to uncertainty.  We want to use both pieces of information, but in different ways:  we care about the effect estimate value, and we want to use the statistic to point out which estimates have higher likelihood/believability (or dare-I-say, "significance").  We can map the effect estimate to a colorbar and see whether the BOLD signal is positive or negative, big or small, just by the color;  we can use the "believability" based on the statistic to threshold what we see (though see the transparent thresholding issue, too, for nice ways to include that).  

So, in the RGBA encoding of the data, let the effect estimate map to the RGB value, and let the statistic map to the A.

Some software only displays the statistic value as the overlay, *and* uses the same statistic for thresholding.  In such a case, no information of effect estimate is shown, and it makes some people sad :(.  

For more description of why this is important/useful, see Chen et al. (2017):
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6591724/

**Comment by neurolabusc** [comment]
This property is also useful for diffusion, where we often wish to [modulate the alpha](https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/overlays.html) of the RGB tensor direction with fractional anistropy.

**Comment by neurolabusc** [comment]
@mrneont can you provide sample images. As I noted, this seems either related to or completely solved with existing [modulation of diffusion V1 with FA](https://niivue.github.io/niivue/features/modulate.html) abilities.

**Comment by mrneont** [comment]
@neurolabusc : Sure, [here is an example](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/tutorials/auto_image/auto_%40chauffeur_afni.html#ex-4-overlay-beta-coefs-and-threshold-with-stats) where:
+ the underlay is the anatomical image
+ the overlay is a statistics output, and specifically:
   - the displayed colors are beta coefficient values (with units of BOLD % signal change) from subvolume [1],
   - the thresholding is performed on the associated statistic volume in subvolume [2] (at the magical p=0.001)
In this case, standard/opaque thresholding is applied, so if the voxel in subvolume [2] has p<0.001, one sees the overlay (beta or effect estimate) displayed, while of p>=0.001 there is no overlay value displayed.  In the RGBA notation, RGB is determined by the values in subvol [1], while the A is determined by those in subvol [2]:  if p<0.001 then A=1 (technically, in this case, A=0.5 so you can still see through to the underlay); else A=0.

Here is a [related example](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/tutorials/auto_image/auto_%40chauffeur_afni.html#ex-5-overlay-beta-coefs-and-threshold-translucently-with-stats) where everything is the same, except what happens if p>=0.001---in this case, instead of that voxel strictly getting A=0, the A value fades below the maximum as the statistic gets further from the threshold value.

**Comment by neurolabusc** [comment]
@mrneont I think the latest commit to Thresholding branch should comprehensively address this issue. Try out the updated modulate demos and close this issue if you agree.

**Comment by mrneont** [comment]
@neurolabusc :
This "modulation" demo:
https://niivue.github.io/niivue/features/modulate.html
... works well for showing V1 and V1 modulated by FA;  just the FA overlay doesn't appear to show anything, though (is there a threshold that I should be changing?  I don't see an option to do so).

The original issue here, though, was not really about showing (vectorized) V1 modulated by an FA volume;  it was about showing a (scalar) coefficient volume as an overlay, while thresholding by a separate (scalar).  The functionality is related, but and maybe the under-the-hood part is the same as what is displayed here.  But the idea would be for the user to select one volume for overlaying, to set an appropriate colorbar for it, and then to select a separate volume as the thresholding dataset, and to choose the threshold value to apply to that separate volume (and you have already added in the transparent thresholding and boxing that is great to apply for this part).

thanks,
pt

**Comment by hanayik** [comment]
@mrneont I just published Chris's changes. The new demo is live now.

**Comment by neurolabusc** [comment]
The new demo is https://niivue.github.io/niivue/features/modulateScalar.html

**Comment by mrneont** [comment]
That latter demo page looks like it gives the appropriate behavior, thanks.  I was initially a little confused that I couldn't get the whole brain to show up above threshold, but I see that the threshold slider (tMax) has a minimum at 0.1.

Thanks!
