### ISSUE TITLE
niivue toggle to go from thumbnail view to interaction, *and* back to thumbnail view

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#437]
Howdy-

As recently discussed, it would be useful to be able to go from the thumbnail view to full, fancy niivue interaction dataset visualization with something like Ctrl+Leftclick, *and* to be able to return to the thumbnail view, as well.  

It is hard not to see that a mouseclick should be involved, because certain applications might have multiple niivue thumbnails around.  It also seems useful to have the toggle be more than just a Leftclick, so that an incidental click doesn't shift things.  Also, the humble Leftclick will already be used a lot within niivue to move around the data, so it can't be the action that returns to the thumbnail view.

I don't know that one *has* to have the same action drive both the thumbnail->interactive and the interactive->thumbnail viewing, but it does seem nice.

And just a note that having the both the thumbnail and the interactive states within niivue is really great.  Kudos!

**Comment by hanayik** [comment]
@mrneont, just writing to say that I have not forgotten about this. It will be worked on in the near future :)

**Comment by hanayik** [comment]
Just noting that the priority of this issue has been demoted since the APQC reports in AFNI will most likely implement a NiiVue canvas toggle button rather than defaulting to showing NiiVue with a thumbnail image. The toggle button will hide/show NiiVue just below the existing static images in the report.

**Comment by mrneont** [comment]
Indeed, demote away...
