### ISSUE TITLE
Does NVImage.loadFromBase64 work?

### ISSUE THREAD

**Issue by sabino-ramirez** [niivue/niivue#443]
Im trying to load a small .nii.gz image from a base64 encoding retrieved from python backend. Is there something we should know regarding successfully using loadFromBase64? 
There's no error when loading the image but when I call addVolume(base64Img) I get 'cannot read properties of null'.

Or perhaps a more efficient way to load a .nii.gz image from a GET request to backend?

Thanks!

**Comment by hanayik** [comment]
Hi @sabino-ramirez, Do you have a link to a minimal code example where this is failing? We're using `loadFromBase64` in multiple locations within NiiVue and things are working. Happy to help if you can provide some example data and code.
