### ISSUE TITLE
Right click and drag measure should not draw line on 3D render in A C S R mode. 

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#444]
Screenshot below shows the red measure line drawn on the 3D render. 

<img width="401" alt="Screenshot 2022-12-02 at 1 57 20 pm" src="https://user-images.githubusercontent.com/5217720/205309373-89ee0297-ea9c-49c8-9375-1b95184a065f.png">

**Comment by neurolabusc** [comment]
SHould be fixed in drawing branch. Please close issue if fixed.
