### ISSUE TITLE
Clipped mesh "Voxels not aligned to world space" updates on mouse click/drag when it shouldn't

### ISSUE THREAD

**Issue by bwagnerwork** [niivue/niivue#447]
Hi NiiVue,

With a clipped mesh and image that is not "plumb" I'm getting weird results from mouse interaction.  The video below is from the drawing branch, but I've also had it occur in main (although in the drawing branch with sliceMM=false it doesn't occur).  Basically when I click or drag, the mesh is updating when the expected action is that is shouldn't.  This only seems to happen with images that are out of plumb.  Images that don't throw that warning behave as expected.

https://user-images.githubusercontent.com/9351579/205367687-9ca3f61e-de5e-4517-b6c7-71e36c854f10.mp4

Also it seems the mesh isn't aligned for this view.  Possibly not taking into account the "out of plumbness".

**Comment by neurolabusc** [comment]
It might be worth sharing another interactive sample that includes your data. I presume this is CAT12, and I am not sure the intricacies of the mesh format. For FreeSurfer, a single GIfTI mesh can store several spatial transformation matrices that allow you to compute an affine matrix for both native space as well as MNI space. So software needs to select the transform that matches the voxelwise image.

**Comment by bwagnerwork** [comment]
Using your sample and e4e19db drawing branch (https://wagners.homeip.net/work/nv_plumb_issue2.html) I'm only seeing the issue when **sliceMM is set true**. The first clip can be found at https://wagners.homeip.net/work/nv_plumb_issue.html.  

This is CAT12 data ([nonplumb.zip](https://github.com/niivue/niivue/files/10157716/nonplumb.zip) selected files).  I loaded the dataset in freeview to confirm it overlayed well.  When I created a similar scene in AMI.js (ages ago), I had to apply the same transforms to freesurfer and cat12 to get them to overlay correctly.  FYI.

**Comment by neurolabusc** [comment]
I am setting this to acknowledged and it is related to [issue 415](https://github.com/niivue/niivue/issues/415). Specifically, NiiVues 2D slices always sample orthogonal to the voxel sample grid. This avoids the alias artifacts and inability to edit drawings seen in tools like FSLeyes. Non-oblique volumes cause issues for any tools, and you can see this with tools like Slicer3D and AFNI. 

The core issue is that [NiiVue clips meshes by using the world space oriented clip space](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_model_view_projection). Unfortunately, the OpenGL-ES based WebGL [does not have an equivalent of the OpenGL `glClipPlane`](https://groups.google.com/g/webgl-dev-list/c/0vUJ9r6g_bg). Therefore, there is no obvious efficient solution. I am working on getting meshes to be properly transformed when `sliceMM=false`, which should allow clipping to work correctly in that representation. 

Handling oblique data presents a complex series of tradeoffs, and I think NiiVue introduces a unique alternative. It allows users to visualize the orientation, edit drawings, and avoids aliasing artifacts. However, without access to arbitrary clip-planes, we will be limited in our ability to apply mesh clipping in our world space views. Perhaps we simply have to restrict the world space mesh clipping to plumb data.

**Comment by neurolabusc** [comment]
@bwagnerwork this latest commit to the drawing branch should improve the alignment when `sliceMM=false`. I have to think very carefully regarding whether we can accurately model mesh clipping with `sliceMM=true`. There are a couple of [leads](https://stackoverflow.com/questions/49092512/how-to-do-clipping-planes-on-opengl-es-2-or-3) but some are not universal and others would incur a big performance hit, which is not ideal when we are trying to enable any device including low power mobile devices. It might be that we can not enable all features in all modes.

Before: mesh vertices had poor alignment in voxel space
![crop](https://user-images.githubusercontent.com/8930807/205988259-27ad148a-1501-4360-8f51-0a19ad952c99.png)
Now: Mesh vertices a transformed to orthogonal voxel space
![crop2](https://user-images.githubusercontent.com/8930807/205988271-f5d7b188-fce3-45f8-857a-c58cc4d1842a.png)

**Comment by bwagnerwork** [comment]
@neurolabusc That's great!  My use of sliceMM=true was a bit of a hack given the current main branch.  I'm happy to live in voxel space.

**Comment by neurolabusc** [comment]
@bwagnerwork this has now been merged into the main branch. For this application, you will want to use `sliceMM=false`. I am closing this issue, but we will still need to document this better.
