### ISSUE TITLE
Include version details

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#453]
At the moment, the NiiVue version is stored in the [package.json](https://github.com/niivue/niivue/blob/95c63e9ed6485cc4e488554ed7290d0684f947f8/package.json#L3) file. I think the version number should be reported by a console.log() when a NiiVue instance is created. This will help with bug reporting and demos.

**Comment by hanayik** [comment]
Hi Chris,

I have just submitted a PR that adds this. When NiiVue is built, a new variable will be defined __NIIVUE_VERSION__ that will always be in sync with the value listed in package.json.

Also, I have removed all console.log statements in favor of our log.debug() which can be turned on or off by setting logging:true when creating a niivue instance.

When logging is set to true, the __NIIVUE_VERSION__ will be printed to the console at the moment niivue is linked to a canvas.



From: Chris Rorden ***@***.***>
Date: Wednesday, 21 December 2022 at 2:51 pm
To: niivue/niivue ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [niivue/niivue] Include version details (Issue #453)

At the moment, the NiiVue version is stored in the package.json<https://github.com/niivue/niivue/blob/95c63e9ed6485cc4e488554ed7290d0684f947f8/package.json#L3> file. I think the version number should be reported by a console.log() when a NiiVue instance is created. This will help with bug reporting and demos.
