### ISSUE TITLE
New years resolutions

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#458]
Perhaps it is worth having a discussion of potential new features that should be considered for the pinned [WIP](https://github.com/niivue/niivue/issues/237) list. There is always a tension between a lean, easy to maintain code base versus powerful features. Here are a few ideas worth considering.

### Barycentric Effects

[Surfice](https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage) uses the geometry shader to create barycentric effects on the fly. For example the wireframe and disks effects shown in the image. WebGL does not have a geometry shader. However, we could pre-process meshes [to create these effects with WebGL](https://tchayen.github.io/posts/wireframes-with-barycentric-coordinates). The downside is that without the geometry shader these effects do not re-use vertices, so the number of vertices that the GPU needs to handle increases  dramatically, which might lead to poor performance for complex meshes on mobile devices.  
![barycentric](https://user-images.githubusercontent.com/8930807/209678789-ce41938c-be4d-4127-ba16-f23035cc9cc7.jpg).

### Matcap Effects

[Surfice](https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage) and [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage) provide Matcap shaders, including the famous Blender Matcaps. This is an efficient way to emulate complex lighting like metallic or slimy surfaces, as shown in the image below. These would be easy to add to NiiVue, as seen in its ancestor [MRIcroWeb](https://github.com/rordenlab/rordenlab.github.io). However, this does require including each Matcap as a separate jpeg image, so the distribution becomes a bit bulkier.

![matcap](https://user-images.githubusercontent.com/8930807/209679719-b1994b3f-caae-41a4-8e87-2390a3c1b104.jpg)

### Streamline Effects

[NiiVue draws streamlines as lines](https://niivue.github.io/niivue/features/tracts.html) which are limited to 1-pixel thickness and are unable to show lighting effects. Extruding the streamlines to triangulated cylinders would lead to unacceptable performance on most mobile devices. [MRtrix](https://community.mrtrix.org/t/visualization-with-tckmap-vs-mrview/1022) uses a clever geometry shader, but these are not available in WebGL (nor other mobile oriented languages like Metal). [Surfice](https://github.com/neurolabusc/surf-ice/blob/1885f5dec0aff7691ac1995b75c3035fe09e3d37/gl_core_3d.pas#L139) provides a vertex shader we could use which is described [here](https://www.researchgate.net/publication/319441378_A_Simple_and_Efficient_Cylinder_Imposter_Approach_to_Visualize_DTI_Fiber_Tracts). This doubles the number of vertices compared to simple lines though it is still a fraction of triangulated cylinders. This would require porting a lot of code to JavaScript to pre-process the streamlines.

![tubes](https://user-images.githubusercontent.com/8930807/209680749-59af8eef-e248-4274-b633-7d1df89fb2a2.jpg)

**Comment by hanayik** [comment]
thanks @neurolabusc, I have created new issues (enhancements) for each of the items you listed. They are all great features to add to NiiVue, and where performance could be an issue on mobile, we can detect this and produce warnings or disable features as needed.
