### ISSUE TITLE
Save the problem. Not all views are saved after sketching

### ISSUE THREAD

**Issue by wujie1314** [niivue/niivue#460]
The saved file is used to load the original drawing that cannot be restored

**Comment by neurolabusc** [comment]
I am not sure I understand the question. Can you provide the steps to replicate the issue or a video demonstrating the issue. 

You can use the [drawing demo](https://niivue.github.io/niivue/features/draw.ui.html) and choose the Draw/Red, Draw/Green and Draw/Blue menu items to sketch new shapes. Once you have created your drawing, use the File/SaveDrawing to save your new drawing as a NIfTI file. You can drag and drop this new image onto NiiVUe: note that red, green and blue are mapped as 1,2,3 respectively: matching the expectation of tools like AFNI, FSL, FreeSurfer and SPM expect masks to be scalar intensities.

**Comment by wujie1314** [comment]
Before saving the painting：
![image](https://user-images.githubusercontent.com/41436763/210025454-2f29944e-7de6-47dd-9bc9-7141a947b7c0.png)
Load the saved file：
![image](https://user-images.githubusercontent.com/41436763/210025520-6618f5e4-2426-400d-9650-cf041af762f9.png)
The loaded images are different

**Comment by neurolabusc** [comment]
Thank you for the images. The software is working as intended. You loaded the saved file as a scalar background image with the "gray" colorscheme. You can solve your problem by opening the drawing with the [loadDrawingFromUrl](https://niivue.github.io/niivue/devdocs/Niivue.html#loadDrawingFromUrl) function. A live demo of using this function is found [here](https://niivue.github.io/niivue/features/draw.ui.html).

The screenshot below shows the [live demo](https://niivue.github.io/niivue/features/draw.ui.html) where I have drawn `R`, `G` and `B` with the red, green and blue pen and then used the File/SaveDrawing menu item to save the drawing. The right side of the image shows an instance of [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage) where I used the File/Open menu item to open the FLAIR background image and the Draw/OpenVOI to open the drawing I created with NiiVue. 

![draw3](https://user-images.githubusercontent.com/8930807/210109392-6d03bf03-6e73-4383-b3c8-4e0f792dc588.jpg)

NiiVue is a modular tool that developers can wrap with their own user interfaces to achieve a wide range of tasks, viewing the results with any web enabled device (phone, tablet, computer). I recommend [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage), [ITKsnap](http://www.itksnap.org/pmwiki/pmwiki.php) or [FSLeyes](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes) as monolithic tools with nice drawing tools.

**Comment by neurolabusc** [comment]
1. The latest stable release will load an image as a drawing if you press the `Alt` key while dropping an image. 
2. The core NiiVue repository is designed to live in a web page sandbox, which imposes strict limitations on file system access. However, the new [afNiiVue](https://github.com/niivue/afNiiVue) repository provides a minimal electron wrapper for NiiVue that allows native file system access for Linux, MacOS and Windows. That provides a more comprehensive solution for your question.
