### ISSUE TITLE
Can the clarity be improved？

### ISSUE THREAD

**Issue by wujie1314** [niivue/niivue#461]
![image](https://user-images.githubusercontent.com/41436763/210032241-a11cb977-49d8-4ddf-8026-aacdf7d8b00c.png)
Not very clear   Can it be more smooth or my model is out of order

**Comment by neurolabusc** [comment]
I think the core issue is the low resolution of your voxel-based atlas. NiiVue is faithfully representing the resolution of this image. In general, scalar images can look nicer in rendering versus categorical labeling maps as one can interpolate a less jagged edge. I would see if you can get the atlas as a higher resolution voxel-based image, or to see if there is a mesh-based version.

If you are using a desktop computer, you might also want to try out [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage) which includes several rendering modes (e.g the `Default` mode is shown in the screenshot below). NiiVue is designed for high performance to work well with low power devices (phones), so rendering shaders as not as sophisticated. The screenshot below shows MRIcroGL and also illustrates the `spmSUIT` atlas that is included with MRIcroGL.  

![suit2](https://user-images.githubusercontent.com/8930807/210110359-6e382211-15cd-4de3-8a42-1572db01cf30.png)
