### ISSUE TITLE
update window/level contrast

### ISSUE THREAD

**Issue by haehn** [niivue/niivue#463]
Hi, I would like to update the contrast through JS.

I tried the following:

`nv.volumes[0].cal_min = -300` 
`nv.volumes[0].cal_max = 1000` 

but the display does not adjust. I tried to call a drawScene after but still no change - what am I missing?

**Comment by neurolabusc** [comment]
Rescaling all the voxels for a 3D image is computationally expensive. After you change all your volume properties, you will want to refresh the layer. To update just the first volume of the first layer you could write:

```
      nv1.volumes[0].cal_min = -300
      nv1.volumes[0].cal_max = 1000
      nv1.refreshLayers(nv1.volumes[0],0,1);
      nv1.drawScene();
```
If you want to apply changes to all the layers, you can choose:
```
      nv1.volumes[0].cal_min = -300
      nv1.volumes[0].cal_max = 1000
      nv1.updateGLVolume();
```
By deferring the computation, the change is calculated just once, regardless of how many properties you change. It is one extra call for the developer, but it improves the user experience.

**Comment by neurolabusc** [comment]
I notice from your intensity range that you are working with CT images (MR magnitude images never have negative values). A nice feature of CT intensity is that it is calibrated in Hounsfield units, allowing one to specify the precise tissue to identify (whereas most MR modalities have relative intensities). You can leverage this by choosing the ct_* color,maps, that specify both a color scheme and intensity range. 

You can try this out with the [test images live demo](https://niivue.github.io/niivue/features/test_images.html): select the `CT_abdo` image from the top panel and then try out the `ct_*` color schemes from the bottom panel.

**Comment by haehn** [comment]
Thanks - that works!
