### ISSUE TITLE
resetBriCon called when no volumes are present

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/niivue#468]
In the touchStartListener in src/niivue.js, when double-clicking, resetBriCon gets called.
If no volumes have been added, this error is given: 
```js
Uncaught TypeError: Cannot read properties of undefined (reading 'robust_min')
    at Niivue.resetBriCon
```
There should probably be a check either in touchStartListener or resetBriCon to see if `volumes.length > 0`.

**Comment by neurolabusc** [comment]
@AnthonyAndroulakis nice catch. I have added the change you suggested to the `thresholding` branch. We can close this issue after that is merged.
