### ISSUE TITLE
Add Matcap Effects

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#477]
As mentioned in #458, it would be nice to add these effects since MRIcroGL has them. I'm not too worried about the bundle size after including these new images. None of our users have complained about the Niivue bundle size, and the images typically displayed in NiiVue are much larger than NiiVue itself.

**Comment by neurolabusc** [comment]
I have added a MatCap shader mesh shader with several example MatCaps (shiny, cortex, plastic, fuzzy). Users can find many more MatCaps by doing a Google image search with the term `matcap images`.

![matcap](https://user-images.githubusercontent.com/8930807/212374896-8c94ed7b-e766-4c7f-8004-02876270fa57.jpg)
