### ISSUE TITLE
Mesh rendering performance

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#482]
@mrneont and @afni-dglen note that visualization is not fluid when Intel integrated graphics are used with [HighDPI displays](https://www.khronos.org/webgl/wiki/HandlingHighDPI).  This is seen in the [FreeSurfer demo with 164k vertices](https://niivue.github.io/niivue/features/mesh.freesurfer.html) which is sluggish on Intel Mac's with `retina` displays, but fluid on Apple Silicon Mac's with similar displays. Perhaps the `opts.isHighResolutionCapable` default should be initialized as `false` if the rendererInfo reports an Intel GPU.

A more complicated but sophisticated solution would be to use low resolution during dynamic motion and use high resolution when user interaction pauses (this is the default behavior of MRIcroGL).

**Comment by mrneont** [comment]
@neurolabusc : that sounds good, thanks.

**Comment by afni-dglen** [comment]
Thanks. Just to be sure, I'm seeing this seemingly erratic behavior on an Intel MacBook Air (2020). At higher resolution (4k or 1440p), it seems to be a little better than lower resolution (1080p). Most of this is from just too fast rotations. The rotation rate seems to increase as I move the mouse cursor toward the center and then slow down as I move away. It's more usable far from the center. 

On my M1 MacBook Air (2021), it works, but it's still a little faster than I would expect, but it's fluid. I'm using a 1000dpi mouse, and I think I get about 1-1/2 rotations moving the mouse very slowly from left to right across that FreeSurfer surface. If I move it quickly, I get many more rotations. I think in no case do we need a very fast rotation for this, so setting a limit on rotational speed seems like a good idea.

BTW, the FreeSurfer demo surface doesn't appear on my equally vintage Android phone.

**Comment by neurolabusc** [comment]
Closing this issue. The latest release changes the defaults to trade-off quality for performance. The equipment of @afni-glen and @mrneont report that the latest release provides acceptable if not fluid performance on their [MacBooks](https://techable.com/apple/specs/macbook-air-13-inch-core-i5-11-ghz-2020/) that use a [1.1GHz processor with integrated Intel CPU](https://www.notebookcheck.net/Intel-Core-i5-1030NG7-Processor-Benchmarks-and-Specs.458928.0.html) constrained by a 10w TDP and a design with minimal cooling driving a high resolution (2560×1600) monitor.  The pull-request provides further details.

Its worth noting that the default FreeSurfer meshes have a huge number of triangles and in theory NiiVue could apply [adaptive simplification](https://rordenlab.github.io/nii2meshWeb/). Indeed, the FreeSurfer meshes are designed to [allow simple decimation](https://brainder.org/2016/05/31/downsampling-decimating-a-brain-surface/). However, it should be noted that the support for this decimation necessarily means that [FreeSurfer meshes do not store vertex data in a cache efficient manner](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html). Unfortunately, simplification or vertex optimization](https://github.com/zeux/meshoptimizer) would break the correspondence between FreeSurfer meshes and the vertex overlays (thickness, curvature, statistical scalars). Therefore, FreeSurfer meshes are inherently inefficient to display. NiiVue is fluid on most devices, and usable on older devices.
