### ISSUE TITLE
reset all views

### ISSUE THREAD

**Issue by haehn** [niivue/niivue#484]
Hi, is there something like `nv1.reset()` which sets all camera positions back to after loading? If not, could we please add it? I looked at `nv1.screenSlices` but it looked complex.

**Comment by neurolabusc** [comment]
@haehn if you try the latest commit to the thresholding branch you will see a new option `nv1.setDefaults()`. I think this name is more consistent with other functions than `nv1.reset()`, but do not have a strong opion on this. I added buttons to demonstrate this if you run `npm run dev` as well as `npm run demo` (the `connectome` demo for the latter).

Note that it resets the options, but does not change values in your web page. For example, if you have a checkbox that allows the user to toggle `isRadiologicalConvention`, you will want to make sure it reflects the updated options.

**Comment by haehn** [comment]
Thank you!
