### ISSUE TITLE
resolve NVMesh.loadFromBase64 issues

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#495]
see: https://github.com/nilearn/nilearn/issues/3451

@alexisthual, could you add details of the issue you encountered?

**Comment by alexisthual** [comment]
> see: [nilearn/nilearn#3451](https://github.com/nilearn/nilearn/issues/3451)
> 
> @alexisthual, could you add details of the issue you encountered?

@AnthonyAndroulakis described the issue right here: https://github.com/nilearn/nilearn/issues/3451#issuecomment-1405330955

I think now the main issue is that loadFromBase64 doesn't handle gzipped files.

**Comment by alexisthual** [comment]
I think this can be closed as we (@ymzayek @AnthonyAndroulakis @neurolabusc) just tested feeding a base64 string of a gunzip gifti file and it worked! :tada:
