### ISSUE TITLE
The loading file gz file is a little unclear on the page

### ISSUE THREAD

**Issue by wujie1314** [niivue/niivue#502]
![2f4ded436b0f45a4d6747d45fb40e17](https://user-images.githubusercontent.com/41436763/216001452-7784c9b1-f91a-43c2-8c32-3b70c45defc9.png)
![68450cb4ef12d4d5d89ec5f8fc50a2d](https://user-images.githubusercontent.com/41436763/216001493-c08781bc-75c0-4b83-906c-1d8d3f5095b5.png)
The loading effect of the image file you gave is much better

**Comment by neurolabusc** [comment]
This is a consequence of using an image segmented map with categorical values. Your atlas does not deal with partial volume effects. In your atlas, a voxel is either blue or it is not. In the lower image voxel opacity is continuous not discrete: brighter voxels are more opaque than darker voxels. 

Continuous volume rendering is like the boundary of a cloud in the sky: there is not an instantaneous boundary of being inside the opaque cloud or outside in clear air, rather their is a gradient where visibility becomes more and more obscured. 

This is a limitation of your segmentation, not NiiVue. If you had a probabilistic atlas that mapped the partial volume effects, the appearance would look less jagged. NiiVue is accurately showing the discrete nature of the image you are asking it to visualize.

**Comment by wujie1314** [comment]
Is there any parameter adjustment smooth？

**Comment by wujie1314** [comment]
> This is a consequence of using an image segmented map with categorical values. Your atlas does not deal with partial volume effects. In your atlas, a voxel is either blue or it is not. In the lower image voxel opacity is continuous not discrete: brighter voxels are more opaque than darker voxels.
> 
> Continuous volume rendering is like the boundary of a cloud in the sky: there is not an instantaneous boundary of being inside the opaque cloud or outside in clear air, rather there is a gradient where visibility becomes more and more obscured.
> 
> This is a limitation of your segmentation, not NiiVue. If you had a probabilistic atlas that mapped the partial volume effects, the appearance would look less jagged. NiiVue is accurately showing the discrete nature of the image you are asking it to visualize.

Is there any parameter adjustment smooth？

**Comment by neurolabusc** [comment]
The [drawing user interface demo](https://niivue.github.io/niivue/features/draw.ui.html) includes the `Smooth interpolation` item in the `view` menu that toggles trilinear versus nearest neighbor interpolation for the 2D slices. However, I get the sense that you are looking for a more dramatic impact. In general, the remit of NiiVue is limited to image visualization, to achieve a relatively clean API. 

JavaScript is a scripting language, so you could always write your own, or adapt the [fslmaths](https://niivue.github.io/niivue-niimath/) functions. Alternatively, you could embed NiiVue into a [Jupyter notebook](https://github.com/niivue/ipyniivue) and use Python functions for image processing.
