### ISSUE TITLE
XML files are not read properly in NVMesh

### ISSUE THREAD

**Issue by alexisthual** [niivue/niivue#507]
Linked to https://github.com/nilearn/nilearn/issues/3451#issuecomment-1416174323

**Summary**
It seems that XML files are not read properly by `NVMesh` methods because they read XML files line by line.
In particular, `NVMesh.readGII()` can't read gifti files generated with `nibabel` (and probably a lot of other gifti files).

**The specific case of `NVMesh.readGII()`**
Here are 2 issues I spotted for `NVMesh.readGII()` :
- it reads xml files line by line, which prevents it from reading base64 data when it's not stored in a line of its own
- it doesn't handle float64 arrays

Here is a python snippet which will create a valid gifti file which `niivue` can't read:

```python
# %% make_surface.py
import pathlib

import nibabel as nib

from nilearn import datasets, surface

fsaverage = datasets.fetch_surf_fsaverage("fsaverage7")

motor_images = datasets.fetch_neurovault_motor_task()
stat_img = motor_images.images[0]
surface_map = surface.vol_to_surf(stat_img, fsaverage.pial_left)

surface_map_path = "./surface_map.gii"

img = nib.gifti.gifti.GiftiImage()
img.add_gifti_data_array(
    nib.gifti.gifti.GiftiDataArray(
        surface_map,
        intent="NIFTI_INTENT_ZSCORE",
    )
)
nib.save(img, surface_map_path)
```

The generated file looks something like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GIFTI SYSTEM "http://www.nitrc.org/frs/download.php/115/gifti.dtd">
<GIFTI Version="1.0" NumberOfDataArrays="1"><MetaData /><LabelTable /><DataArray Intent="NIFTI_INTENT_ZSCORE" DataType="NIFTI_TYPE_FLOAT64" ArrayIndexingOrder="RowMajorOrder" Dimensionality="1" Encoding="GZipBase64Binary" Endian="LittleEndian" ExternalFileName="" ExternalFileOffset="0" Dim0="163842"><MetaData /><CoordinateSystemTransformMatrix><DataSpace>NIFTI_XFORM_UNKNOWN</DataSpace><TransformedSpace>NIFTI_XFORM_UNKNOWN</TransformedSpace><MatrixData>  1.000000   0.000000   0.000000   0.000000
  0.000000   1.000000   0.000000   0.000000
  0.000000   0.000000   1.000000   0.000000
  0.000000   0.000000   0.000000   1.000000</MatrixData></CoordinateSystemTransformMatrix><Data>...</Data></DataArray></GIFTI>
```

But as `NVMesh.readGII()` reads it line by line and [loads data only if it comes across a line which starts with `"<Data>"`](https://github.com/niivue/niivue/blob/f9c3849554a83f4028f91f4c440537ff5f526ef3/src/nvmesh.js#L3063), it doesn't load this file properly.
Adding a few carriage return solves this issue:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GIFTI SYSTEM "http://www.nitrc.org/frs/download.php/115/gifti.dtd">
<GIFTI Version="1.0" NumberOfDataArrays="1">
<MetaData />
<LabelTable />
<DataArray Intent="NIFTI_INTENT_ZSCORE" DataType="NIFTI_TYPE_FLOAT64" ArrayIndexingOrder="RowMajorOrder" Dimensionality="1" Encoding="GZipBase64Binary" Endian="LittleEndian" ExternalFileName="" ExternalFileOffset="0" Dim0="163842">
<MetaData />
<CoordinateSystemTransformMatrix>
<DataSpace>NIFTI_XFORM_UNKNOWN</DataSpace><TransformedSpace>NIFTI_XFORM_UNKNOWN</TransformedSpace>
<MatrixData>  1.000000   0.000000   0.000000   0.000000
  0.000000   1.000000   0.000000   0.000000
  0.000000   0.000000   1.000000   0.000000
  0.000000   0.000000   0.000000   1.000000</MatrixData>
</CoordinateSystemTransformMatrix>
<Data>...</Data>
</DataArray></GIFTI>
```

I think the logic of `NVMesh.readGII()` needs to be reworked so that it handles gifti files which no carriage returns.
Instead of processing lines, it should probably process tags.

**Methods affected by this behaviour**
This problem is most like present in other methods as well. In particular, it seems that all functions like `NVMesh.readNII2()`, etc all have `readStrX()` and `readStr()` utility functions which read files line by line instead of tag by tag. I also checked `NVImage` quickly but couldn't really tell if this problem is present there as well.

**Comment by neurolabusc** [comment]
@alexisthual thanks for your help on this. We certainly want to have a compliant solution. The motivation for our implementation is the very slow performance of conventional JavaScript implementations at reading XML. We originally used [GIFTI-Reader-JS](https://github.com/rii-mango/GIFTI-Reader-JS) which has good compliance but poor performance. I am happy to improve our implementation, but it is worth asking whether NIFTI_TYPE_FLOAT64 is appropriate for most use cases. nibabel issues [1089](https://github.com/nipy/nibabel/issues/1089), [1046](https://github.com/nipy/nibabel/issues/1046) and [792](https://github.com/nipy/nibabel/issues/792) seem related. I acknowledge that it is much easier to determine excessive precision with integers than floats. In general, I think it is great to use high precision internally when computing results to minimize the influence of rounding errors. However, for storage one needs to consider how many situations really require more than [6-9 significant decimal digits](https://en.wikipedia.org/wiki/Significant_figures) of precision. I do think that different hardware implementations do not maintain this level of precision: consider x86 code that might use the FPU (80-bits internal) or SSE (64-bits) for each calculation, or a compiler that chooses between a single FMA operation versus separate multiply and add operations. I think this explains why popular tools like FreeSurfer and AFNI do not write FLOAT64.

**Comment by alexisthual** [comment]
I think recent changes allow us to safely close this issue. Thanks! :slightly_smiling_face:
