### ISSUE TITLE
Automatic code formatting

### ISSUE THREAD

**Issue by alexisthual** [niivue/niivue#516]
This codebase is still young, I think it's still a good time to automate code formatting :smile: 
I really like working with [`prettier`](https://prettier.io/), which does a great job at formatting js, html and css files.

**Comment by hanayik** [comment]
@alexisthual , this is already run on [each build](https://github.com/niivue/niivue/blob/main/package.json#L16). Are there some examples that show this not working? It's possible something slipped through the cracks.

**Comment by alexisthual** [comment]
Yes sorry, my formulation was a bit too dramatic haha.
I ran `prettier` on the entire codebase. It changed 77 files, mostly located in `./tests`.

**Comment by neurolabusc** [comment]
I do think we should consider also formatting the *.html files in /demos/features. These include different forms of white space (tab vs space) and the JavaScript is idiosyncratic, with some lines ending with a semicolon while others do not. These are often the first code that new developers will look at, so it might be nice to make these look more consistent.

**Comment by neurolabusc** [comment]
@alexisthual your PR did not clean up the *.html files in the folder /demos/features, only *.css and *.js files.

**Comment by alexisthual** [comment]
Wooops, sorry, `html` files were indeed in `.prettierignore` so they were not formatted.
