### ISSUE TITLE
Tractography plotting improvements

### ISSUE THREAD

**Issue by pierre-nedelec** [niivue/niivue#523]
Hello! I've been experimenting more with niivue and it looks great! However, I'd like to do the following:
- Color/show specific bundles (from `.trk`)
- Clip the tractography (mesh) view when added to 2D volume views to a given threshold before/after the plane

Is it possible with the current implementation or does it require some tweaking?

Concerning the first point, in `nvmesh.js`, I see the following:
- [Bundle reading for `readTRACT`](https://github.com/niivue/niivue/blob/df657245fc510e1318f0c7fdba4fce14e7d6bb1c/src/nvmesh.js#L909)
- Nothing of the sort in [`readTRK`](https://github.com/niivue/niivue/blob/df657245fc510e1318f0c7fdba4fce14e7d6bb1c/src/nvmesh.js#L1007)

**Comment by neurolabusc** [comment]
@pierre-nedelec you can already show bundle specific colors. The [tractography demo](https://niivue.github.io/niivue/features/tracts.html) includes a pull-down menu that allows you to set per-vertex and per-streamline colors. For [TrackVis TRK files](https://trackvis.org/docs/?subsect=fileformat) the [n_properties sets the data_per_streamline (dps)](https://github.com/niivue/niivue/blob/df657245fc510e1318f0c7fdba4fce14e7d6bb1c/src/nvmesh.js#L1066) and [n_scalars sets the data_per_vertex (dpv)](https://github.com/niivue/niivue/blob/df657245fc510e1318f0c7fdba4fce14e7d6bb1c/src/nvmesh.js#L1033). The As you note, the AFNI .tract.niml format uses `Bundle_Tag` to set dps. NiiVue code uses the dps and dpv terminology to match the [TRX](https://github.com/tee-ar-ex/trx-spec/blob/master/specifications.md) specifications.

**Comment by neurolabusc** [comment]
With regards to clipping the mesh near a boundary, do take a look at [`mesh clipping` slider on the advanced world space demo](https://niivue.github.io/niivue/features/worldspace2.html). Note that it works on the 2D slices, not the 3D rendering. Also, if your voxel data grid is rotated relative to world space, the effect works best in voxel space mode not world space mode. This reflects an inherent limitation of WebGL2, where you can not read the depth buffer. A great thing about WebGL2 is that it is a lowest common denominator language that can be implemented on the optimal graphics driver for the hardware (OpenGL ES, Metal, Vulcan, DirectX). However, a consequence of this is that it lacks some of the advanced features of these advanced APIs (e.g. geometry shaders, reading depth buffer, etc).

**Comment by pierre-nedelec** [comment]
Hi @neurolabusc! Thank you for pointing out to the example, it was super helpful. Sorry I meant to come back to this earlier, I don't think it's quite closed yet.
- The mesh clipping works great.
- The default bundle highlighting works too (with `nv1.setMeshProperty(nv1.meshes[0].id, "fiberColor", "DPS0");`)
- However, is there a way to:
  - specify the color for each tract based on tract name?
     - What is the correct way to assign a colormap that maps into the bundle id? it seems I can modify `nv1.colormap` maybe, but not sure if that's the right approach...
https://github.com/niivue/niivue/blob/df657245fc510e1318f0c7fdba4fce14e7d6bb1c/src/nvmesh.js#L240-L256
     - Also, in `nv1.meshes[0].dps`, I only see numerical values, not bundle names, even though those were saved in the `trk` file (see screenshot below). The mapping should occur by name and not just id since these could be mixed up. 
  - decide which one to show or to hide? 


<img width="525" alt="image" src="https://user-images.githubusercontent.com/65797646/223282952-e7d5421c-a88c-4794-9de4-942da88f6399.png">
 

Thank you for your help!

**Comment by pierre-nedelec** [comment]
Thanks for the response, I understand the limits of the TRK file better. Looks like TRX is very promising! I think I could currently overcome that by using the json sidecar that comes with the TRK file which has the mapping between bundle name and # (see below).

Concerning the coloring, thanks for pointing out the example file. Re: your `cal_min` comment, if for some reason the tract # is different from one file to the other using a colormap like that wouldn't be consistent, so it'd be useful to be able to assign a color to each # by passing a dictionary or function as argument. I can imagine people to be interested in that with other types of property for which they want some fancy coloring (e.g., thresholding, non linear mapping).

But more importantly for us here, is there a way to show/hide bundles based on property value? I.e., could I tell NiiVue to only display fibers that have the DPS property value of 5?

```json
"bundle_ids": {
    "ATR_L": 1,
    "ATR_R": 2,
    ...
    "VOF_R": 17,
    "VOF_L": 18
    }
```
Thanks!
