### ISSUE TITLE
Remove haze function

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#53]
NiiVue should include operations to remove haze from a volume. This can help the appearance of the volume rendering, and ensure good behavior for depth picking. I would suggest copying the method from MRIcroGL. As an aside, I wonder if there are any JavaScript tools that do something like FSL's [BET](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BET/UserGuide).

 - [Blog](https://github.com/neurolabusc/blog/tree/main/GL-extract)
 - [MRIcroGL](https://github.com/rordenlab/MRIcroGL/tree/master/Haze)

![haze](https://user-images.githubusercontent.com/8930807/129586004-e2746396-aa06-4429-9ff1-83e419533eab.jpg)

**Comment by hanayik** [comment]
This will be part of niimath wasm

**Comment by neurolabusc** [comment]
niimath is now ported to WASM. In general, it is a superset of fslmaths. 

You can evaluate this WASM implementation from the command line using the niimath.js project, which is a rough clone of fslmaths:

```
git clone --branch development https://github.com/rordenlab/niimath
cd niimath/src
emcc -O2 -s ALLOW_MEMORY_GROWTH -s MAXIMUM_MEMORY=4GB -s TOTAL_MEMORY=268435456 -s WASM=1 -DUSING_WASM -I. core32.c nifti2_wasm.c core.c walloc.c -o funcx.js
node test.js
npm install nifti-reader-js
node niimath.js ~/T1.nii.gz -dehaze 5 ~/dT1.nii
```
