### ISSUE TITLE
Improvements for the documentation

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/niivue#530]
While reading through niivue's documentation, I've come up with a few improvements. 
As these are relatively short, I've grouped them into this 1 issue. 

1. saveScene: the filename parameter has a default value of "". This default value is not mentioned in the documentation.
2. setMeshThicknessOn2D: The sentence "Use Infinity to show entire mesh or 0.0 to hide mesh." should be in the description of the `meshThicknessOn2D` parameter, not in the description of the function.
3. the example given for `setSliceMosaicString` has a typo: it should say `niivue.setSliceMosaicString("A 0 20 C 30 S 42")` instead of `niivue.setMeshThicknessOn2D("A 0 20 C 30 S 42")`
4. setSliceMM: The descriptions of the `isSliceMM` parameter and the `setSliceMM` function should be switched for clarity purposes.
5. loadDrawingFromUrl: the 2nd parameter, `isBinarize`, is not mentioned in the documentation
6. drawOtsu: The description for this function would benefit from having a little more detail. For example, "Use the Otsu thresholding algorithm to separate pixels into multiple different classes."
7. setPenValue: the first parameter, `penValue`, is listed as having type `boolean`. However, in the example, `penValue` is given an integer value (`1`). Also, the default value of `isFilledPen = false` is not listed in the documentation.
8. removeHaze: The default values of the arguments (`level = 5, volIndex = 0`) are not mentioned in the documentation.
9. saveImage: The default value of `isSaveDrawing = false` is not mentioned in the documentation. Also, the live demo page linked does not exist (the linked demo should be `https://niivue.github.io/niivue/features/draw.ui.html` instead).
10. removeVolumeByIndex: This function is defined 3 times in the niivue.js. This makes it show up 3 times in the documentation. It should only show once.
11. setDrawOpacity: there is a typo in the description. `tansparent` should be `transparent`
12. loadConnectome: the documentation states that the the json parameter is of type string. From reading the code, it looks like it should be an Object.
13. setMeshShader: default value of `meshShaderNameOrNumber=2` is not stated in the documentation
14. setCustomMeshShader: default values of `fragmentShaderText = "", name = "Custom"` are not stated in the documentation. Also, the description for this function is wrong.
15. setModulationImage: Parameters 1 and 2 are incorrectly named in the documentation. They should be listed as `idTarget` and `idModulation`. Also, the default value of `modulateAlpha = false` is not stated in the documentation.
16. binarize: the example needs to be updated

**Comment by hanayik** [comment]
@AnthonyAndroulakis , could you work on implementing these suggestions to the documentation as a new PR?

**Comment by neurolabusc** [comment]
@hanayik my attempt to resolve these [submitted as a PR and committed](https://github.com/niivue/niivue/commit/fb7c83aa67773b0ad7890d97e2987179e8681d4c). It would be great if we could publish the updated documentation and have @AnthonyAndroulakis review everything and close this issue if he is happy with my solutions.

**Comment by hanayik** [comment]
@neurolabusc , It should have published via the last PR that was merged in a few min ago. I needed to fix some of the JSdoc comments to show default argument values correctly.

**Comment by discordtehe** [comment]
> @AnthonyAndroulakis , could you work on implementing these suggestions to the documentation as a new PR?

Sorry I did not see this comment in time. I'll take a look at the PR @neurolabusc committed.

**Comment by AnthonyAndroulakis** [comment]
@hanayik Apologies, did not see this thread earlier. @neurolabusc This all looks good. Thank you for implementing these suggestions.
