### ISSUE TITLE
saveImage function does not work

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/niivue#532]
**Describe the bug**
The niivue.saveImage function does not save the image properly. Instead it saves a 9 bytes file, the only contents being `undefined`.

**To Reproduce**
1. Go to https://niivue.github.io/niivue/features/draw.ui.html
2. Make a drawing
3. Click on File -> Save Drawing
4. Check the saved file's contents

**Expected behavior**
The saved file should include the image data.

**Comment by nefelibetas** [comment]
I also encountered this problem.

**Comment by neurolabusc** [comment]
Fixed in main branch today.
