### ISSUE TITLE
Mac Sign and Build App

### ISSUE THREAD

**Issue by rnorlund** [niivue/niivue#536]
Is there a command to build and sign an app/release, I noticed there wasn't one in the package.json shortcuts.
Might be nice to include one if such a build is possible at this stage.

**Comment by neurolabusc** [comment]
For electron-based Windows, Linux and Mac apple, you will want to use [niivue-desktop](https://github.com/niivue/niivue-desktop). The home page describes how to build an executable:

```bash
git clone --recurse-submodules git@github.com:niivue/niivue-desktop.git
cd niivue-desktop
npm install
npm run package
```

To share a MacOS version you will want to [notarize](https://www.electronjs.org/docs/latest/tutorial/code-signing) your App or use [Electron Builder](https://www.electron.build/code-signing).

For IOS and Android, [visit niivue-ipad](https://github.com/niivue/niivue-ipad).

**Comment by hanayik** [comment]
You don’t need to use electron builder. If you have apple developer credentials you can use them with the electron forge package which is already part of NiiVue desktop. You’ll just need to set this up for your account specifically. Don’t commit a signing config to the repo.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
