### ISSUE TITLE
canvas focus on init causes page to jump to niivue canvas when embedded in other GUIs

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#543]
@neurolabusc , and @cdrake , 

Do you remember why we need to focus the canvas when we initialise NiiVue?

https://github.com/niivue/niivue/blob/main/src/niivue.js#L1306

I'm inclined to remove this focus call during the init/register interactions to fix the page jumping behaviour when using NiiVue in other GUIs (like the FSL GUIs). 

Let me know what you guys think.

**Comment by neurolabusc** [comment]
I agree it should not be the default behavior to capture focus.
