### ISSUE TITLE
Issue with loading a file from a backend endpoint with React

### ISSUE THREAD

**Issue by martinkulka** [niivue/niivue#547]
Hello,

I am using this amazing library in my bachelor's thesis for my web-based medical application. I wanted to thank you first that this library is being made and actively developed.

Edit:
Today i tried to create a FastAPI backend for this application, and i still cannot get the library to display the files it receives. 
This is what i get when i pass the URL to the file on the backend: 

![image](https://user-images.githubusercontent.com/55322841/226124656-8d3900cd-792f-47e0-a531-d434b4087a5c.png)

FINAL EDIT: I found out what the issue was. I guess i was incorrectly setting the endpoint name? I named my endpoint this: 
`http://127.0.0.1:8000/api/input_file`. The issue was, when i proceeded to put this URL into `loadVolumes()`, when creating NVImage, it couldn't extract the name of the file and neither the .nii.gz file suffix. It then proceeded to use readDICOM instead of the NIFTI parser function on the file, hence the error above. I needed to rename my endpoint like so: `http://127.0.0.1:8000/api/input_file.nii.gz`, and my app works perfectly now.

This probably isn't an issue with the library, rather a problem with my knowledge of HTTP requests and how to correctly set them up for file downloading. I apologize.

**Comment by hanayik** [comment]
@martinkulka , no worries! glad it's working now. Just to note, you could also use your original endpoint name (without the .nii.gz extension) if you also supplied the name of the file to load (even it was "placeholder.nii.gz"). 

The specific area in the [code is in nvimage.js](https://github.com/niivue/niivue/blob/main/src/nvimage.js#L2723). If the name isn't supplied, we try to infer the extension from the URL, but if the name _is_ supplied it overrides whatever is (or is not) in the URL.
