### ISSUE TITLE
An error occurred when using react. The file is not a NIFTI file

### ISSUE THREAD

**Issue by huiaixing** [niivue/niivue#549]
Hello，I am using this library for my graduation thesis. It is very powerful. Thank you.
But I got two bugs when I used it in react.
First is  "**That file does not appear to be NIFTI!(devScripts.js:6523)**"
And another is  "**Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cal_min')  (niivue.es.js:107941)**"
I loaded this NII file from a local folder，so I am sure the path and format of the file are correct.
Could you help me see what's going on here？

![image](https://user-images.githubusercontent.com/80866450/227706618-4174caf9-7cd5-41dc-9804-ea8770726ffa.png)

code：
![image](https://user-images.githubusercontent.com/80866450/227706974-664e0fc7-f71b-4e44-a9fb-a86842fbeb27.png)
![Uploading image.png…]()

**Comment by hanayik** [comment]
@huiaixing, could you please provide an example of what the url looks like that you are passing in as a prop? Also, it might be useful to share the file you are trying to load (if it is shareable data). Could you also share the version of NiiVue that you are using? Should be in your package.json file.

**Comment by huiaixing** [comment]
@hanayik  
this is the url
![image](https://user-images.githubusercontent.com/80866450/227711867-1ebcaaf5-0386-44ac-9622-8e8ec77a238d.png)

niivue version is 0.32.0
![image](https://user-images.githubusercontent.com/80866450/227711714-ea3e0911-fe53-4422-b592-93b17960f9ca.png)

this is the nii file(I compressed this nii file because github does not support uploading the nii file)
[nii-File.zip](https://github.com/niivue/niivue/files/11068650/nii-File.zip)

**Comment by neurolabusc** [comment]
@huiaixing are you testing us the Windows operating system? I would suggest that you re-test with [NiiVue 0.33.1](https://www.npmjs.com/package/@niivue/niivue) which avoids a bug in the [ANGLE](https://bugs.chromium.org/p/angleproject/issues/detail?id=8085) DirectX implementation.

**Comment by neurolabusc** [comment]
@huiaixing NiiVue does support loading NIfTI files compressed with GZip format using the extension `.nii.gz`. While optional, for slow internet connections, this will accelerate file transfer. If you have a file that will be cmpressed once and decompressed many times, it may be worth the time to use an aggressive compression level (the -11 enables `zopfli` which is very slow to compress but creates very small files considering they are GZip compatible):

```
 pigz -n -11 18.nii
```

**Comment by huiaixing** [comment]
@neurolabusc   yes I am using the Windows operating system. Now I have upgraded Niivue to 0.33.1. But my project couldn't start. An error is displayed like this.
![image](https://user-images.githubusercontent.com/80866450/227713991-30e05142-e328-4491-ad2d-f8a1d7db6b39.png)

**Comment by hanayik** [comment]
@huiaixing, could you provide instructions and/or a minimal example GitHub repo with minimal code illustrating the problem so that I can try to replicate?

**Comment by hanayik** [comment]
@huiaixing , we have not been able to replicate this without a minimal example. Are you able to provide one? In the meantime, we have decided to create and publish vue, react, and angular minimal demos that show how NiiVue can be used in these frameworks. We can link those demo repos to this issue once completed. Hope that might be able to help!

**Comment by huiaixing** [comment]
@hanayik I am using typscript , when I import this nii file , I got two errors  are “ Cannot find module '@/assets/18. nii' or its corresponding type declaration ” and " Cannot find module '@ nivue/nivue' or its corresponding type declaration ",
I'm trying to declare a type in typing.d.ts, but it still not working.I have provided a minimal example. Coudle you help me see how to solve this problem?
![image](https://user-images.githubusercontent.com/80866450/229271003-4ebc65af-57f3-4fd4-ba6f-5af5e0841ca3.png)
![image](https://user-images.githubusercontent.com/80866450/229271152-fd007b64-cc39-4453-97cc-d4b86bc3b418.png)
[niivue.zip](https://github.com/niivue/niivue/files/11128684/niivue.zip)

**Comment by huiaixing** [comment]
@hanayik  hi I have solved this problem through ‘file-loader’. Thank you for your reply. This question can be closed now.

**Comment by neurolabusc** [comment]
@huiaixing would you mind sharing your working demo and would you be happy to have it publicly shared under the [BSD 2-Clause license](https://github.com/niivue/niivue/blob/main/LICENSE)? It would be nice to have a type-script based react demo.

**Comment by huiaixing** [comment]
@neurolabusc  Hi I uploaded my demo here in a compressed package, The types of NII and NIIVUE need to be declared in typings.d.ts file and need to load the file-loader to import the NII file in .umirc.ts file. The rest of the code is the officially provided react version of the code。
[reactTsNiivueDemo.zip](https://github.com/niivue/niivue/files/11131405/reactTsNiivueDemo.zip)
