### ISSUE TITLE
if cal_min and cal_max set, then don't waste time running calMinMax

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#55]
in order to speed up loading, If cal_min, and cal_max are set then trust that the user (And the image creator) want to use those values. If cal_min/max are not set (zero) then run `calMinMax` as normal. 

@neurolabusc , what do you think of this strategy? It we'd need to workout what to do with global_min and global_max, but perhaps they could be set to cal_min and cal_max if cal_min/max > 0?

**Comment by neurolabusc** [comment]
Sounds like a good strategy. I would suggest the conditional `if (isfinite(cal_max)) && (isfinite(cal_min)) && (cal_max > cal_min))`, where isfinite returns false for NaN, -Inf, +Inf.

**Comment by hanayik** [comment]
done. https://github.com/niivue/niivue/commit/c007cb8a7b9aef139a954e7ffc3ec18d1acea944

Also added a new property to the niivue options: 

`trustCalMinMax: boolean //default is true, but if cal_min/max not set then calulate anyways. False means always distrust`
