### ISSUE TITLE
adding cmaps

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#551]
@hanayik:

I have started a PR (https://github.com/niivue/niivue/pull/550) to add some new cmaps that are used in AFNI, which will facilitate the APQC HTML integration for NiiVue.  I started with a pretty simple ROI-based one (basing it on the existing cmaps/random.json), but would like to add a couple others.  I have a few questions for other colorbars:

1. Why are most "A" values (except the [0]th) 64? 

2.  If I add an ROI map with 512 colors, should I simply extend the current format:
```
{
  "min": 0,
  "max": 512,
  "R": [ 
   ...],
  "G": [ 
   ...],
  "B": [ 
   ...],
  "A": [ 
   ...],
  "I": [ 
    0, ..., 511
  ]
}
```
?  And would the same apply for a cmap with <256 colors?

3. I started using simply the AFNI cmap names with `.json` appended for the filenames, but these have capitalization in them, generally;  the current niivue/src/cmaps/*json do not.  Should I lower the capitalization of the AFNI cmap names?

4. The continuous cmaps in AFNI are generally still defined as a list of 256 values, whereas the NiiVue continuous colormaps are defined with a more Python/interpolation style.  Should I approximate the AFNI continuous colormaps in the Pythonic style, or could those lists of 256 values be used within NiiVue?

**Comment by mrneont** [comment]
@neurolabusc : thanks for the explication of these several points.

Re. the existing "continuous" colorbars with 256 values/nodes, I will just use those for now, for simplicity and directness. Those can always be adjusted in the future with convenient approximations.

Re. the A values:  That is good to know.  The ROI_i256.json file I started with is typically meant for ROI map/atlas coloring, so I followed the analogous freesurfer.json A values (choosing the first one to be 0 and the rest 64).  For something like a continuous colormap with 256 colors, would you recommend that the A values have some gradation?  I guess
https://github.com/niivue/niivue/blob/main/src/cmaps/blue2red.json
is meant to be "two-sided" (like going from -X to X), and https://github.com/niivue/niivue/blob/main/src/cmaps/redyell.json is meant "one-sided" (like going from 0 to X).  I'm aiming to add colorbars that would be used for effect estimate display.

**Comment by neurolabusc** [comment]
- With regards to gradations, why not try out MRIcroGL to interactively set the alpha level. You can interactively drag the nodes to adjust your colormap, and then option-click on the color map to save it to disk.
 - For two-sided statistical thresholds, you should create two separate colormaps. The blue2red is designed as a one-sided colormap, just trying to add hue to increase salience. See [this live demo](https://niivue.github.io/niivue/features/alphathreshold.html) of two-tailed statistics that uses the warm and winter color maps:

```
          colorMap: "warm",
          colorMapNegative: "winter",
```

**Comment by neurolabusc** [comment]
@mrneont a lot of the [AFNI colormaps are interpolated from a few nodes](https://github.com/afni/afni/blob/25e77d564f2c67ff480fa99a7b8e48ec2d9a89fc/src/display.c#L1880) - so you can use the 
```
define NPANE_BIG    256
```
with nodes NBIG_MBOT and NPB_2 for various color maps to have a direct mapping from AFNI to node-based NiiVue.

**Comment by mrneont** [comment]
@neurolabusc : 

Both excellent suggestions.  I could indeed make the separate halves of Reds_and_Blues_Inv using just a pair of min/max RGBA values each.  Thanks for showing me something new about AFNI today!

**Comment by shangjiaxuan** [comment]
It would also be quite nice if one could add cmap files at runtime. Currently NiiVue colormap events only accepts existing color tag strings.

**Comment by shangjiaxuan** [comment]
NiiVue currently cannot load colormap at runtime, and can only load preset files. It would be nice if one could specify a json payload or url as colormap?
