### ISSUE TITLE
how to set opacity of overlay volume?

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#558]
How would I set an overlay volume to be semi-transparent?

I tried each of these:
```
nvobj.volumes[1].setDrawOpacity(0.1);  
```
and 
```
nvobj.volumes[1].opacity = 0.1;
```
... but neither appeared to have any effect, even though the opacity value is quite low.

The `nvobj` is a NiiVue instance started as:
```
const nvobj = new niivue.Niivue(
      { logging:true, 
        show3Dcrosshair: true }
    )
```
... and I have 3 volumes loaded (underlay, overlay and threshold volume).  

Thanks.

**Comment by hanayik** [comment]
@mrneont , try `nvobj.setOpacity(vol_idx, new_opacity)`

for example: ` nvobj.setOpacity(1, 0.1)`

**Comment by mrneont** [comment]
Hi, @hanayik : 

Thanks, that does work, as long as I don't have 
```
nvobj.volumes[1].alphaThreshold = true; 
```
also set.  In that case, I guess the suprathreshold locations always have opacity=1, rather than opacity=MAX_OPA, which could be set to be <1 (which is what would happen in AFNI).  Is that the case?

That might still be fine in most cases.  For lowering opacity, I was just trying to get familiar with it in the current stats/alphaThreshold case, but I will mostly use it when it comes time to check EPI-anatomical alignment, so having a simple overlay and underlay case (no alphaThreshold being turned true).

thanks,
pt

**Comment by neurolabusc** [comment]
@mrneont can we close this case? The `alphaThreshold` is a special case where opacity is over ridden by voxel intensity. It is the expected behavior.

**Comment by mrneont** [comment]
Sure, that is fine.  In the future, I guess it might be worth considering whether the max opacity in alphaThresholding could be less than unity, which might be useful for cases when the suprathreshold regions are large.  For now, it should be fine, thanks.
