### ISSUE TITLE
report crosshair coordinates?

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#559]
Howdy-

Is there a function/setting to display the (x,y,z) coordinates of crosshair location, so the user knows where they are looking in the brain?  I browsed a bit, but did not see one.

Thanks,
pt

**Comment by hanayik** [comment]
@mrneont , 

You will need to supply an `onLocationChange` callback function like this:

```
function locationChangeHandler(data) {
    console.log(data);
    // or get an element in the html document and display the data.string
   // there are also other properties on the data object
   // https://github.com/niivue/niivue/blob/main/src/niivue.js#L7379
}
const nvobj = new niivue.Niivue(
  {
     logging:true, 
     show3Dcrosshair: true,
     onLocationChange: locationChangeHandler
  }
)
```

one of the live demos shows this as well: https://github.com/niivue/niivue/blob/main/demos/features/basic.multiplanar.html#L36

**Comment by mrneont** [comment]
Thanks, I have this working now.  I was trying to find where 'data.string' was created---I like that information, but would like to change the formatting of the coordinates and intensity values.  I haven't been able to backtrack it, though (even trying to search for the unicode \times symbol).

**Comment by hanayik** [comment]
@mrneont, 

the line in niivue is here:
https://github.com/niivue/niivue/blob/main/src/niivue.js#L7352

the `data` object that is returned has the properties:
```
data = {
  mm, // mm coords 
  axCorSag, // slice
  vox, // voxel location 
  frac, // clip space
  xy, // mouse xy
  values, //  voxel values for all loaded volumes
  string // location coords as string
}
```

We can prob document this better to help make it more clear in the docs :). Thanks for pointing it out! I think others would find it helpful to know what's returned.

**Comment by neurolabusc** [comment]
@mrneont the string is generated by [createOnLocationChange()](https://github.com/niivue/niivue/blob/77f941cb260bdcd8e16cb403b37e9f729dec36ca/src/niivue.js#L7339).  However, if you do not like the formatting of the string, you can always apply your preferred formatting: 

```
function handleLocationChange(data){ 
  document.getElementById('location').innerHTML = 'voxel location: ' + data.vox + ' ' + data.values[0].value
}
```

**Comment by mrneont** [comment]
Thanks, that is useful.

Maybe I will mention what I want to do explicitly, and how I have started clunkily doing this for suggestions of a better way to go.  I would like to report the (x,y,z) coords and values of the underlay, overlay and threshold volumes.  I am aiming for this format of text string:
```
xyz:[0.5L, 21.5A, 16.5S], UOT:[123, -4.321, 7.890]
```
So, my first approximation to this is including this function in my HTML directly:
```
  function reportCoorAndValues(data) {
    //document.getElementById("intensity").innerHTML = "&nbsp;&nbsp;" + data.string;
    document.getElementById('intensity').innerHTML = 'xyz:[' + data.mm[0] + ', ' + data.mm[1] + ', '+ data.mm[2] +'], UOT:[' + data.values[0].value + ', ' + data.values[1].value + ', ' + data.values[2].value + ']' 
      console.log(data.string);
  }
```
... which gets the numbers in the right spot, but with faaaar too many decimal points, and without converting the signed coordinate values to more useful coordinate magnitude-with-letter format. 
+ For the decimal question, how should I best include the `dynamicDecimals()` functionality, without duplicating a lot of code?
+ For the coordinate magnitude-with-letter format, I believe NiiVue always works in a frame where left/posterior/inferior are all negative valued, is that correct?  Therefore, I would like to do the following, for a given (X, Y, Z) coordinate triple, for each of the coords (where this is a kind of psudocode):
```
let xmag = str(abs(X))
let xlet = (X<0) : 'L' ? 'R'
let xfinal = xmag + xlet
```
Does that make sense?  Should I do those pieces within NiiVue src, or just within the HTML?

**Comment by neurolabusc** [comment]
@mrneont you can also have your wrapper generate a location change event. This is useful for showing information when you load a new image.

```
nv1.createOnLocationChange();
```

**Comment by neurolabusc** [comment]
@mrneont here are two functions for converting numbers to a string with a fixed string with a limited number of digits. The difference is that the second function retains the trailing zeros:

```
// node flt2str.mjs 
async function main() {
  function flt2str(flt, decimals = 0) {
    //return parseFloat(flt.toFixed(decimals)); //return number
    return parseFloat(flt.toFixed(decimals))+""; //return string
  }
  let val = 0.251;
  console.log('flt2str type ', typeof flt2str(val));
  console.log('flt2str(val,0): ', flt2str(val, 0));
  console.log('flt2str(val,1): ', flt2str(val, 1));
  console.log('flt2str(val,2): ', flt2str(val, 2));
  console.log('flt2str(val,3): ', flt2str(val, 3));
  console.log('flt2str(val,4): ', flt2str(val, 4));
  function flt2str0(flt, decimals = 0) {
    //retain trailing zero
    return flt.toFixed(decimals); //return string
  }
  console.log('flt2str0 type ', typeof flt2str0(val));
  console.log('flt2str0(val,0): ', flt2str0(val, 0));
  console.log('flt2str0(val,1): ', flt2str0(val, 1));
  console.log('flt2str0(val,2): ', flt2str0(val, 2));
  console.log('flt2str0(val,3): ', flt2str0(val, 3));
  console.log('flt2str0(val,4): ', flt2str0(val, 4));
}
main().then(() => console.log('Done'))
```

You can observe the behavior by running this script from the command line:

```bash
$ node flt2str.mjs
flt2str type  string
flt2str(val,0):  0
flt2str(val,1):  0.3
flt2str(val,2):  0.25
flt2str(val,3):  0.251
flt2str(val,4):  0.251
flt2str0 type  string
flt2str0(val,0):  0
flt2str0(val,1):  0.3
flt2str0(val,2):  0.25
flt2str0(val,3):  0.251
flt2str0(val,4):  0.2510
Done
```

**Comment by mrneont** [comment]
Great, thanks, that is working for me.  

And for reporting the directionality of coords, I wrote a function to take coords where L/P/I are neg (and R/A/S are pos) and use the signum information to report the coordinate with the appropriate letter instead of the sign:
```
/* more string formatting numbers, below ... WITH directionality here,
   assuming the coords are what AFNI calls LPI (and what some other
   software call RAS); basically, L/P/I are neg coords, and R/A/S are
   positive.  
*/
function flt2str0_dir(flt, ndec = 0, dir = '' ) {
    //retain trailing zero
    if ( dir == '' ) {
      return flt.toFixed(ndec); //return string
    } else if ( dir == 'RL' ) {
      let aflt = Math.abs(flt);
      let lab  = (flt < 0 ) ? 'L' : 'R';
      return aflt.toFixed(ndec) + lab;
    } else if ( dir == 'AP' ) {
      let aflt = Math.abs(flt);
      let lab  = (flt < 0 ) ? 'P' : 'A';
      return aflt.toFixed(ndec) + lab;
    } else if ( dir == 'IS' ) {
      let aflt = Math.abs(flt);
      let lab  = (flt < 0 ) ? 'I' : 'S';
      return aflt.toFixed(ndec) + lab;
    } else {
      return ''; 
    }
}
```
... and then when using that:
```
      let str_c = '&nbspxyz:[' + 
                  flt2str0_dir(data.mm[0], 3, 'RL') + ', ' +
                  flt2str0_dir(data.mm[1], 3, 'AP') + ', ' +
                  flt2str0_dir(data.mm[2], 3, 'IS') + '], '

```
