### ISSUE TITLE
implement 2D slice zooming feature

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#56]
this feature would enable users to zoom in on 2D slices.

We already devote mouse wheel events to slice scrolling in 2D view modes. So, in order to add slice zooming as well, I propose that we implement a "z + scroll" event handler. 

We would update the zoom level under the following conditions:

- "z" is pressed down
- mouse wheel event
- sliceType != sliceTypeRender

**Comment by neurolabusc** [comment]
- Should the center of expansion be the location of the cross-hairs or the center of the 2D slice? 
 - This feature probably also requires a way to pan the 2D image. 

Both FSLeyes and MRIcroGL show implementations for slice zooming and panning. We do want to think carefully if there are good gestures for tablets and phones.

**Comment by hanayik** [comment]
@neurolabusc:

- I think the zoom should center on the crosshair
- panning: see #57

Good point about mobile gestures. My opinion on this:

- zoom: two finger pinch
- pan: two finger touch and drag
