### ISSUE TITLE
Duplicates in documentation

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/niivue#561]
I noticed that some classes in the documentation are duplicated:
<img width="352" alt="Screen Shot 2023-03-30 at 6 02 00 PM" src="https://user-images.githubusercontent.com/43938491/228974117-b3c19952-6069-4e96-b27d-c3e5e052195e.png">

**Comment by hanayik** [comment]
@AnthonyAndroulakis, thanks for pointing this out. I will work on cleaning up the docs and fixing this.
