### ISSUE TITLE
reporting data values during onLocaitonChange event does not use frame4D

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#569]
When retrieving data values from the onLocationChange data object we are only reporting the first volume info. NVImage.getValue allows us to pass in frame4D as well. 

Suggested fix: update the data object returned from https://github.com/niivue/niivue/blob/main/src/niivue.js#L7405 to report the voxel values for each layer given its current frame4D value. (suggested by @mrneont ).

**Comment by mrneont** [comment]
Yes, that does solve the issue, thanks.
