### ISSUE TITLE
Catch is resistFingerprinting is set

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#582]
The Mozilla FireFox browser will block NiiVue if `privacy.resistFingerprinting` is set to true, as these lines that attempt to detect details regarding the graphics capabilities are considered a privacy issue:

```
let vendor = this.gl.getParameter(rendererInfo.UNMASKED_VENDOR_WEBGL);
let renderer = this.gl.getParameter(rendererInfo.UNMASKED_RENDERER_WEBGL);
```

To replicate, enable this feature: 
1. Type `about:config` in the address bar and press Enter. A warning page may appear. Click Accept the Risk and Continue to go to the `about:config` page.
2. Search for privacy.resistFingerprinting and set it to `true`.

**Comment by effigies** [comment]
Thank you for creating this, and apologies for not creating an issue first. Will read the contributing guide better next time.
