### ISSUE TITLE
area and angle measurement

### ISSUE THREAD

**Issue by johnren-code** [niivue/niivue#595]
Hello, I would like to know if NIIVUE currently supports dragging for angle or area calculation, as shown below：
![image](https://github.com/niivue/niivue/assets/76835772/8372c816-d97b-400b-86ae-8b46cd9bf21c)
Looking forward to your reply!

**Comment by neurolabusc** [comment]
The [drawing live demo](https://niivue.github.io/niivue/features/draw.ui.html) illustrates how you can set the mouse drag-mode to measure distances. You can also get descriptive values when you draw a region of interest. I think the area, circle and rectangle tools could all be added without much code, but I would have thought that drawing would provide much more precision for real world uses. Further, it is unclear what the user interface gestures would be for these different tools across mouse, touch and pen inputs. 

![nv](https://github.com/niivue/niivue/assets/8930807/1af4b615-d82b-4440-bf36-0444ec0b0096)

**Comment by johnren-code** [comment]
OK, I got it!
Another question, is there a way to make the labels displayed by the `loadDrawingFromUrl` clearer? Like ITK-SNAP
Here is yours:
![image](https://github.com/niivue/niivue/assets/76835772/3aed639f-b187-4136-9c51-5b8bccb09289)
Here is ITK-SNAP:
![image](https://github.com/niivue/niivue/assets/76835772/503d26e2-c751-4fe5-bf9a-ba9e5b7197b1)

**Comment by neurolabusc** [comment]
I do not understand the question. The NiiVue image is showing a 2D slice, where each region has a discrete color. The lower ITK-SNAP image shows a 3D rendering of the object. Have you tried looking at a 3D rendering view in NiiVue (e.g. by pressing the 'v' key on a keyboard to cycle view styles).

I do think that ITK-SNAP is applying lighting based on gradients. In the future, we could do this - for example the fore-runner to NiiVue was [MRIcroWeb](https://rordenlab.github.io/) which included matcap-based volume rendering. It something we could easily add. However, these methods require a lot more graphics card resources, so we will need to think about how to allow this as an option to ensure we still have good performance on inexpensive devices.

**Comment by johnren-code** [comment]
Actually, niivue seems to be able to achieve this effect at present, using the function `nv.loadVolumes(this.volumeList) `as shown below(without added color):
![image](https://github.com/niivue/niivue/assets/76835772/5ce9c2d6-0854-443f-b015-0edacad52643)
Therefore, I would like to know if `loadDrawingFromUrl` can also achieve this more three-dimensional and intuitive effect by adding certain attributes.

**Comment by johnren-code** [comment]
I want to make modifications to the label, therefore, I want to use `loadDrawingFromUrl` instead of `loadVolumes` to show the label.

**Comment by neurolabusc** [comment]
NiiVue expects you to create a drawing on a voxel based background image.  You can always load the drawing as both your drawing and the background image. Here is a minimal example that you can use to replace your /niivue/src/index.html and then simply run `npm run dev`. I would also turn off interpolation as your drawing is a categorical rather than continuous image (this demo includes a `smooth` checkbox so you can see the influence of this choice):

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>NiiVue</title>
    <link rel="stylesheet" href="niivue.css" />
    <link rel="icon" href="data:;base64,iVBORw0KGgo=" />
  </head>
  <body>
    <noscript>
      <strong>niivue requires JavaScript.</strong>
    </noscript>
    <header>
      <label for="check1">Smooth</label>
      <input type="checkbox" id="check1" unchecked />
    </header>
    <main>
      <canvas id="gl1"></canvas>
    </main>
    <footer id="location">&nbsp;</footer>
    <script type="module" async>
      import { Niivue } from "./niivue.js";
      import { NVImage } from "./nvimage.js";
      import { NVMesh } from "./nvmesh.js";
      document
        .getElementById("check1")
        .addEventListener("change", doCheckClick);
      function doCheckClick() {
        nv1.setInterpolation(!this.checked);
      }
      var volumeList1 = [
        { url: "../demos/images/lesion.nii.gz", limitFrames4D: 3 },
      ];
      function handleLocationChange(data) {
        document.getElementById("location").innerHTML =
          "&nbsp;&nbsp;" + data.string;
      }
      let defaults = {
        show3Dcrosshair: true,
        onLocationChange: handleLocationChange,
      };
      var nv1 = new Niivue(defaults);
      nv1.setInterpolation(true);
      nv1.setRadiologicalConvention(false);
      nv1.attachTo("gl1");
      nv1.opts.multiplanarForceRender = true;
      await nv1.loadVolumes(volumeList1);
      await nv1.loadDrawingFromUrl("../demos/images/lesion.nii.gz");
    </script>
  </body>
</html>
```


![nvx](https://github.com/niivue/niivue/assets/8930807/1d69ddfa-a594-4602-99bc-9dd7b5c48235)

**Comment by neurolabusc** [comment]
I believe my comment closes this issue. Please open a new issue if you need additional advice.
