### ISSUE TITLE
drawSelectionBox erases the canvas

### ISSUE THREAD

**Issue by haehn** [niivue/niivue#596]
I am doing `nv.drawSelectionBox([50,50,100,100])` and the canvas/viewport turns black. What am I doing wrong?

Also, I would like to allow the user to select a ROI-box similar to the contrast-drag. What is the best way of doing this?

**Comment by neurolabusc** [comment]
@haehn I have added experimental support for you. This should get you up and running, but the eventual API may change. You will want to download the `drawing` branch and then `npm run dev` to try a live demo. Note that this experimental version allows you to create a callback named `onContrastDragRelease()`. If this is set, the contrast-drag works as before until the user releases the drag, at which case the drag information is returned to your function. As demonstrated in my demo, this only intercepts the function of the `contrast` drag mode: the other drag modes work as before. The function returns the 3D fractional texture space for the start and end of the drag, so it will work on sagittal, coronal and axial slices. A fractional location of [-1, -1, -1] suggests the user dragged off the boundary of the texture.

**Comment by haehn** [comment]
Super thank you
