### ISSUE TITLE
Zooming with clip plane enabled

### ISSUE THREAD

**Issue by IsaacCrane** [niivue/niivue#599]
With the clip plane displayed there is no obvious way to zoom in and out since the clip plane's position takes scrolling as an input. Is there a way to zoom in and out with the clip plane enabled?

**Comment by neurolabusc** [comment]
I agree that we need a good way to allow this on all devices (phone: touch, tablet: pencil, computer: keyboard/mouse). At the moment, for a computer you can use the 'c' key to disable the clip plane and then set the desired zoom, and then use the 'c' key to enable a clip plane that you can adjust. The feature would be easy to add in code, but I think we need a good suggestion for the right way to implement this intuitively.

**Comment by IsaacCrane** [comment]
The site that I am making involves the user changing the things that are displayed frequently. Is there a way to store the present zoom information so that every time the user tries to zoom in, then change something about the scene, the zoom is kept the same? Thanks so much for your help.

**Comment by neurolabusc** [comment]
I am not sure I understand or can replicate the issue. The zoom properties and other features should be persistent across users actions. Take a look at [this demo](https://niivue.github.io/niivue/features/draw.ui.html) where you can zoom the 3D and 2D slices, pane the 2D slices and draw on slices with setting being persistent across user actions.


Note that you can read and write the render zooming function, so you can always add a UI element to control this feature. Call "drawScene" to instigate a screen refresh (NiiVue preserves batteries by only updating when required):

```JavaScript
nv1.scene.volScaleMultiplier = 2.0;
nv1.drawScene();
```

**Comment by IsaacCrane** [comment]
This is perfect. The problem isn't with Niivue but that I am calling Niivue multiple times. The scale multiplier is the code I was looking for. Thanks

**Comment by neurolabusc** [comment]
Assuming you are working on [this project](https://nrdg.github.io/hbn_viewer/), note that when you load a new background image (in your project: changing the participant or scan type) NiiVue will automatically recalculate the bounding box, zoom and intensity settings. This is generally helpful, as you may have an volumes that have very different spatial extents or image intensities. If this is information you want to retain, you can always read this before opening a new background and write it after loading a new volume (just make sure to use `await` when opening your new volume).

By the way, for this [code](https://github.com/nrdg/hbn_viewer/blob/5554dc527c9a76fd803ae38417b279fba4f963a4/callNiivue.js#LL11C9-L11C32), creating and attaching NiiVue instances is computationally costly:

```JavaScript
   var nv1 = new niivue.Niivue(({
  		show3Dcrosshair: true,//displays crosshair
  		backColor: [1, 1, 1, 1]}))//sets the background color.
  nv1.setSliceType(nv1.sliceTypeRender)//all three directions of slices are displayed
  nv1.attachTo('gl1')
```

I would only create a new and attach a NiiVue instance once when the page opens. Subsequently you can simply bind a new background image:

```JavaScript
volumeList1[0].url = img;
nv1.loadVolumes(volumeList1);
nv1.updateGLVolume();
```

Here is a [live demo](https://niivue.github.io/niivue/features/test_images.html) demonstrating this technique.
