### ISSUE TITLE
How does niivue perform measurement functions, similar to punctuation in OHIF, and then measure in millimeters

### ISSUE THREAD

**Issue by rookiefishs** [niivue/niivue#604]
![image](https://github.com/niivue/niivue/assets/103868319/b4dc5197-b23e-44ac-b1b6-cd546831fa56)

We are a software development team from China and have encountered some issues recently when using the nivue library, such as the lack of measurement APIs in the nivue library and the inability to dynamically generate some tag information in the view through existing data. We hope to receive a response from the nivue development team!

**Comment by hanayik** [comment]
Hi, NiiVue supports measurement via a right click and drag. You can see a demo [here](https://niivue.github.io/niivue/features/draw.ui.html) by selecting measurement from the drag menu.

**Comment by rookiefishs** [comment]
> 您好，NiiVue支持通过右键单击和拖动进行测量。[您可以在此处](https://niivue.github.io/niivue/features/draw.ui.html)通过从拖动菜单中选择测量量来查看显示。

感谢回复,但是我有一个问题,就是在使用loadMeshes API的时候我需要加载一个jcon文件,是否可以不加载文件,直接填入jcon文件内部的数据呢,因为我可以直接获取到数据,并且这个数据是实时更新的,所以可以在视图中实时的修改,如果必须要使用文件引入的话,那么就可能造成较大的负担

**Comment by rookiefishs** [comment]
> 您好，NiiVue支持通过右键单击和拖动进行测量。[您可以在此处](https://niivue.github.io/niivue/features/draw.ui.html)通过从拖动菜单中选择测量量来查看显示。

Thank you for your reply, but I have a question. When using the loadMeshes API, I need to load a jcon file. Can I simply fill in the data in the jcon file without loading the file? Because I can directly obtain the data and the data is updated in real-time, it can be modified in real-time in the video. If it is necessary to use a file to import, it may cause greater burden

**Comment by rookiefishs** [comment]
Thank you for your reply, but I have a question. When using the loadMeshes API, I need to load a jcon file. I hope to not load this file and fill in the data directly because I can directly obtain the data and the data is updated in real-time, so it can be modified in real-time in the view. If a file must be used for loading, it may cause greater burden

**Comment by rookiefishs** [comment]
> Hello, NiiVue supports measuring by right-clicking and dragging. You can select Measure from the drag menu to（ https://niivue.github.io/niivue/features/draw.ui.html ）View the presentation.

I saw the corresponding function, but I couldn't find the callback function after the measurement was completed, which prevented me from completing my requirements. I hope you can provide me with some help
