### ISSUE TITLE
add more comments to explain niivue code base to other devs

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#606]
Now that NiiVue is being use by other groups, it is a good time to make sure the code base is commented well so that others can use and understand the code easily.

Perhaps this is a good task for an AI bot....

**Comment by hanayik** [comment]
Also, as part of this work, maybe work on breaking larger functions into smaller, bite-sized pieces.

**Comment by rookiefishs** [comment]
I think some updates can be made to the document, as some APIs cannot be obtained and the classification is somewhat messy. This is my personal suggestion

**Comment by ziyupianxian** [comment]
I'd like to see more official documentation and tutorials, API principles and instructions, and more API interfaces and features. Hope Niivue gets better and better!
