### ISSUE TITLE
NVController.js cases

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/niivue#610]
In https://github.com/niivue/niivue/blob/main/src/nvcontroller.js there are cases for `NVMESSAGE.MESH_SHADER_CHANGED` and `NVMESSAGE.COLORMAP_CHANGED`. However, these properties (MESH_SHADER_CHANGED and COLORMAP_CHANGED) do not exist on the NVMESSAGE object.

I assume these were renamed at some point like so:
MESH_SHADER_CHANGED -> SHADER_CHANGED
COLORMAP_CHANGED -> COLOR_MAP_CHANGED

**Comment by neurolabusc** [comment]
Well spotted. @hanayik I think we should use the messages `SHADER_CHANGED` and `COLORMAP_CHANGED` - e.g. [colormap is a single word, not two](https://github.com/niivue/niivue/issues/602). If you agree, I can make the changes to resolve this issue.

**Comment by hanayik** [comment]
@neurolabusc, agreed! I can merge in once you’re happy with your current PR. There were some failing tests, so I’m waiting on the most recent GitHub actions to finish and then I will investigate any test failures if they persist.

**Comment by neurolabusc** [comment]
@hanayik I have added this fix to my PR. I suggest merging my PR and then fixing the failing tests.
