### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/niivue#612]
While reading https://raw.githubusercontent.com/niivue/niivue/main/src/nvimage.js, in NVImage.prototype.readMHA, I saw
```js
    if (items.length > 2);
    items = items.slice(2);
```
I think this should be 
```js
    if (items.length > 2)
        items = items.slice(2);
```

**Comment by neurolabusc** [comment]
Thanks, fixed in current PR.
