### ISSUE TITLE
FreeSurfer Color map

### ISSUE THREAD

**Issue by hiksa** [niivue/niivue#613]
We would like to use the [FreeSurfer lookup table](https://github.com/mwaskom/PyROI/blob/master/data/Freesurfer/FreeSurferColorLUT.txt) a longside a volume created by FreeSurfer. The format of said lookup table is different than the one that niivue supports so we've converted it. We are loading a volume that contains automated segmentation labels produced by FreeSurfer and loading the converted colormap by calling setDrawColormap(cmap) on a niivue instance.

After following the steps described above, no observable changes can be seen in the rendering of the volume. 

We used [this demo](https://niivue.github.io/niivue/features/freesurfer.html) for guidance. After running the demo locally and commenting out the code that loads the color map in it we didn't see a change in the rendering of the images, which leads us to think that there may be a problem with color maps containing labels.

Any help or guidance would be appreciated :)

**Comment by neurolabusc** [comment]
@hiksa why don't you add your [new colormap to this live demo](https://niivue.github.io/niivue/features/draw.ui.html) which already has a custom colormap. This will help you resolve what the issue is. Feel free to upload your json or send it to my email for further feedback.

**Comment by neurolabusc** [comment]
@hiksa please see [PR621](https://github.com/niivue/niivue/pull/621) for a comprehensive solution for atlases. While drawings are limited to 8-bit (256 regions), voxel-based atlases can have an arbitrary number of levels. At the moment, these are specific to voxel-based images, but can be extended to indexed meshes in the future.

**Comment by neurolabusc** [comment]
@hiksa I have created a script to convert [FreeSurfer color tables to NiiVue colormaps](https://github.com/niivue/fs2NiiVueColormaps). 

@dngreve and @pwighton I realize that [FreeSurfer has an institutional license](https://github.com/freesurfer/freesurfer/blob/dev/LICENSE.txt). Can you confirm that the colormaps can be shared with the BSD-2 Clause License.
