### ISSUE TITLE
The canvas is erased on drawSelectionBox() method

### ISSUE THREAD

**Issue by shrutivarade** [niivue/niivue#619]
Hello developers,

I am a student of Prof. Daniel at University of Massachusetts, Boston and we were looking into using nv.drawSelectionBox([x,y,w,h]) that draws a selection box but the canvas turns black. 

We have the segmentation part working with niivue but we are looking into interactive region of interest selection now. I am new to the niivue build process - how do I access this new feature? 

Is there an example?

**Comment by haehn** [comment]
@shrutivarade this is related to https://github.com/niivue/niivue/issues/596 and it seems like it is merged now so maybe just try it with the latest niivue.js
