### ISSUE TITLE
drawing pen color and thickness

### ISSUE THREAD

**Issue by johnren-code** [niivue/niivue#624]
Hello! I would like to know if there is currently a function like `nv.setPenValue` that allows us to customize the color and thickness of the brush and the thickness of the eraser more flexibly?

Also, regarding issue616, I successfully ran your code and I got `nivue.es.js` and `nivue.umd.js` using the npm run build command, can I import these two js files into my project to use the latest nivue library?

Looking forward to your reply.

**Comment by hanayik** [comment]
Hi @johnren-code , you can import the bundled niivue files into a project like this (just one example using es modules):
https://github.com/niivue/niivue/blob/021be632353a3997b610b067c0a829b72017cd0e/demos/features/basic.multiplanar.html#L31

**Comment by johnren-code** [comment]
Okay, I got it, thanks a lot. In addition, I would like to know if there is currently a function like `nv.setPenValue` that allows us to customize the color and thickness of the brush and the thickness of the eraser more flexibly?

**Comment by johnren-code** [comment]
OK, Thank you! I would like to know if there is currently a function in niivue that supports us to get data from ITK's colormap directly, I would like to make a change based on ITK's colormap, but find it quite tedious to enter the colormap manually one by one by myself.

**Comment by neurolabusc** [comment]
@hanayik I will close this issue for now. I think we can revisit this after [we have a robust semiautomated segmentation](https://github.com/niivue/niivue/issues/663) tool. This will provide a concrete platform to evaluate the best way to guide and refine these segmentations.
