### ISSUE TITLE
orientation labels incorrect for demo FLAIR.nrrd image

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#627]
The demo image /demos/images/FLAIR.nrrd displays incorrect orientation labels when loaded in niivue

To replicate: Open https://niivue.github.io/niivue/features/basic.multiplanar.html and drag and drop the demos/images/FLAIR.nrrd image onto the canvas. 

<img width="1198" alt="Screenshot 2023-06-20 at 20 47 23" src="https://github.com/niivue/niivue/assets/5217720/be897f89-0e80-4b8e-92d4-25e1ce127598">

**Comment by neurolabusc** [comment]
@hanayik this is a limitation of the image, not NiiVue. You can see this by viewing the image with Slicer3D, or by viewing the header with a text editor. The image was converted from NIfTI to NRRD with [Convert3D](http://www.itksnap.org/pmwiki/pmwiki.php?n=Convert3D.Convert3D), and that excellent set of tools does [exhibit issues](https://github.com/rordenlab/dcm2niix/issues/718) mingling formats where the first line is at the top of the screen (e.g. NRRD) and those where the first line is at the bottom (NIfTI).

```
ITK_FileNotes:=Created by Convert3D
ITK_InputFilterName:=NrrdImageIO
```

I will resolve this by replcaing the NRRD created with Convert3D to one created with Slicer3D.
