### ISSUE TITLE
add volume calculation to getDescriptives function

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#628]
report number of voxels and volume in mm3 in descriptives output. If a mask is provided (e.g. a drawing) then report the volume for the masked region. 

https://github.com/niivue/niivue/blob/bfb23eacbcefb4d8ddc1321b3c2a4e62871603a6/src/niivue.js#L4584

**Comment by neurolabusc** [comment]
The number of voxels in masked volume is returned as `nvox`. To convert to mm3 simply compute the product nvox *  hdr.pixdim[1] * hdr.pixdim[2] * hdr.pixdim[3]
