### ISSUE TITLE
What do the letters RGBAI represent in colorMap?How should i change it?And how to determine label counts?

### ISSUE THREAD

**Issue by hefangnan** [niivue/niivue#632]

**Comment by hanayik** [comment]
Hi @hefangnan , I think this document should help you out some:

https://github.com/niivue/niivue/blob/main/docs/development-notes/colormaps.md

**Comment by hanayik** [comment]
@hefangnan , I'm closing this since the colormaps documentation should have the info you want. Comment or reopen if needed.
