### ISSUE TITLE
Can I load multiple nii files?

### ISSUE THREAD

**Issue by hezhongfeng** [niivue/niivue#635]
Can I load multiple nii files, put multiple objects together, and save them as one file?

**Comment by hanayik** [comment]
Hi @hezhongfeng , Yes you can load multiple .nii files at the same time. See our [demo code](https://github.com/niivue/niivue/blob/2db3d9250040f68683853b48cf920eb7332d48dc/demos/features/basic.multiplanar.html#L42) as a reference.

You can save your scene as well once you have loaded multiple files by using the `saveDocument` method. See our other [demo code](https://github.com/niivue/niivue/blob/2db3d9250040f68683853b48cf920eb7332d48dc/demos/features/document.3d.html#L79) as a reference. You can then [reload the saved document](https://github.com/niivue/niivue/blob/2db3d9250040f68683853b48cf920eb7332d48dc/demos/features/document.load.html#L141) later to recreate that scene.

**Comment by hezhongfeng** [comment]
Thanks.
