### ISSUE TITLE
Can you move objects?

### ISSUE THREAD

**Issue by hezhongfeng** [niivue/niivue#636]
I download this repository and build run demo.
this demo `basic.multiplanar` load 2 nii files.
Can you move objects? 
For example, move the red one out of the middle

**Comment by hanayik** [comment]
Hi @hezhongfeng , You can rearrange the volumes in niivue by calling some helper functions such as:
- `moveVolumeUp`
- `moveVolumeDown`
- `moveVolumeToBottom`
- `moveVolumeToTop`

However, these functions just change the order of layers. This will not remove objects contained within your data. 

See more here in the developer docs: https://niivue.github.io/niivue/devdocs/Niivue.html#moveVolumeDown

**Comment by hezhongfeng** [comment]
Thanks.

**Comment by hezhongfeng** [comment]
@hanayik 
Hi, I meant to change the coordinates of the volume center point.
As an example, use the keyboard to try to move the volume.

**Comment by hezhongfeng** [comment]
like make one volume translate in (X,Y,Z)
