### ISSUE TITLE
I have many nii.gz in volunmes， now i want to show these images separately when i click on any of them. How to achieve this function?

### ISSUE THREAD

**Issue by hefangnan** [niivue/niivue#637]
![Snipaste_2023-06-29_14-43-52](https://github.com/niivue/niivue/assets/52640516/b69ffca0-381e-4cfc-9dc9-b87209a26ffb)

**Comment by hanayik** [comment]
Hi @hefangnan , I would do this by toggling the opacity of your volumes. You can use `setOpacity` to achieve the desired effect. See the developer docs here (search for setOpacity):
https://niivue.github.io/niivue/devdocs/Niivue.html
