### ISSUE TITLE
 Why sometimes only one of multiple files can be displayed, and the overlapping effect cannot be achieved？

### ISSUE THREAD

**Issue by hefangnan** [niivue/niivue#639]
![Snipaste_2023-07-02_21-11-37](https://github.com/niivue/niivue/assets/52640516/0b3dd935-5c94-4a42-b06f-f36532bf4ce7)

**Comment by neurolabusc** [comment]
I am unable to replicate.

@hefangnan if you want meaningful and timely answers, please provide live demos that illustrate your problem. I have created a [template live repository here](https://github.com/neurolabusc/niivue_volumes) that you can try out [as a live demo](https://neurolabusc.github.io/niivue_volumes/). As you can see, my live demo is unable to replicate your problem. A couple of possibilities are that an opaque top layer can occlude your ability to see lower layers (solutions include adjusting opacity or setting the cal_min and cal_max to mask dark regions). Another issue can be if your top layers are not spatially aligned with the bottm (background) layer, so it is out of the field of view.

**Comment by hefangnan** [comment]
Inspired by you, I solved the problem, thank you very much!
