### ISSUE TITLE
On the Color Display of Multiple Labels in Segmented Images

### ISSUE THREAD

**Issue by 1-on** [niivue/niivue#660]
I need to display different labels in different colors on the segmented NII image. What should I do

**Comment by neurolabusc** [comment]
[Details are provided in the developer notes for colormaps](https://github.com/niivue/niivue/blob/main/docs/development-notes/colormaps.md#atlases-and-labeled-images). You can interactively change the labels of a [segmented NIfTI image in the live demo linked from the developer notes](https://niivue.github.io/niivue/features/segment.html).

**Comment by 1-on** [comment]
I can execute the code normally by directly referencing the niivue library, 
<script src="https://niivue.github.io/niivue/features/niivue.umd.js"></script>
but when I introduce a local niivue in the vue, it prompts me that I cannot find the setColormapLabel method
