### ISSUE TITLE
vscode extension for NiiVue

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#665]
Hi All, 
Thanks for inviting me to the NiiVue repository!
We had the following idea for using NiiVue in a vscode extension, I think here might be a good place to show:

We created a vscode extension to render images with NiiVue when a file of supported format is selected:
<img width="760" alt="image" src="https://github.com/niivue/niivue/assets/1307522/4fad01c8-ef18-4f14-924e-874af90dfec9">

In the web-based vscode on github.dev:
<img width="728" alt="web_based" src="https://github.com/niivue/niivue/assets/1307522/6d3acbee-0f26-4f5b-a840-8f01675d201e">

The extension is easy to install via the vscode extension tab by searching for "niivue". Please have a go!

It's still very early development and plenty of features that could be added.
What are your thoughts about it?

Best,
Korbinian

**Comment by neurolabusc** [comment]
@korbinian90 this is terrific. I would invite you to make this a new repository in the [niivue](https://github.com/orgs/niivue/repositories) group to help people find it. I would also suggest renaming from [vscode-niivue](https://github.com/korbinian90/vscode-niivue) to niivue-vscode to match the style of other projects (e.g. niivue-desktop, niivue-ipad, etc.).

**Comment by hanayik** [comment]
@korbinian90 , this is great! I’ve always thought it would be fantastic to view supported images directly in vscode. I just installed and love it already. Very happy to have it included in the NiiVue ecosystem, and thanks for making the extension. I think a lot of people will like it.
