### ISSUE TITLE
onLocationChange not triggered when moved by key press

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#677]
The `onLocationChange` listener does not trigger when the crosshair is moved by key press

This can be seen tested in https://niivue.github.io/niivue/features/basic.multiplanar.html, when pressing H to move the crosshair. The intensity value does not update.

**Comment by dlevitas** [comment]
This appears to be related to the `keyDownListener()` [function](https://github.com/niivue/niivue/blob/727a1a8ca44e0c51709f2e6fe5b48cafe80826ba/src/niivue.js#L1472). Simply adding `this.createOnLocationChange();` on the following line updates the intensity value when pressing the H (and also J, K, L) keys. 

I'm still working through the NiiVue codebase, but assuming this doesn't create unexpected behaviors elsewhere I'd be happy to submit a PR.

**Comment by neurolabusc** [comment]
@dlevitas that looks like the correct place for a patch. I can add this in to an upcoming PR that will address a few of the open issues.

**Comment by neurolabusc** [comment]
@korbinian90 and @dlevitas my latest commit to the drawing branch resolves this. Also, previously the keys would increment the crosshair position by a fixed percentage of the image resolution. The new behavior is to increment the crosshair position by precisely one slice. This means that the keys make more proportionally larger jumps for lower resolution images. This is helpful for drawing, as one can precisely jump from drawing on one slice to drawing on the next.
