### ISSUE TITLE
Does this plugin support padding?

### ISSUE THREAD

**Issue by gaofengxu888** [niivue/niivue#678]
like this
![image](https://github.com/niivue/niivue/assets/16555773/e5e36bb9-f993-4163-a2be-80720cdf1d48)

**Comment by neurolabusc** [comment]
Not at the moment. I notice that the mockup for [issue 663](https://github.com/niivue/niivue/issues/663) also shows padding, so this is something that the development team should discuss at the next meeting.

**Comment by neurolabusc** [comment]
@gaofengxu888 in fact you can set the property `nv1.opts.multiplanarPadPixels = 3` to insert spacing. Once my latest commit is approved, there will be a new helper function `setMultiplanarPadPixels()` that will also show up in the [docmentation](https://niivue.github.io/niivue/devdocs/Niivue.html) and have a [live demo](https://niivue.github.io/niivue/features/atlas.html).


The live demo will include a slider that allowss you to interactively adjust the padding. It also includes a check box to allow you to choose between a light background (where the slice borders are distinct) and a dark background (where the padding between slices still exists, but is more subtle to see).
![padding](https://github.com/niivue/niivue/assets/8930807/1dd919ad-ac97-43cc-aea2-ff38c81d3193)
