### ISSUE TITLE
FEATURE: show intersecting slice view

### ISSUE THREAD

**Issue by ningfei** [niivue/niivue#679]
Would be great to be able to show a intersecting slice view (e.g. as in the figure below).

![slice](https://github.com/niivue/niivue/assets/516957/7d41e15a-9d4e-4ea6-9e14-e39eced8b041)

**Comment by neurolabusc** [comment]
@ningfei I have created a shader to achieve this, and will discuss inclusion with the team. There are a few issues that come to light with regards to usability:
 - It feels most natural when the intersecting slice view shows the same slices as the slice views. However, this means that the rendering crosshair is always at the slice intersections, where one can think of some situations where this would be nice to decouple (e.g. crosshairs aligned to a major tract, while the slice intersections are elsewhere. It is hard to work out a good UI for these competing use cases.
 - Should clip planes exist with the intersecting slice view? It is very hard to gauge the depth and angle of the clip plane in this view, so perhaps they should just be disabled.
 - A complete solution will need both a visible render shader and a depth picking shader.

![clipPlaneX](https://github.com/niivue/niivue/assets/8930807/60e07aae-0330-4267-8886-fc67cf10d3a4)

**Comment by ningfei** [comment]
Cool, thanks! 
- In our case we don't really use the crosshair as well as the clip planes. If we need a 2D slice, we usually achieve it by straighten the 3D scene. For the 3D scene, we can either drag the slice itself or use a scrollbar to navigate through.
- Agreed that it would be nice to have the crosshair so it can be aligned with the coordinate but I think it's difficult to decouple. A simple solution would be showing either the intersecting view or the 2D plane view, not both.  And one can easily switch between the two.

**Comment by neurolabusc** [comment]
@ningfei perhaps you want to try out my implementation. You can try out the experimental drawing branch as follows:

```
git clone --branch drawing git@github.com:niivue/niivue.git
cd niivue
npm install
npm run demo
```

which launches a web server, allowing you to open the `Shiny volume rendering` live demo - the mode pull down allows you to select the `slices` rendering mode.

**Comment by neurolabusc** [comment]
Closing. You can set the volume rendering mode to `slices` in the new [live demo](https://niivue.github.io/niivue/features/shiny.volumes.html) to evaluate this feature.
