### ISSUE TITLE
NiiVue 0.37.0 thinks it is 0.36.0

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#690]
When including the node_modules\@niivue\niivue\dist\niivue.umd.js file in html, the following console output is printed:
NIIVUE VERSION  0.36.0

Searching in the file niivue.umd.js also gives a lot of results of "0.36" while no result for the version "0.37".

The package.json file in node_modules\@niivue\niivue\package.json correctly states:
"version": "0.37.0",

**Comment by hanayik** [comment]
@korbinian90 Thanks for pointing this out. I will look into it and patch as necessary.
