### ISSUE TITLE
Nearest Neighbor - weird visual appearance

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#692]
When selecting nearest neighbor interpolation, it looks perfect when the voxels are large, but for smaller voxels, there is a weird visual appearance (shown in 4x zoom):
![image](https://github.com/niivue/niivue/assets/1307522/b4defd87-3c5e-4b5b-b6d4-d75e62f1bb65)
Some voxels are drawn very small compared to others

**Comment by neurolabusc** [comment]
This is an inherent property of this filter: [Nearest neighbor interpolation (also known as zero-order interpolation) is the simplest method, and strong aliasing and blurring effects are associated with this interpolation](https://www.hindawi.com/journals/ijbi/2013/395915/). Note that nearest neighbor and trilinear texture interpolation is computed in hardware with [WebGL](https://webglfundamentals.org/webgl/lessons/webgl-3d-textures.html). The artifacts will be most apparent when an oblique angle exists in plane, therefore you may want to constrain nearest neighbor interpolation to [voxel-space rather than world space orientations](https://niivue.github.io/niivue/features/worldspace.html).

**Comment by korbinian90** [comment]
Thanks for the links and explanation! I used normal non-oblique angle views. It still felt a bit weird to me that it is visible this heavily on a 4K 32" monitor.

After trying a few things I found that the problem is increased by the display scaling factor of windows, which was set to 150%. Setting it to 100% solves the problem for me, as the effect is hardly noticeable anymore. Setting it to the maximum 350% increases the problem and even introduces blurry edges.

I found the high resolution setting in NiiVue: 
`const nv = new niivue.Niivue({ isResizeCanvas: true, isHighResolutionCapable: true });`
This also seems to solve the issue. Are there expected downsides to setting this always to true (for the vscode extension)?

**Comment by neurolabusc** [comment]
@korbinian90 please see the notes for [PR488](https://github.com/niivue/niivue/pull/488). 

Ultimately, as the developer of this extension, you need to make some decisions regarding the default speed and performance tradeoffs you are comfortable with. This is a moving target as GPUs are getting dramatically more powerful while display DPI is reaching the limits of physiology and MRI SNR limits the resolution of the images.

@afni-dglen uses a 1.1GHz MacOS laptop from 2020 with an Intel CPU and integrated graphics that is constrained to 10 watts but with a high resolution (retina display). On one hand, we want to provide good performance for computers in the developing world. On the other, this laptop has four times the pixels and runs on less power than traditional laptops from the era, so one could argue it has a very imbalanced design. That laptop has poorer NiiVue performance than my 2019 iphone with retina display. 

To provide a sense for these tradeoffs, please examine the [Anti-Aliasing: faster (off) or better (on) live demos for meshes and voxels](https://niivue.github.io/niivue/). This will allow you to evaluate the quality and speed tradeoffs:
 1. When you attach NiiVue to a WebGL context you can [request anti-aliasing](https://medium.com/@pixelscommander/why-does-webgl-antialiasing-lie-51e5d3e208bb). In the [live demos](https://github.com/niivue/niivue/blob/90811ad7dec22b73807b599091052a7c2e27f36e/demos/features/mesh.freesurfer.aaON.html#L172C7-L172C32) the call `nv1.attachTo("gl1", true);` requests antialiasing, `nv1.attachTo("gl1", false);` will not request antialiasing, and teh default `nv1.attachTo("gl1");` will make a request depending on the hardware used (this is tricky, as for privacy reasons most browsers do not provide any details about the GPU). Note that one can only request antialiasing - a specific user's computer may refuse this request. This request must be made when the context is created, and can not be adjusted at run time. If enabled, antialiasing is typically performed in hardware.
 2. The run time [function setHighResolutionCapable(boolean)](https://niivue.github.io/niivue/devdocs/Niivue.html#setHighResolutionCapable) and the creation boolean `isHighResolutionCapable` will use the native resolution of the display if set to true. This has now influence if the the monitor is not high resolution. The quality and performance impact depends on the [devicePixelRatio](https://www.khronos.org/webgl/wiki/HandlingHighDPI).
 3. The meshXRay is a continuous value that defaults to 0.0. Any value larger than 1 will draw the mesh twice with different opacity to allow one to see details deep structures. Here a a nice [live demo](https://niivue.github.io/niivue/features/tracts2.html). While meshes for games constrain the number of triangles for fast rendering, scientific medical imaging meshes supersample the surface, so they place a great burden on rendering. 
 4. In theory, nearest neighbor interpolation is faster than trilinear. However, both are performed in hardware.

It is interesting that setting the value of isHighResolutionCapable influences the behavior on your 4k monitor. This suggests that your computer reports a [hardwareConcurrency of less than 7](https://github.com/niivue/niivue/blob/90811ad7dec22b73807b599091052a7c2e27f36e/src/niivue.js#L780). As long as you do not specify isHighResolutionCapable, NiiVue will use isHighResolutionCapable if the hardwareConcurrency is greater than 6. Like @afni-dglen you have a relatively high resolution display with a relatively low-power CPU. However, while @afni-dglen advocated for choosing speed over quality in this situation, you are advocating for the opposite choice. I do think that these decisions are very transient - the latest generation integrated graphics are far more powerful than their predecessors, and even most phones now have more than 6 threads.

**Comment by hanayik** [comment]
Closing since this has been thoroughly answered. Please reopen as needed.

**Comment by korbinian90** [comment]
@neurolabusc Thank you for the detailed explanation!
I think the issue on my machine with not selecting `isHighResolutionCapable` is that my default is to have `isResizeCanvas: false`. I first have to figure out how to make the resizeCanvas cooperate with my own multiple-view resizing logic.
I plan to revisit this again after some other tasks
