### ISSUE TITLE
Tilting image

### ISSUE THREAD

**Issue by rnorlund** [niivue/niivue#701]
Hi all, one problem I often run into drawing lesions is that the brain is not oriented properly (so scaning through axial slices and looking for symmetry is problematic). 
For example, Neuro3D on a Siemens lets you tilt the crosshairs.
If I could tilt the axial plane quickly, that would be great. 
Do we yet have that functionality simply integrated?

**Comment by neurolabusc** [comment]
We will add a new image reslicing coform option to aid the machine learning usage of this tool. This might be useful for drawing lesions on some high resolution anatomical scans. However, in general this request is outside the remit of NIiVue and users should think carefully about how they solve this problem. Reslicing images is lossy, and clinical scans often have anisotropic spatial resolution (e.g. high in-plane resolution and low resolution through plane). When we draw lesions, we create a binary map identifying injured and spared voxels. These discrete images are necessarily prone to aliasing artifacts. The important aspect of NiiVue is that the drawings are mapped onto the native resolution of the background image. Our revolutionary display avoids the [artifacts seen with other tools like FSLeyes](https://github.com/rordenlab/dcm2niix/issues/595).

If a user really wants to conform their data, there are numerous tools to do this. However, this approach can often have unintended consequences.
