### ISSUE TITLE
higher customization possibilities for the interface layout

### ISSUE THREAD

**Issue by CryWhileCode** [niivue/niivue#702]
Hi, I'm using this library in my current project, but I'd like to have higher customization possibilities for the interface layout, similar to the palace layout of VTA.js.
![vta](https://github.com/niivue/niivue/assets/106230567/aa5b84f6-9c21-4a14-b67f-f02c79d9160d)

**Comment by CryWhileCode** [comment]
Layouts like this one from BrainBrowser are also possible
![image](https://github.com/niivue/niivue/assets/106230567/62048281-b61c-4450-9cad-a4117f98bb69)

**Comment by hanayik** [comment]
@CryWhileCode , thanks for providing some examples. NiiVue already provides the 4 panel layout, but this is only shown if the html canvas height is greater than the width. When the canvas is in landscape mode (width > height) then the scene is rendered as a single row, rather than two rows and two columns. NiiVue is meant to work on any WebGL2.0 capable device, including smartphones and tablets that are often rotated between landscape and portrait views. 

You can force NiiVue to use the 2x2 layout if you make your canvas within your app taller rather than wider. 

The brain browser example (layout as a single column) is not currently possible in NiiVue, but could be with minor changes.

**Comment by neurolabusc** [comment]
You can always use the mosaic view. For example in this [live demo](https://niivue.github.io/niivue/features/mosaics.html) you can get a 4x4 grid by using a mosaic string of `-30 -20 -10 0; 10 20 30 40; 50 60 70 80`, and if you want a single 1x4 column you could insert `-30; -20; -10; 0`.  You can put a bit of space between tiles by using the `padding` to create a margin, as seen in this [live demo](https://niivue.github.io/niivue/features/atlas.html). Likewise, the [Sync live demo](https://niivue.github.io/niivue/features/sync.mesh.html) shows how you can have different NiiVue modules communicate with each other, just like your brainbrowser demo.

However, as noted on [our home page](https://github.com/niivue/niivue#niivue) we encourage developers to use the best tool for their job, with voxel-based alternatives including [ami](https://fnndsc.github.io/ami/), [BioImage Suite Web](https://bioimagesuiteweb.github.io/webapp/viewer.html), [BrainBrowser](https://brainbrowser.cbrain.mcgill.ca/volume-viewer), [nifti-drop](http://vsoch.github.io/nifti-drop), [OHIF DICOM Viewer](https://viewer.ohif.org/), [Papaya](https://www.fmrib.ox.ac.uk/ukbiobank/group_means/index.html), [VTK.js](https://kitware.github.io/paraview-glance/app/), and [slicedrop](https://slicedrop.com/). We see NiiVue as filling a separate niche from these tools: we provide a unified domain-specific tool for viewing the voxels, meshes, statistics, connectomes and tractography data of neuroimaging using a very simple API. We do not try to do everything, and by keeping the visualization consistent the end users can transfer their skills between popular tools that are adopting NiiVue including AFNI, FreeSurfer, FSL, and nilearn.  Each tool must make choices about simplicity, interface consistency and flexibility. While you are free to fork NiiVue and modify it as you wish, the core tool tries to provide a solution specific to the developer's domain expertise.

**Comment by neurolabusc** [comment]
My upcoming PR will introduce a new function named setMultiplanarLayout that will allow users to select the layout of column, row, grid, or auto (the default, which uses the optimal layout for the canvas size). Once this PR is merged, a new [layout live demo](https://niivue.github.io/niivue/features/layout.html) will go online.
 
![layout](https://github.com/niivue/niivue/assets/8930807/bbc18e50-05c4-4304-bb5f-5e95340a2985)

**Comment by CryWhileCode** [comment]
@neurolabusc @hanayik Thank you very much for your reply.
I tried it with the code in your PR and it does force the grid layout already! but the other problem is that I want to make the width and height of each view the same. Like the picture below.
![image](https://github.com/niivue/niivue/assets/106230567/4ede42dd-bcdc-4d03-bf2e-9add976383e4)
The width and height of the S-side is not the same as that of the A and C-side. But in niivue it looks like this
![image](https://github.com/niivue/niivue/assets/106230567/b76546b1-34b2-4978-ac1e-1fcdfda68f71)
And I found that inside VTA.js he has four canvas images for each of the four sides A, C, S, and R. Would this be more conducive to user customizable layouts? I think if this was done for pages it would be easier to add custom content on them. To some info like this below.
![image](https://github.com/niivue/niivue/assets/106230567/83764b12-fad1-411f-8b66-98ea94b181f2)

**Comment by hanayik** [comment]
@CryWhileCode , thanks for the feedback after testing the new layout feature. I don't think we want to manage 4 different canvases within niivue. The Niivue library is intended to be embedded into other applications using a simple API. To achieve the look you are going for, you could experiment with the `multiplanarPadPixels` property when creating a niivue instance. You can also overlay any html element on the canvas to create the HUD like interface you referenced in your screenshots. To do that, just use `position: absolute` in the css styles for the HUD elements.
