### ISSUE TITLE
The colorbar for negative colormaps is always shown for meshes

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#704]
Starting from the example https://niivue.github.io/niivue/features/colormaps.mesh.html, I wanted to use an only-positive colormap and not show the negative colorbar.
With the setting `useNegativeCmap: false`, the unused negative colorbar is still displayed.

**Comment by hanayik** [comment]
@korbinian90 , you can achieve this by setting `colormapNegative` to an empty string.
