### ISSUE TITLE
Change syncWith to broadcastTo(object | array)

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#709]
Currently, niivue instances can sync with each other so that one can drive another. This is done with the `syncWith(otherNvInstance`) call. However, this is slightly confusing syntax since the driving niivue instance is the one passed as the argument. 

I think a more clear call would be `broadcastTo(object | array)`. This new `broadcastTo` function would allow any niivue instance to broadcast its syncable properties to any other niivue instance (or multiple niivue instances if the input is an array of niivue instances). Any niivue instance can broadcast to any other niivue instance since the one with focus will be doing the broadcasting (avoiding a recursive sync).

**Comment by korbinian90** [comment]
I'm using the new broadcastTo function, it makes the syncing way better! Thanks!

For easier usage, we could avoid syncing with oneself. I accidently created a few infinite loops when using it with broadcastTo(nv, nvArray) since nv was included in the array.

I'm creating a pull request
