### ISSUE TITLE
Switching subjects after loading meshes causes slice type to reset

### ISSUE THREAD

**Issue by asagilmore** [niivue/niivue#710]
I am loading meshes using the following function.

```
async function loadBundle(bundle){
  if (!nv.initialized) {
    await nv.init();
  }

  if (nv.gl) {
    let url = getBundleLink(props.dataset,props.subject,props.site,bundle)
    let color = bundle.rgba255
    let meshOptions = {url:url, rgba255: color, gl: nv.gl}
    await nv.addMeshFromUrl(meshOptions);
    return
  } else {
    console.error('WebGL context is not initialized');
  }
}
```
When I then load a new volume it resets the slice type to Render.

this bug can be seen [here](https://github.com/NRDG/tractoscope) aswell.

**Comment by neurolabusc** [comment]
I am unable to replicate your situation, and it looks like a lot of things are going on. If you want clear feedback, you may want to make a fork of NiiVue and edit the /src/index.html so a live demo replicates your problem. For example, the master branch live demo is invoked with:

```
git clone git@github.com:niivue/niivue.git
cd niivue
npm install
npm run dev
```

Having said this, it seems this might be the intended behavior. The sagittal, axial, coronal and MPR views require a voxel-based image to anchor them. If you load a mesh, connectome, or tractography without a voxel-based image, the rendering is the only available slice view. Therefore, it does not seem unexpected to me that loading a mesh invokes the meshes native view. Once you have loaded a voxel-based dataset, you can always choose a slice view, as illustrated by the pull down menu in this [live demo](https://niivue.github.io/niivue/features/basic.multiplanar.html).

**Comment by neurolabusc** [comment]
As an aside, if you are loading both a voxel-based image and a mesh, make sure you await for the loading of the voxels to complete before awaiting the loading of the mesh. Voxels take a long time to load to the GPU, so without the `await` the mesh loading may not detect a voxel is loading simultaneously:

For example, with a hot-loading `npm run dev` I can simulate your issue if I omit the `await` before the loadVolumes.
```
  await nv1.loadVolumes([{url: "../demos/images/mni152.nii.gz"}]);
  await nv1.loadMeshes([{url: "../demos/images/BrainMesh_ICBM152.lh.mz3"}]);
```
