### ISSUE TITLE
Support for MNI file formats

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#726]
Hello,

I would be interested in support for the Montreal Neurological Institute (MNI)'s file formats:

- [MINC](https://www.bic.mni.mcgill.ca/ServicesSoftware/MINC): voxel volumes
- [.obj](https://www.bic.mni.mcgill.ca/users/mishkin/mni_obj_format.pdf): surface mesh (not to be confused with Wavefront, same extension however different spec)
- .txt files represent "mesh overlay" e.g. cortical thickness, surface mask, ... vertex-wise data

Would you all accept a PR for this? If so, any pointers on how I can get started?

**Comment by jennydaman** [comment]
Example data can be found here: https://github.com/FNNDSC/civet_example_datalad

Web software for visualizing MNI formats can be found here:

- Surface viewer: https://natacha-beck.github.io/brainbrowser/BrainBrowserSurfaceUI/
- Volume viewer: https://natacha-beck.github.io/brainbrowser/BrainBrowserVolumeUI/

**Comment by neurolabusc** [comment]
Supporting the MNI OBJ format is easy, it is described [here](http://www.bic.mni.mcgill.ca/users/mishkin/mni_obj_format.pdf), with examples [here](https://bigbrain.loris.ca/main.php?test_name=brainsurfaces). It is a text-based format with the resulting penalties in precision, file size and speed. While I would discourage using this legacy format, I can add support for this.

MINC was [originally based on NetCDF, but the data format was changed to HDF](http://www.bic.mni.mcgill.ca/ServicesSoftware/MINC). I have very little experience with any of these formats or how they are used in the wild. I note that [brainbrowser has JavaScript code for MINC, NetCDF and enough HDF to support MINC](https://github.com/aces/brainbrowser/tree/fe0ce114c6cd8e317a6bdd9b7ef97cbf1c38309d/src/brainbrowser/volume-viewer/volume-loaders). The simple option would if the authors of those libraries [Robert D. Vincent (@rdvincent) Nicolas Kassis (@nkassis) and Tarek Sherif (@tsherif)] agreed to re-brand those core libraries with a permissive license that is compatible with our BSD-2 clause license. At the moment, we can not incorporate their GPL code (I like to think of the BSD-2 like O negative blood type, as it is the universal donor but is also the most restrictive recipient).

**Comment by rdvincent** [comment]
I not longer work at the MNI, so I lack the authority to change the licensing terms of the code. However, I certainly have no objection to the change.

**Comment by jennydaman** [comment]
@neurolabusc support for MINC is less important since MINC users can easily run `mnc2nii`.

What program can I use to convert MNI `.obj` and `.txt` to more conventional formats? While I wrote [my own converter](https://github.com/fnndsc/pybicpl) from `.obj` to `.asc` or Wavefront, it doesn't handle `.txt` e.g. thickness data, curvature data.

In the absence of a good converter - between the option of spending effort to write a converter v.s. adding direct support to NiiVue, I'd rather do the latter and make a contribution.

**Comment by neurolabusc** [comment]
You can use [Surfice](https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage) to read MNI OBJ and save them to other formats. You can either do this with the graphical interface (drag and drop meshes to load, choose Advanced/SaveMesh to save) You can use the Scripting/New menu item write Python script.

For example, this script  converts the mesh [gray_left_327680.obj](https://bigbrain.loris.ca/main.php?test_name=brainsurfaces) from 17.8 to a 3.8mb GIfTI or 2.9mb MZ3. The GIfTI format is a great interchange format, but if your only aim is to create web pages using NiiVue, the mz3 format [is faster and smaller](https://github.com/neurolabusc/MeshFormatsJS) so will result in more responsive web sites.

```
import gl
gl.meshload('/Users/chris/Desktop/gray_left_327680.obj')
gl.meshsave('/Users/chris/Desktop/gifti.gii')
gl.meshsave('/Users/chris/Desktop/mz3.mz3')
```

I am not familiar with your thickness and curvature data, but NiiVue will load popular per-vertex scalar values that you could save as FreeSurfer [curv](http://www.grahamwideman.com/gw/brain/fs/surfacefileformats.htm), BrainVoyager or [mz3](https://github.com/neurolabusc/surf-ice/tree/master/mz3) data. This [live demo](https://niivue.github.io/niivue/features/mesh.stats.html) shows how you can load a FreeSurfer curv file (the 'curvature' slider adjusted the opacity).

**Comment by jennydaman** [comment]
Hey @neurolabusc thank you for working on support for MNI .obj format!

The format used by MNI for thickness/curvature data is just a whitespace-delimited list of floats, one value per vertex. It is the same concept as a isSCALAR mz3. I wrote a mz3 encoder for this, and it seems to work when I load the output as a surface overlay in Surfice. https://github.com/FNNDSC/mni2mz3

Do you think you will add native support for `.txt` as a mesh overlay format to NiiVue?

I was also able to use SurfIce to convert from MNI .obj to .mz3, though the Surfice program doesn't suit my workflow (do bulk conversion and run everything in containers). I'll probably add the .obj to .mz3 functionality to the `mni2mz3` program I'm working on.

**Comment by neurolabusc** [comment]
@jennydaman
 - I did write an importer for the MNI .obj format meshes, so it will likely be incorporated in the next few days.
 - The text format seems easy enough to support, but the challenge is that the extension `.txt` is widely used for all variations of text formats. The NiiVue drag and drop works by using a file extension to decipher the format and type (e.g. .nii, .obj, .trx, .jcon, for voxel, mesh, connectome, tracts, per-vertex scalars). So I worry that assuming that all `.txt` files are MNI-format per vertex scalars may have a lot of unintended consequences. 


I do think your [mni2mz3](https://github.com/FNNDSC/mni2mz3) looks like a good solution. I have a couple small comments:
 - I assume you meant that the the second argument should be `.mz3` not `.txt`
```
# convert scalar per-vertex values
mni2mz3 thickness.txt thickness.mz3
```
 - While mz3 is the native mesh format of Surfice and NiiVue (as it directly maps to how we transfer mesh vertices and indices to the GPU), it is also supported by other tools including SPM and PALM.

**Comment by jennydaman** [comment]
Forgive the typos, I wrote this on a plane

**Comment by jennydaman** [comment]
@neurolabusc I've finished up `mni2mz3`, if you'd like to try it I have it compiled for various platforms and also published to PyPi. Either run

```shell
pip install mni2mz3
```

Or download a binary from https://github.com/FNNDSC/mni2mz3/releases/tag/v0.1.0-rc.4

Both mesh and scalar files produced by `mni2mz3` work in Surf-Ice. Sadly MZ3 scalar files are not working in NiiVue https://github.com/niivue/niivue/issues/729
