### ISSUE TITLE
Support for MZ3 scalar data

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#729]
The README says MZ3 is supported as both a "mesh-based format" and "mesh overlay format." However, when I tried loading a `.mz3` `isSCALAR` only file (no vertex data) into NiiVue I got an error message.

https://github.com/niivue/niivue/blob/b4a6ea1343a24dced309468e364033325358d27a/src/nvmesh-loaders.js#L1346

Looking at the code it doesn't seem like MZ3 scalar data, though other parts do seem to be about MZ3 scalar data?

https://github.com/niivue/niivue/blob/b4a6ea1343a24dced309468e364033325358d27a/src/nvmesh.js#L1031-L1032

My questions are, is MZ3 scalar-only data files supported? If so, what is the API usage?

**Comment by neurolabusc** [comment]
@jennydaman this is a bug in your (otherwise elegant) [mni2mz3](https://github.com/FNNDSC/mni2mz3) - specifically, for scalars it is claiming NVERT = 0 when for scalars the NFACE = 0 and NVERT is set to number of vertices.

Consider converting your [sample data](https://github.com/FNNDSC/civet_example_datalad):

```
mni2mz3 mni_icbm_00100_surface_rsl_right_native_volume_40mm.txt scalars.mz3
mni2mz3 mni_icbm_00100_white_surface_rsl_right_81920.obj mesh.mz3
```
If you change the NVERT of the resulting `scalars.mz3` to 40962 the overlay will load correctly. You can test this by putting the mz3 files into your /NiiVue/src folder, changing the /NiiVue/src/index.html to the included file and running `npm run dev`:
![nv](https://github.com/niivue/niivue/assets/8930807/ad094c43-553e-480c-b383-89d1a22cdacd)

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>Mesh Statistics</title>
    <link rel="stylesheet" href="niivue.css" />
  </head>
  <body>
    <noscript>
      <strong
        >niivue doesn't work properly without JavaScript enabled. Please enable
        it to continue.</strong
      >
    </noscript>
    <header>
      <label for="curveSlider">Alpha</label>
      <input
        type="range"
        min="0"
        max="10"
        value="7"
        class="slider"
        id="curveSlider"
      />
      <label for="shaderDrop">Shader</label>
      <select id="shaderDrop">
        <option value="Edge">Edge</option>
        <option value="Flat">Flat</option>
        <option value="Matcap" selected>Matcap</option>
        <option value="Matte">Matte</option>
        <option value="Outline">Outline</option>
        <option value="Phong">Phong</option>
        <option value="Toon">Toon</option>
      </select>
    </header>
    <main id="container">
      <canvas id="gl1"></canvas>
    </main>
  </body>
</html>
    <script type="module" async>
      import { Niivue } from "./niivue.js";
      import { NVImage } from "./nvimage.js";
      import { NVMesh } from "./nvmesh.js";
  curveSlider.onchange = function () {
    nv1.setMeshLayerProperty(nv1.meshes[0].id, 0, "opacity", this.value * 0.1);
  }
  shaderDrop.onchange = function () {
    const shaderName = this.value;
    nv1.setMeshShader(nv1.meshes[0].id, shaderName);
  };
  var nv1 = new Niivue({
    show3Dcrosshair: true,
    backColor: [0, 0, 0, 1],
  });
  nv1.attachTo("gl1");
  nv1.opts.isColorbar = true;
  var meshLHLayersList1 = [
    {
      url: "./scalarsRH.mz3",
      colormap: "actc",
      colormapNegative: "",
    },
  ];
  await nv1.loadMeshes([{ url: "./meshRH.mz3", layers: meshLHLayersList1 }]);
  shaderDrop.onchange();
</script>
```

I will add the logic from Surfice to improve handling of malformed mz3 scalars, but this should really be fixed in your converter to ensure support for tools that follow the standard.

**Comment by neurolabusc** [comment]
@jennydaman [here is the patch](https://github.com/niivue/niivue/pull/725/files/c8ccaaec87ff6acb36bf0392d8248af4dca2d83b..2c4fe0209f6fe0df0780fad98788885d76aefd7e) to handle some malformed mz3 files and better detect unsupported features (which I have not yet seen in the wild). So this will be included in the upcoming release of NiiVue.

**Comment by jennydaman** [comment]
I appreciate the time you've spent digging into my code. I fixed the bug in https://github.com/FNNDSC/mni2mz3/commit/14e04e2d084e3eebfc3bc568ecb5d369b96bcc23 which can be obtained from the [v0.1.1 release](https://github.com/FNNDSC/mni2mz3/releases/tag/v0.1.1)

From what I can see, everything works (looks good in NiiVue and Surf-Ice) though if you would, I have some questions about the MZ3:

> The [winding order](https://www.khronos.org/opengl/wiki/Face_Culling) of faces defines the direction the triangle is facing.

Does the winding order matter for rendering the mesh? (`mni2mz3` currently does not validate triangle direction)

>  Note: for better compression integer data is transposed (interleaved)

Is this part of the spec accurate? `mni2mz3` works without applying transpose, whereas thinks look broken with transpose. Also I don't see where the transpose function is being called in the mz3 Matlab code

- https://github.com/neurolabusc/surf-ice/blob/1885f5dec0aff7691ac1995b75c3035fe09e3d37/mz3/readMz3.m#L69-L75
- https://github.com/neurolabusc/surf-ice/blob/1885f5dec0aff7691ac1995b75c3035fe09e3d37/mz3/writeMz3.m#L146

**Comment by neurolabusc** [comment]
1. For mesh graphics winding order distiguishes front faces from backfaces. You can examine the influence by visualizing a mesh with a clip plane in Surfice and choosing the `light backfaces` option from the `phong` shader. You can also try the Advanced\ReverseFaces menu item to reverse the winding order. The [Matlab documentation](https://www.mathworks.com/help/matlab/creating_plots/reflectance-characteristics-of-graphics-objects.html) describes this as well. Beyond lighting, many tools use winding order culling to accelerate visualization. Fortunately, all graphics APIs agree that the default is [CCW winding order](https://learnopengl.com/Advanced-OpenGL/Face-culling) and MZ3 follows this standard. So one would hope all MNI meshes observe this convention.

![backface](https://github.com/niivue/niivue/assets/8930807/6ec6e568-4d13-45be-a762-6db356bb1ec8)

2. Well spotted, I had originally swizzled integer data for improved compression, but this idea was voted down and not implemented anywhere (you can still invoke it with the Surfice SwizzleMZ compiler directive)[https://github.com/neurolabusc/surf-ice/blob/1885f5dec0aff7691ac1995b75c3035fe09e3d37/mesh.pas#L4350]. I will change the MZ3 documentation with the next commit.

**Comment by jennydaman** [comment]
Thank you for the extra details.
