### ISSUE TITLE
Inverting left and right

### ISSUE THREAD

**Issue by MindaugasBernatavicius** [niivue/niivue#734]
New to niivue and have a usecase where I need to flip the background CXR left to right (with the associated overlay heatmap).
Is there an easy way to flip the image left to right with niivue for coronal and horizontal perspectives? 

![image](https://github.com/niivue/niivue/assets/7895269/5492d598-d9dd-468d-a7a9-3793a0d3923d)

**Comment by hanayik** [comment]
@MindaugasBernatavicius , you can call `setRadiologicalConvention(true)` after initialising NiiVue, or use the `isRadiologicalConvention` property in the [options](https://niivue.github.io/niivue/devdocs/global.html#NiivueOptions) object when initialising NiiVue for the first time on a page.
