### ISSUE TITLE
Ruler/Measurement annotation does not sustain once another click is made

### ISSUE THREAD

**Issue by girish0628** [niivue/niivue#747]
**Version Info:** NIIVUE VERSION  0.38.0

**Issue:** 
- After creating a measurement annotation (see screenshot below) as soon as a click is made anywhere on the user interface the measurement annotation disappears
- This problem persists in given any way a measurement annotation is made

![measure](https://github.com/niivue/niivue/assets/8336926/b472e6d6-53f7-47de-a1f8-54d13e232cc2)

**What I am looking for:**
- If the annotation can be sustained in anyway via an API call or some code changes, it would be extremely helpful. In short, I would like the annotation to _not disappear_ if a click is made or any event occurs unless a manual call is made

**Current implementation of the Measurement Annotation:**
```
switch (mode) {
      case 'none':
        nv.opts.dragMode = nv.dragModes.none;
        break;
      case 'contrast':
        nv.opts.dragMode = nv.dragModes.contrast;
        break;
      case 'measurement':
        nv.opts.dragMode = nv.dragModes.measurement;
        break;
      case 'pan':
        nv.opts.dragMode = nv.dragModes.pan;
        break;
    }
```

**Comment by hanayik** [comment]
@girish0628, the current implementation of the measurement tool is intended to be transient. However, I can see the value in displaying multiple measurements at once (for example, when calculating the [Evans Index](https://radiopaedia.org/articles/evans-index-2?lang=gb)). However, I think in cases like this, we would only want to draw multiple measurement lines and text on top of the same slice (not allow for drawing persistent measurements across slices). 

@neurolabusc, do you think allowing multiple measurement lines (and text) on the same slice is reasonable?

**Comment by hanayik** [comment]
closing in favour of using custom callbacks and labelled connectomes
