### ISSUE TITLE
 Paint/Line/Drawing Annotation Meta Data Inaccessible

### ISSUE THREAD

**Issue by girish0628** [niivue/niivue#748]
**Version Info:** NIIVUE VERSION 0.38.0

**Issue:**
- Once a drawing is made whether using a brush tool or fill, the annotation cannot be deleted (see attached screenshot)
- There is no event available in the documentation/code that allows to get the drawing event object in order to delete it. Control of the object is also missing.
- dragEnd was tried as shown in below code implementation, but that does not work out in giving control of the object.

![paint](https://github.com/niivue/niivue/assets/8336926/0b23e089-30b6-42d8-bd6e-2f5ce0c5256d)

**Looking For:**
- Is there any kind of event handler available in the API for controlling the drawing object?
- Or is there some kind of API call that is currently unexposed?

Any guidance would be super helpful.

**Current Implementation:**
```
nv.setDrawingEnabled (true);
    nv.setPenValue (2, isFilled);

    nv.on ('dragEnd', evt => {
      console.log (evt);
    });
```

**Comment by neurolabusc** [comment]
@girish0628 the [live demos](https://niivue.github.io/niivue/) demonstrate how to use many features. I would suggest you look at the [Drawing user interface](https://niivue.github.io/niivue/features/draw.ui.html) live demo which includes a Edit/UndoDraw menu item.  This demonstrates the function [drawUndo()](https://niivue.github.io/niivue/devdocs/Niivue.html#drawUndo). By default the the undo buffer holds up to 8 steps (determined by maxDrawUndoBitmaps) which acts as a revolver, e.g. if you undo enough it returns to the final state.
