### ISSUE TITLE
Non-Nifti volumes (like nrrd and mif) fail to load via drag and drop

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#751]

**Comment by neurolabusc** [comment]
@hanayik I can not replicate this issue with the current stable release, for example [this web page](https://niivue.github.io/niivue/features/shear.html) loads the sample mif (`template.mif.gz`) and nrrd (`FLAIR.nrrd`) files that are included with the NiiVue distribution on my MacOS M2 laptop regardless of whether I test Safari or Chrome.

**Comment by hanayik** [comment]
@neurolabusc, if you checkout the current `main` branch and run `npm run dev`, then drag and drop `FLAIR.nrrd` it does not load (also does not produce an error). `FLAIR.nii.gz` does load via drag and drop though. The demos do not contain this bug from my testing (only apparent from `npm run dev` and then loading `/src/index.html`).
