### ISSUE TITLE
What does mesh.visible do?

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#762]
I am trying to develop an application where the visibility of meshes can be toggled. I see that meshes have a field called `visible` which can be set by calling `nv1.setMeshLayerProperty`.

```patch
diff --git a/demos/features/mesh.layers.html b/demos/features/mesh.layers.html
index e18081b..66c39c3 100644
--- a/demos/features/mesh.layers.html
+++ b/demos/features/mesh.layers.html
@@ -33,6 +33,13 @@
         class="slider"
         id="meshSlider3"
       />
+      <input
+        type="checkbox"
+        id="meshCheckbox1"
+        checked
+      />
+      <label for="meshCheckbox1">Visible</label>
+
     </header>
     <main id="container">
       <canvas id="gl1"></canvas>
@@ -52,6 +59,11 @@
   slider3.oninput = function () {
     nv1.setMeshLayerProperty(nv1.meshes[0].id, 0, "opacity", this.value * 0.1);
   };
+  var checkbox1 = document.getElementById("meshCheckbox1");
+  checkbox1.onclick = function () {
+    nv1.setMeshProperty(nv1.meshes[0].id, 'visible', checkbox1.checked);
+    console.log(`visible=${nv1.meshes[0].visible}`);
+  }
   function handleLocationChange(data) {
     document.getElementById("location").innerHTML =
       "&nbsp;&nbsp;" + data.string;
```

I don't see any difference when the mesh is toggled to be `visible=false` or `visible=true`.

`opacity` doesn't seem to do anything either, for instance with the change

```javascript
nv1.setMeshProperty(nv1.meshes[0].id, 'opacity', checkbox1.checked ? 1.0 : 0.0);
```

I still don't see a difference.

**Comment by hanayik** [comment]
@jennydaman , I think this is a bug. It would be good if @neurolabusc could confirm. It looks like `drawMesh3D` is using the [`alpha`](https://github.com/niivue/niivue/blob/2ffa253a8664d0c436cc1c0f2ece4d63b7c49b52/src/niivue/index.js#L8164) value passed to it (which is set by the property `meshXRay` as a [NiiVue option](https://github.com/niivue/niivue/blob/2ffa253a8664d0c436cc1c0f2ece4d63b7c49b52/src/nvdocument.js#L140)). I think what it should do, is use a combination of `meshXRay` and the opacity value set on each [mesh](https://niivue.github.io/niivue/devdocs/NVMesh.html). Maybe this requires a shader update @neurolabusc?

**Comment by hanayik** [comment]
@jennydaman , actually are you trying to hide the _entire_ mesh object, or just work with the mesh layers? If you update your code to be `nv1.setMeshLayerProperty(nv1.meshes[0].id, 0, 'opacity', checkbox1.checked ? 1 : 0);` it will toggle the mesh layer to be visible or not (but not the background mesh object).

**Comment by hanayik** [comment]
> I am trying to hide the entire mesh object (use case: quickly toggle between looking at gray-matter surface to white-matter surface)

I see. I have just created PR #767 to fix this. In my testing the feature worked as intended, but it would be good to have you test for your use case. You can checkout the `fix-mesh-visible` branch and run `npm run demo` to test with some of your own test images

**Comment by jennydaman** [comment]
Thanks for the fix! I tried the fix on the main branch, it seems to work. Though for my application I have Niivue installed from npmjs.com, which is out of date. I am looking forward to the next release.

BTW here's what I was working on.

Demo: https://niivue-hosting-of-medical-image-analysis-platform-dcb83b.apps.shift.nerc.mghpcc.org/
Code: https://github.com/FNNDSC/niivue-browser

I lied to you about GM-WM, it's actually fetal brain CP-SP which is analogous.

**Comment by jennydaman** [comment]
I upgraded to version 0.38.5, the feature is working great!
