### ISSUE TITLE
NiiVue and NVImage classes missing from docs after reorganisation

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#763]
@jens-ox, it looks like NiiVue and NVImage have been removed from the docs [webpage](https://niivue.github.io/niivue/devdocs/index.html) since they were reorganised into directories containing `index.js` files and helpers. I missed this when it happened. We'll need to revive those missing sections.

**Comment by jens-ox** [comment]
@hanayik sorry, I didn't check that. Adding `-r` to the `jsdoc` command should hopefully fix it.
