### ISSUE TITLE
TypeScript migration - follow-ups

### ISSUE THREAD

**Issue by jens-ox** [niivue/niivue#769]
I would recommend doing the following things after the TypeScript migration (see #757, #669, #746):

- **Unit Testing**
Currently, all tests run via a browser instance, either using Puppeteer or using Playwright (only Playwright in the future). For tests that don't rely on rendering things (e.g. testing loaders and transformations), unit tests will be faster and will allow things like checking code coverage. I would recommend using [Vitest](https://vitest.dev/) for that.
- **Methods with many parameters: use parameter objects**
Some methods inside NiiVue have tons of parameters. This means that users have to pay attention to the ordering of the parameters and makes optional parameters harder, as they have to be at the end of the parameter list. Instead, I would recommend using parameter objects (like `loadFromFile` in `NVMesh`) for methods with more than 3 parameters.
- **Logger: Use standardised logging library**
~Instead of shipping a custom logger (that is currently only sparsely used), use an established logging library like [Pino](https://github.com/pinojs/pino).~
@hanayik: pino didn't play nice with the build system. Opted for a homebrewed simple logger that replicated what pino was providing in the browser. 
- **Class methods/fields: use visibility modifiers**
By default, all class fields and methods are public. To make the interfaces easier to understand for users, fields and methods should be annotated with [visibility modifiers](https://www.typescriptlang.org/docs/handbook/2/classes.html#member-visibility).

**Comment by hanayik** [comment]
> I would recommend doing the following things after the TypeScript migration (see #757, #669, #746):
> 
> * **Unit Testing**
>   Currently, all tests run via a browser instance, either using Puppeteer or using Playwright (only Playwright in the future). For tests that don't rely on rendering things (e.g. testing loaders and transformations), unit tests will be faster and will allow things like checking code coverage. I would recommend using [Vitest](https://vitest.dev/) for that.

I agree, I was actually looking into this recently and used [threejs](https://github.com/mrdoob/three.js) as a template for what this could look like. `vitest` looks promising for this.
