### ISSUE TITLE
Feature request: set HTTP headers

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#776]
Hello,

I would like to use NiiVue to request files which requires authorization. For example:

```shell
$ curl -i https://cube.chrisproject.org/api/v1/files/358294/incoming_WIPmocoMEMPRAGE_1mm_FOV_220_20131014162255_4.nii
HTTP/1.1 401 Unauthorized
Date: Mon, 04 Dec 2023 19:50:45 GMT
Server: Apache
WWW-Authenticate: Token
Content-Length: 6
Allow: GET
X-Frame-Options: DENY
Vary: Cookie,Origin
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
Content-Type: */*

detail

$ curl -o out.nii https://cube.chrisproject.org/api/v1/files/358294/incoming_WIPmocoMEMPRAGE_1mm_FOV_220_20131014162255_4.nii -H 'Authorization: Token eb193760b1984dff9acdaa6b0703308a1768dfec'
```

How can HTTP headers be set for the images I want to load?

**Comment by neurolabusc** [comment]
@hanayik can answer better, but I think you need to set [Cross-origin resource sharing (CORS)](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) for the images you want to share.

**Comment by jennydaman** [comment]
Yes, the server is already configured with the correct CORS settings. In this case, I am trying to get files from a server which requires authentication with username+password or token.

**Comment by hanayik** [comment]
@jennydaman , we will need to update the URL loading methods to accept header fields specified by the user.

**Comment by jennydaman** [comment]
@hanayik @neurolabusc this feature would be of big interest to my proposed BrainHack project, though not strictly necessary.

**Comment by hanayik** [comment]
@jennydaman , I can work on this on Wednesday perhaps. Alternatively, if you control the server, you could implement a custom “pre-signed” url route that would work based on if the user is authenticated or not (which your server would also need to control). This would require more work on your end though.

**Comment by hanayik** [comment]
@jennydaman , I have added experimental support for headers. Can you checkout the branch `feature-allow-headers` and test for your use case?

you can edit `src/index.html` to test locally. 

update `volumeList1` to be:

```
var volumeList1 = [{ url: "<YOUR_PROTECTED_URL>", headers: {'Authorization': 'TOKEN INFO HERE' }];
```
