### ISSUE TITLE
Show edges for overlays

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#78]
A common task to FSL and AFNI quality assurance is to test the alignment of different images, e.g. is a fMRI scan aligned to the individual's T1 scan, is one individual's T1 scan aligned to a group template. Both FSL and [AFNI chauffeur](https://afni.nimh.nih.gov/pub/dist/doc/program_help/@chauffeur_afni.html) provide methods to show edge of one image on another. AFNI provides [references for the method it uses](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/programs/3dedge3_sphx.html), which seems to be very similar to a [Sobel](https://en.wikipedia.org/wiki/Sobel_operator). Here is [my implementation of a 3D Sobel](https://github.com/rordenlab/MRIcroGL/blob/1064d9d041aab8771d2f34a656af15926600d7c4/nifti.pas#L804). While the wiki describes a [separable formula](https://en.wikipedia.org/wiki/Sobel_operator#Extension_to_other_dimensions), it does seem to require a lot of memory, and doing the 3D computation is very quick.

I think a good first application for NiiVue is to support these FSL and AFNI QA displays on an interactive web page.

FSL style:
![func2standard](https://user-images.githubusercontent.com/8930807/130671861-3feb4445-1b34-4e57-89c2-2d88bb273b0e.png)

MRIcroGL Sobel:

![MRIcroGL_Sobel](https://user-images.githubusercontent.com/8930807/130673332-3106f287-efcb-4ad5-b081-8efe0e98a8c7.png)

**Comment by neurolabusc** [comment]
I did some experiments on this topic. I remain impressed with [3DEdge](https://github.com/afni/afni/tree/master/src/3DEdge), also described [here](http://www-sop.inria.fr/members/Gregoire.Malandain/segment/edges.html) (though ftp links are non functional). It is unfortunate that it uses the GPL, so we can not adopt it. While I do think we can emulate the quality, the speed an low memory footprint of 3DEdge are really outstanding. In particular, the speed (which leverages the separable properties of the filter) is important for us, as JavaScript is pretty slow. 

For my experiments, I have added a basic 3D Canny filter to niimath. The procedure is as described by [Reeves](http://www.via.cornell.edu/ece5780/lab3.pdf). The procedure is:

1. Remove outliers: Clamp values less than the robust range to the minimum value of the robust range. Clamp values greater than the robust range to the maximum value of the robust range.
2. Apply a low-pass filter, a Gaussian blur with a sigma of 2 voxels seems suitable.
3. Apply a Sobel filter that calculates the gradient magnitude, it also determines if the strongest gradient direction is along the rows, columns or slices.
3. Normalize the gradient magnitude to the range 0..1. Set any values below 0.1 to zero ([lower bound cut-off suppression](https://en.wikipedia.org/wiki/Canny_edge_detector)).
4. Edge tracking: to survive, an edge must be have a stronger gradient in its direction (row, column, slice) than its neighbor. In other words, if this is a `row` edge (gX was strongest gradient), it must have a stronger gradient magnitude than its neighbor to the left or right (this makes the edge a single voxel skeleton). Likewise, to survive it must have some neighbors that are also non-zero gradients (e.g. a `row` edge must have a non-zero magnitude neighbor along the `column` or `slice` dimension). This removes unconnected noise. 

With the latest commit to niimath, this can be applied using the call:

```
 ./niimath highres.nii.gz -clamp 0 -uclamp 100 -sv 2 -sobel_binary outv
```

![epi](https://user-images.githubusercontent.com/8930807/132959447-9c5a9a6c-5ba0-4bfa-bc44-3a40f0525770.png)
![t1](https://user-images.githubusercontent.com/8930807/132959449-3e809d88-a9ed-4263-ae41-7f5e68cf4123.png)


Like AFNI and FSL, this creates a binarized image. One nice idea I saw was the work by [Bahnisch et al., 2009](https://link.springer.com/content/pdf/10.1007%2F978-3-642-03798-6_12.pdf) that provides sub-voxel edges to capture partial volume effects. It is a shame they do not provide an implementation of their procedure. They also omit the edge tracing step, simply saying it is complicated. Regardless, perhaps something to pursue. A very simple alternative is to just add a little blur to the skeleton:

```
./niimath highres.nii.gz -clamp 0 -uclamp 98 -sv 2 -sobel_binary -sv 1 -range outv
```

**Comment by mrneont** [comment]
Hi, @neurolabusc -

That is looking good.  Glad 3dedge3 has been a useful starting point.

I would just note that 3dedge3 does not create a binarized edge map:  steeper edges have higher values than shallow ones.  

In the above images from the overlap_check wrapper, this is particularly nice with a yellow-to-red colorbar, because shallower edges are fainter (but still present) while "major" edges pop out visually.

--pt

**Comment by neurolabusc** [comment]
The [Difference of Gassian (DoG)](https://en.wikipedia.org/wiki/Difference_of_Gaussians) (aka [Laplacian of Gaussian](https://homepages.inf.ed.ac.uk/rbf/HIPR2/log.htm)) provides another elegant solution. I added an implementation that colors zero crossings. The voxel gets a color of 1 if there is a zero crossing at the voxel face, 0.5 if it is at the voxel edge, and 0.25 if the crossing is at a corner. This creates nice, smooth boundaries. This implementation creates two voxel thick borders.

```
./niimath example_func2highres.nii.gz -clamp 10 -uclamp 100 -dog_edge 2 4 edge
```
![dg_epi](https://user-images.githubusercontent.com/8930807/132966163-c82bf8bd-377c-4cf3-aa38-69e90677eb04.png)
![dg](https://user-images.githubusercontent.com/8930807/132966165-7d79635e-ee03-4bc1-998a-23de66e18c85.png)

**Comment by neurolabusc** [comment]
The latest commit allows single or double voxel cases. In both cases, a difference of Gaussian is calculated. If the user specifies `dog1` the edge is defined as positive voxels that share negative voxel neighbors. If `dog2` is specified, both positive and negative voxels with zero-crossing neighbors are counted as edges. So calling might look like this:

```
niimath example_func2highres -clamp 0 -uclamp 100 -dog1 2 4 epi1
niimath example_func2highres -clamp 0 -uclamp 100 -dog2 2 4 epi2
niimath highres -clamp 0 -uclamp 100 -dog1 2 4 struct1
niimath highres -clamp 0 -uclamp 100 -dog2 2 4 struct2
```

In these cases, the single voxel edge is on the bright side of the boundary. However, you can reverse the order of the positive and negative Gaussian to define the edge as the dark side:

```
niimath highres -clamp 0 -uclamp 100 -dog1 4 2 struct1
```

I find these edges very visually pleasing. The Gaussian function is separable, so it is pretty computationally fast. However, it does use a lot of memory (float copies of both blurred images must be stored). For contemporary computers and MRI resolutions, the demands are pretty modest (3DEdge3 was written in 1998).

![struct1](https://user-images.githubusercontent.com/8930807/132985265-e6ed54b5-deef-428a-93d5-2d45397d7b18.png)


![EPI1](https://user-images.githubusercontent.com/8930807/132985237-9979d06e-2123-42e3-92ff-b3c22326cf5d.png)

**Comment by neurolabusc** [comment]
[Assirati et al.](https://iopscience.iop.org/article/10.1088/1742-6596/490/1/012020/pdf) suggest one can use [Q-Gaussian](https://en.wikipedia.org/wiki/Q-Gaussian_distribution) to derive a better approximation of the Laplacian of Gaussians. However, the classic Gaussian has a nice property of being separable, and the tiny amount of blurring is probably advantageous for MRI scans with modest signal to noise.

**Comment by mrneont** [comment]
Those images look quite nice.

**Comment by neurolabusc** [comment]
Another nice trick for thin lines is to create the 2-voxel dog and then apply an unsharp mask. I have updated the `dog` function so the filter can be specified in voxels using negative values (`-dog -2 -4` uses a Sigma of 2 and 4 voxels) with positive values signifying mm (`-dog 2 4` for Sigma 2 and 4mm). My sense is that mm makes sense, since the features of interest have a known size (e.g. cortex is ~2.5mm thick).

```
niimath highres  -clamp 0 -uclamp 100 -dog1 1.5 3 -unsharp 1 1  st1
```

Maybe @jonclayden has thoughts as his [imbibe](https://github.com/jonclayden/imbibe) is a wrapper for niimath and his [mmand](https://github.com/jonclayden/mmand) has functions for relevant features like skeletonisation.

I do feel that the Difference of Gaussian is a nicer solution for brain imaging than the Canny-like edge detectors. The brain has features of known physical size in mm, so the DoG parameters seem like constants. With the Canny-style edge filters, one must select some arbitrary edge threshold (I concede 3dedge3 seems to have a more robust heuristic than FSL's slicer or my own attempts). 

![unsharp](https://user-images.githubusercontent.com/8930807/132987350-1a17d7ec-41c9-438d-8207-fce50bc5d627.png)

**Comment by jonclayden** [comment]
I must admit I haven't put much thought into this – certainly I haven't done anything like as much experimentation as @neurolabusc – so I don't think I can add anything very helpful to this informative thread.

TractoR's [`reg-check` script](https://github.com/tractor/tractor/blob/master/share/tractor/experiments/reg-check.R), which aims to serve this purpose, just calculates a morphological gradient using a basic kernel and then uses k-means to threshold the result. It's an unsophisticated approach that I committed fairly hastily back in 2016 and essentially haven't revisited. On this example it gives a reasonable, if rather thick, outline, but doesn't do very well with internal details.

![tractor](https://user-images.githubusercontent.com/422057/133077052-7296d462-2a83-41a4-b80a-bf38b3083661.png)

**Comment by neurolabusc** [comment]
@jonclayden thanks. The dilation/erosion combination is an interesting trick, and looks pretty similar to the simple Sobel both in performance and computational cost. As you note, these miss internal structures.

**Comment by jonclayden** [comment]
Yes, indeed. I'll have to try out some of the alternatives you've mentioned here at some point. Thanks for posting the results of so many interesting experiments!

**Comment by afni-dglen** [comment]
Interesting discussion. We found "edginess" is really useful for checking alignment. chauffeur_afni and @AddEdge use 3dedge3 for a nice edge view. 
The AFNI GUI also has the Edge Enhance button (either tap 'e' on the image viewer, or select in the Display panel). That uses a Sobel filter described in mri_sobel.c in the AFNI source code. It's applied in 2D on that particular slice view.  

I tried some quick alternatives. From left to right in the image below:
A. 3dedge3 -Deriche Sobel filter implementation
B. Spatial variance. Average difference in 27 voxel neighborhood normalized by mean (stdev/fabs(mean)), thresholded at around 50%ile.
C. Flux image. L2 norm of second difference in x,y,z directions computed as part of 3D anisotropic smoothing,  thresholding at around 63%ile.
D. Spatial variance of spatial variance (C). Poor man's second derivative. 29%ile thresholding.
E. Edge of Spatial variance^2 (D), preserves only the edge by one voxel simple erosion to find outer periphery (corners, edges, faces - all treated equivalently).
  
![image](https://user-images.githubusercontent.com/10454715/133147314-9ef7efa0-6b1b-49c4-9784-7f03d42a5f67.png)

The color scales are not the same across all these, and lots of tricks can be played to manipulate the colors to enhance edges. Still I haven't done too much here. I think 3dedge3 still provides the best of these, and without fiddling around for specific thresholds.

**Comment by neurolabusc** [comment]
Did some work to refine the DoG implementation:
 - I refactored the Gaussian smooth code in [niivue](https://github.com/rordenlab/niimath) that will make it easier to port to JavaScript. It could be simplified further if we only want to use a single thread, or if we use multiple threads only to process 4D datasets.
 - I realized there is a simple performance optimization for DoG: this method operates by creating two smoothed images: one with a narrow width kernel (e.g. 2.5mm FWHM) and one with a larger width (e.g. 5mm FWHM). Since the operations for a separable 3D Gaussian are `O(xyzi)+O(xyzj)+O(xyzk)` (where xyz are dim[1..3] and ijk are the filter kernel widths), the wider kernel is necessarily slower than the smaller one. However, [we can use the results of the narrow kernel as the input for the wider kernel, and reduce its width (and therefore increase speed)](https://computergraphics.stackexchange.com/questions/256/is-doing-multiple-gaussian-blurs-the-same-as-doing-one-larger-blur). In other words, doing a 2.5mm FWHM blur twice results in the same amount of blur as doing a 3.53mm blur. The results of the narrow kernel are free, as we need to compute it anyways.
 - In practice, the performance of a 3D Gaussian blur is often constrained by the transposing of data. In other words, we have hit the [memory wall](https://www.blosc.org/posts/breaking-memory-walls/). One trick is to transpose tiles to use coherent cache reads, further (though probably not useful for JavaScript) there are some [SIMD instructions to accelerate this ](https://stackoverflow.com/questions/16737298/what-is-the-fastest-way-to-transpose-a-matrix-in-c) like [_MM_TRANSPOSE4_PS](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_MM_TRANSPOSE4_PS&expand=7215). For 3D operations we need to transpose both within slices (TransposeXY) and across slices (TransposeXZ). The latter has less cache coherency, and in my testing with a 256^3 voxel volume takes about four times longer.

**Comment by neurolabusc** [comment]
I notice that [bisweb](https://github.com/bioimagesuiteweb/bisweb/blob/9aae44070c2c3af16fee8819764a8ff02575f90b/docs/JStoWASM.md) has a WASM 3D Gaussian we can use (thanks to their Apache license). Xenios (@bioimagesuiteweb) is a consultant for NiiVue. Our tools fit different niches, and we should leverage their well documented and tested solutions wherever possible.

**Comment by XeniosP** [comment]
https://github.com/bioimagesuiteweb/bisweb/blob/devel/js/utilities/bis_imagesmoothreslice.js

**Comment by hanayik** [comment]
this will be part of niimath wasm

**Comment by neurolabusc** [comment]
@XeniosP and @hanayik niimath is now [ported to WASM](https://github.com/rordenlab/niimath/blob/development/src/JavaScript.md). In general, it is a superset of fslmaths. The 3D Gaussian uses optimizations not found in bisweb, and the additional functions may make this interesting for bisweb.

You can evaluate this WASM implementation from the command line using the niimath.js project, which is a rough clone of fslmaths:

```
git clone --branch development https://github.com/rordenlab/niimath
cd niimath/src
emcc -O2 -s ALLOW_MEMORY_GROWTH -s MAXIMUM_MEMORY=4GB -s TOTAL_MEMORY=268435456 -s WASM=1 -DUSING_WASM -I. core32.c nifti2_wasm.c core.c walloc.c -o funcx.js
node test.js
npm install nifti-reader-js
node niimath.js ~/T1.nii.gz -dehaze 5 -dog 2 3.2 ~/dT1.nii
```
