### ISSUE TITLE
Regression: Hot loading development mode fails

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#793]
I typically develop for NiiVue in the hot-loading mode of NiiVue (`npm run dev`). However, this now fails with a `net::ERR_CONTENT_DECODING_FAILED` for reading any images/meshes that use GZip compression. For example, the default hot loading page [loads the compressed image pcasl.nii.gz](https://github.com/niivue/niivue/blob/d1efed3fcd0e3ea608bda5e46e86642d8ffe919b/src/index.html#L78), and the page will create a `net::ERR_CONTENT_DECODING_FAILED`. If I decompress the image (e.g. pcasl.nii) I can get the page to work.

This is easy to replicate using the [suggested local development](https://github.com/niivue/niivue/tree/main#local-development):

```
git clone git@github.com:niivue/niivue.git
cd niivue
npm install
npm run dev
```

**Comment by hanayik** [comment]
@neurolabusc , the error is related to `limitFrames4D`, and the partial load (again, only in Chrome).

**Comment by neurolabusc** [comment]
@hanayik I think a solution is to modify [fetchPartial()](https://github.com/niivue/niivue/blob/d1efed3fcd0e3ea608bda5e46e86642d8ffe919b/src/nvimage/index.ts#L2586C11-L2586C11) to demand reading a stream, and let the subsequent code detect and handle GZip if necessary. So I would suggest changing:

```
headers: { range: 'bytes=0-' + bytesToLoad, ...headers }
```
to read
```
headers: { range: 'bytes=0-' + bytesToLoad, stream: True, ...headers }
```
