### ISSUE TITLE
Problem adding a mesh layer

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#800]
I'm trying to load a mesh overlay from a buffer and add it to an already loaded mesh.

This is what previously (v0.38.0) worked for me
```
NVMesh.readLayer(
    item.uri,
    item.buffer,
    mesh,
    a.opacity,
    a.colormap,
    a.colormapNegative,
    a.useNegativeCmap
  )
  mesh.updateMesh(nv.gl)
```

It stopped working after updating to v0.38.7 since NVMesh doesn't export readLayer anymore. It seems to have migrated to NVMeshLoaders, and I couldn't access it from outside.

Would it make sense to export the readLayer function again? Or is there a better way to achieve this?

**Comment by cdrake** [comment]
I think we should export the NVMeshLoader class to make all of the static methods available for reading/converting meshes. I will follow up with the other @neurolabusc  and @hanayik .

**Comment by hanayik** [comment]
@cdrake , could you implement the suggestion and open a PR?
