### ISSUE TITLE
recent change and niivue behaving differently in APQC HTML?

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#806]
Howdy-

NiiVue is great to have in afni_proc.py's QC (APQC) HTML.  However, between the last time we taught a Bootcamp in late Oct and just this week, there seems to have been a change in NiiVue that makes some images appear all dark?  

The following two images are snapshots of activating NiiVue to view an EPI dataset in October, 2023 (which appears how it was intended to):
![img_niivue_OCTOBER](https://github.com/niivue/niivue/assets/9322171/d31082e8-eada-4d8d-bf1f-b5744862be3d)
... and just yesterday (Dec 13, 2023):
![img_niivue_DECEMBER](https://github.com/niivue/niivue/assets/9322171/ed59dc03-6b06-421e-bf5f-819b2fb40508)
These images were taken from the exact same HTML code surrounding NiiVue---only the version of NiiVue is changing between them.

It is odd that it is totally dark.  In some other images in the APQC HTML, NiiVue still behaves appropriately.  I'm not quite sure what the pattern is of where we observe this dark screen and where the brain appears as it should.  Any suggestions on what might be causing this?

thanks,
pt

**Comment by hanayik** [comment]
@mrneont can you share the two versions of NiiVue? The version text should be printed to the JavaScript console in the webpage developer tools. Also, can you share the html page that has embedded NiiVue?

**Comment by mrneont** [comment]
Hi, @hanayik - Sure thing (I wasn't sure how to get the NiiVue version number, thanks for pointing that out).

* New/dark images: NIIVUE VERSION  0.38.3
* Old/fine: NIIVUE VERSION  0.38.0

**Comment by hanayik** [comment]
this is the diff between the two commits. There's a lot there, but most of it seems to be related to new mesh features, not volumes. I will have to investigate more later. 

https://github.com/niivue/niivue/compare/4be9363..6f6e0e1

**Comment by hanayik** [comment]
Just as a recap, we addressed this today in our meeting and decided to avoid setting modulation images in APQC when it's not necessary since the modulation behaviour changed in a recent commit (from turning off via a boolean to accepting a numerical `mpow` value).
