### ISSUE TITLE
niivue dev meeting 13 Dec 2023

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#808]
### Since last time...

- NiiVue, now in Typescript 🎉 . Thanks @jens-ox
- more tests converted to Playwright, thanks @cdrake 
- fixed some regressions introduced by TS port, thanks @neurolabusc 

### to be done

- [x] - update published devdocs using tsdoc now
- [x] - look into AFNI APQC rendering issues (example data in email)
- [x] - add more explicit types for niivue TS types
- [x] - reduce macOS jest maxWorkers again
- [x] - introduce vitest for fast unit testing (loaders, helpers, etc.) things that don't need rendering
- [ ] - ~introduce parameter objects for functions/methods with more than 3 parameters~ now part of #937

**Comment by jennydaman** [comment]
@hanayik I would like to share with you my current work on "niivue-react". It is a React component wrapper for Niivue offering a declarative and immutable API.

https://github.com/FNNDSC/niivue-react

As of this morning, volumes and Niivue options are working. [All that can be tested is tested.](https://github.com/FNNDSC/niivue-react/blob/4154b940f069d33b495a2a6f9bacb0454e719597/niivue-react/src/diff.test.ts)

**Comment by hanayik** [comment]
@jennydaman , this looks great. I think your work highlights a few things we can improve in the core NiiVue project as well:

- consistent use of IDs or indices (it would be good to avoid the current mixture we have)
- add better mapping of getter/setter methods to NiiVue properties. This can likely be achieved with `public get <prop_name>` and `public set <prop_name>` methods. 

The NiiVue React component has been on the backlog (undocumented one that is) for a while. I think it would be good to bring in your project into the Niivue github organisation if you're happy with that. It can become a project that benefits from regular effort and discussion in our developer meetings. I will also contribute to it and would love to transition my other projects to NiivueCanvas rather than their current, bespoke implementations. 

If you are happy to bring it into the NiiVue organisation, then I think it would be good to adopt similar tooling across projects. That is, I think we should use the toolchain already established in Niivue (npm, eslint, etc.).

**Comment by jennydaman** [comment]
That question is to be answered by @rudolphpienaar, my PI.

I don't mind using npm, eslint, ...

**Comment by hanayik** [comment]
@rudolphpienaar, it would be great to continue the development of niivue-react as a project under the niivue organisation umbrella. While this is not strictly necessary for the work to continue, I think it helps to have the projects consolidated under one roof. The [NiiVue VS code extension](https://github.com/niivue/niivue-vscode) is one example where this has worked well in the past.

**Comment by rudolphpienaar** [comment]
Sure! lmk what I need to do (if anything?) -- but TL;DR this is all fine with me.

**Comment by jennydaman** [comment]
@hanayik please set up a repo with the boilerplate ready-to-go, then add me as a collaborator.
