### ISSUE TITLE
turn off multisampling in niivue tests

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#809]

**Comment by hanayik** [comment]
@cdrake , could you implement this in the playwright and jest tests? It would probably be useful to have a central `niivueOptions` object as a helper that can be used across all tests (since it can be imported). We should set `isAntiAlias` to `false` and `isHighResolutionCapable` to `false` to just to avoid the pixel differences that could occur between snapshots on personal systems and the CI runners.

**Comment by cdrake** [comment]
Will do.
