### ISSUE TITLE
NVImage[] is not an appropriate type for Niivue.loadVolumes

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#814]
https://github.com/niivue/niivue/blob/ce270ec2b55ccdf321078aff0e3eb43a1fb565aa/src/niivue/index.ts#L3625

https://github.com/niivue/niivue/blob/ce270ec2b55ccdf321078aff0e3eb43a1fb565aa/src/nvimage/index.ts#L32-L35

- `url` should be a required field
- everything else should be optional

**Comment by hanayik** [comment]
@jennydaman , yes, good catch. This was an artefact of the Typescript migration. We'll get this fixed as a patch release and published soon. There are many other `TODO` and `FIXMEs` as comments in the code that will be addressed as well soon.
