### ISSUE TITLE
Most URLs in DEVELOP.md are outdated

### ISSUE THREAD

**Issue by kolibril13** [niivue/niivue#828]
This url works https://niivue.github.io/niivue-demo-images/mni152.nii.gz
https://github.com/niivue/niivue/blob/main/DEVELOP.md#load-a-volume

But from other examples the URLS give 404 File not found errors:
 https://github.com/niivue/niivue/blob/main/DEVELOP.md#load-a-mesh
404 URL: https://niivue.github.io/niivue/features/images/BrainMesh_ICBM152.lh.mz3

https://github.com/niivue/niivue/blob/main/DEVELOP.md#load-multiple-volumes
404 URL: https://niivue.github.io/niivue/features/images/hippo.nii.gz

https://github.com/niivue/niivue/blob/main/DEVELOP.md#load-a-volume-and-a-mesh
404 URL: https://niivue.github.io/niivue/features/images/BrainMesh_ICBM152.lh.mz3

**Comment by neurolabusc** [comment]
@kolibril13 I believe this reflects changes in how Github implements CORS. According to [this page](https://github.com/orgs/community/discussions/22399) we need to make sure these links are for `https://niivue.github.io/...` and not `https://github.com/...`.  

@hanayik would you mind implementing these changes as I am on the road.
