### ISSUE TITLE
Faster TRX float16 performance

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#830]
Related to collaborations with @asagilmore and @arokem I would like to suggest an optimization for our TRX file format support.

The community TRX format is used by NiiVue tools including [tractoscope](https://github.com/nrdg/tractoscope). The TRX format can either store vertex positions as float16 (with reduced file size important for slow connections) or float32. The benefit of float32 is that it is a native javascript datatype, whereas there is a [penalty for decoding float16 to float32](https://github.com/tee-ar-ex/trx-javascript).

We can dramatically reduce this decoding penalty for typically-sized TRX files by using a lookup table. I would suggest modifying [nvmesh-loaders.ts](https://github.com/niivue/niivue/blob/21a5e66f7ca0d6d21e949d634e7bb08588da71ce/src/nvmesh-loaders.ts#L203C10-L203C10) from:

```
        for (let i = 0; i < nval; i++) {
          vals[i] = decodeFloat16(u16[i])
        }
```
to read
```
        const lut = new Float32Array(65536)
        for (let i = 0; i < 65536; i++) {
            lut[i] = decodeFloat16(i)
        }
        for (let i = 0; i < nval; i++) {
          vals[i] = lut[u16[i]]
        }
```
The speed difference can be tested with this code:
```
        const start = Date.now();
        let isLUT = false
        if (isLUT) {
            for (let i = 0; i < nval; i++) {
              vals[i] = decodeFloat16(u16[i])
            }
        } else {
            const lut = new Float32Array(65536)
            for (let i = 0; i < 65536; i++) {
                lut[i] = decodeFloat16(i)
            }
            for (let i = 0; i < nval; i++) {
              vals[i] = lut[u16[i]]
            }
        }
        console.log(`Time elapsed: ${Date.now() - start} ms`);
```
For the sample data used by tractoscope, the original code takes 2588ms while the lookup table requires 77ms (x33 improvement).

**Comment by hanayik** [comment]
@neurolabusc , sounds good to me. Any other downsides? This seems to use a negligible amount of memory, so that's not an issue.
