### ISSUE TITLE
Issue with Cursor Alignment in Niftii Image Viewer

### ISSUE THREAD

**Issue by anjugajbhiye91** [niivue/niivue#831]
I am seeing discrepancy between the cursor pointer and crosshair location, making it challenging to accurately navigate and draw within the application.

When attempting to draw something using the cursor pointer, the drawn elements appear at a different location than where the cursor and crosshair are positioned. 

I have created repository to replicate. 

Location: https://bitbucket.org/gajbhiyeanju/niivue-test/](https://bitbucket.org/gajbhiyeanju/niivue-test/

**Comment by hanayik** [comment]
@anjugajbhiye91 , you can fix this by removing the `style` attribute that you applied to the canvas [here](https://bitbucket.org/gajbhiyeanju/niivue-test/src/c084f27f29c2df03f575a9781cb8d1101d854f1f/src/app/app.component.html#lines-3)
