### ISSUE TITLE
Retrieving NIfTI File After Drawing

### ISSUE THREAD

**Issue by anjugajbhiye91** [niivue/niivue#836]
My requirement is to send the NIfTI file as a response back to the API after a drawing operation, but I am facing difficulty in finding the option to retrieve the volume/NIfTI file post-drawing. I dont want to download  instead I want to get that niftii.

If there are specific methods or functions that handle the retrieval of NIfTI files, I would be grateful.

**Comment by hanayik** [comment]
@anjugajbhiye91 , NiiVue currently offers the `saveImage` method, but that will automatically trigger a download to happen (which saves locally). 

I think we can probably add in another method such as `getNiftiImage` that will simply return the array data that you can then send via formdata or any other method you want. 

@neurolabusc and @cdrake , what do you think of this?

**Comment by neurolabusc** [comment]
@hanayik [saveImage()](https://github.com/niivue/niivue/blob/85b9e86c3e1f13c8688c8692c473e67a07c11f1b/src/niivue/index.ts#L2631) will actually return the image data rather than saving to disk if you provide an empty filename. So you could write:

```
let img = saveImage('', true)
```
In future, we will [expand the API](https://github.com/niivue/niivue/issues/663) but I think this is some way off.

**Comment by anjugajbhiye91** [comment]
let img =this.nv.saveImage('', true)
this is downloading niftii and returing true

**Comment by hanayik** [comment]
@neurolabusc and @anjugajbhiye91 , yes, if saving a drawing the file will always be downloaded in the current implementation. The logic in `saveImage` needs to be rewritten to support downloading or returning the image data instead.

**Comment by anjugajbhiye91** [comment]
can I expect this feature in next upcoming version

**Comment by hanayik** [comment]
@neurolabusc , could you approve #843? This fixes the saveImage logic so that an empty filename simply returns the typed array rather than always triggering a download.

**Comment by anjugajbhiye91** [comment]
I'm using  "@niivue/niivue": "^0.38.10", version 
let img =this.nv.saveImage('', true)
its still returing true and  downloading niftii with some random id.

**Comment by hanayik** [comment]
@anjugajbhiye91, The new saveImage feature has not been released yet. When it is, you will need to update NiiVue to the latest version.
