### ISSUE TITLE
colorbarVisible given to Niivue.loadVolumes is disregarded

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#848]
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>NiiVue</title>
    <link rel="stylesheet" href="niivue.css" />
    <link rel="icon" href="data:;base64,iVBORw0KGgo=" />
  </head>
  <body>
    <noscript>
      <strong>niivue requires JavaScript.</strong>
    </noscript>
    <main>
      <canvas id="gl1"></canvas>
    </main>
    <script type="module" async>
      import { Niivue } from "./niivue/index.ts";
      var nv1 = new Niivue({isColorbar: true});
      nv1.attachTo("gl1");
      await nv1.loadVolumes([{ url: "../demos/images/pcasl.nii.gz", colorbarVisible: false }]);
      console.log(`colorbarVisible=${nv1.volumes[0].colorbarVisible}`);
    </script>
  </body>
</html>
```

Expected: console output shows `colorbarVisible=false` and no color bar is seen.
Actual: console output shows `colorbarVisible=true` and color bar is seen.

**Comment by neurolabusc** [comment]
@jennydaman the function [loadVolumes() does not support an option for setting colorbarVisible](https://github.com/niivue/niivue/blob/e7fee2f9b8ee283f201ccd8d09ea0d77c749db7a/src/niivue/index.ts#L3648). 

However, [as shown in the alpha-threshold live demo where colorbars are shown for the statistical overlays but not the background grayscale image](https://niivue.github.io/niivue/features/alphathreshold.html) you can set this property [after loading a volume](https://github.com/niivue/niivue/blob/e7fee2f9b8ee283f201ccd8d09ea0d77c749db7a/demos/features/alphathreshold.html#L155):
```
await nv1.loadVolumes(volumeList1);
nv1.volumes[0].colorbarVisible = false; //hide colorbar for anatomical scan

```

**Comment by jennydaman** [comment]
Oh my bad! (In my head I made the assumption `ImageFromUrlOptions` and `NVImage` were the same)

**Comment by jennydaman** [comment]
Re-opening because the function `Niivue.loadVolumes()`'s parameter is type `ImageFromUrlOptions[]` which **does** include `colorbarVisible`. Since the behavior is different from the function signature, this is a bug.

https://github.com/niivue/niivue/blob/4dd7e2b946cdf384e88f76f61657a0ef1531f978/src/nvimage/utils.ts#L126-L127
