### ISSUE TITLE
Absolute sizing of visual elements

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#857]
I notice that the size of everything (colorbars, text, crosshair line width, ...) is scaled to the size of the canvas' size. We did some user testing and people are saying that the colorbar and crosshair line widths are "annoyingly too big." 

I see we have the function `Niivue.setCrosshairWidth` however the width is still scaling with the canvas size. How can we set the size of everything to be absolute?

BTW --> https://niivue.github.io/niivue/features/colormaps.html the checkboxes here are currently suffering from an off-by-one bug: "Wide Crosshairs" seems to set the crosshairs to green, "Gamma" seems to set the crosshairs to wide

**Comment by neurolabusc** [comment]
@jennydaman 
 - Note that for voxel-based images, the crosshair size is designed to give a scale for the raw voxels. Therefore, the lines appear smaller for higher-resolution images.
 - For other ornaments (text and colorbars), the scaling is based on textHeight. This is a fraction of screen size (where 0 is invisible) and the default is 0.06. See below for an example of setting this.
 - If you really want to have an absolute text size, you could add a resize callback for the canvas and scale appropriately. You simply have to compensate for the fact that NiiVue will set the size based on your requested text height and the minimum of your canvas height or width:`size = this.opts.textHeight * Math.min(this.gl.canvas.height, this.gl.canvas.width) * scale`.
 - NiiVue is designed to work on any device, including those with extreme aspect ratios. Therefore, it does include some logic to scale the colorbar and crosshair size. 
 - for the live demo, the labels are to the left of their component, so "Wide Crosshairs" refers to the rightmost checkbox, and "Gamma" refers to the slider. Maybe adding some non breaking space between components would make this more clear.

```
    let opts = {
      textHeight: 0.02, // smaller text and colorbars
      crosshairColor: [0, 0, 1, 1] // green
    }
    const nv = new Niivue((opts = opts))
```

**Comment by hsellik** [comment]
If anyone still has problems with inconsistent crosshair sizes.

A new NiiVue option `crosshairWidthUnit` has been added, which can be set to `percent` to achieve consistent crosshair sizes with different volume sizes. Can be used in combination with `crosshairWidth`.

```
crosshairWidth: 1, (default)
crosshairWidthUnit: 'percent',
```
