### ISSUE TITLE
Missing exported types

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#860]
This is a growing list of missing type annotations or unexported types which should be provided by Niivue. I'll be adding to this list in the future.

- [ ] [`Niivue.onLocationChange`](https://github.com/niivue/niivue/blob/4dd7e2b946cdf384e88f76f61657a0ef1531f978/src/niivue/index.ts#L599-L610) type is `unknown`
- [ ] [`NiivueOptions`](https://github.com/niivue/niivue/blob/4dd7e2b946cdf384e88f76f61657a0ef1531f978/src/niivue/index.ts#L241-L244) is not exported
- [ ] [`ImageFromUrlOptions`](https://github.com/niivue/niivue/blob/4dd7e2b946cdf384e88f76f61657a0ef1531f978/src/nvimage/utils.ts#L91) (the parameter for `Niivue.loadVolumes`) is not exported
- [ ] [`NVMeshLayer`](https://github.com/niivue/niivue/blob/919d6bcc3bc59fade76c91c8e16c9ec0c4c952b1/src/nvmesh.ts#L33-L62)
- [ ] [`ColorMap`](https://github.com/niivue/niivue/blob/bef7941124538e3e593fbce632b7d67826c9bc1e/src/colortables.ts#L4-L14)

**Comment by hanayik** [comment]
many of these items are resolved except for the `unknown` location type. We can update that soon.

**Comment by jennydaman** [comment]
@hanayik `ImageFromUrlOptions` is still not exported
