### ISSUE TITLE
Setter methods in ipyniivue

### ISSUE THREAD

**Issue by kolibril13** [niivue/niivue#867]
Hi there!
This issue is a follow-up to https://github.com/niivue/niivue/issues/856

I've implemented some setter methods for ipyniivue using anywidgts  `send` function. Here's a screen recording of a notebook using 4 setter functions:
`load_volumes`, `set_opacity`, `set_crosshair_width` and `set_crosshair_color`.

https://github.com/niivue/niivue/assets/44469195/218c6d60-0715-4396-97c3-b11faa36891b

This works fine, however there are some limitations:

1. The widget has to be first initialized.
The following code example (similar to the usage of e.g. `matplotlib`) won't work because messages are send before the widget is initialized.

```python
# WANING: This is pseudo-code
nv = AnyNiivue()

my_volumes = [
           { "url": "https://niivue.github.io/niivue/images/mni152.nii.gz" }
        ]
nv.load_volumes(my_volumes)
nv.set_opacity(0.3)
nv.set_crosshair_width(10)
nv.set_crosshair_color([0, 0, 1, 1]) # blue
display(nv)
```

2. When I run "Run All" in a notebook (or when I manually run multiple cells within a fraction of a second), the view won't render as well. Same reason as above. This is because the execution of JavaScript does currently not block the python kernel. This is an unsolved problem in the ipywidget ecosystem. I discussed this issue with @manzt here https://discord.com/channels/1178781616714297576/1179097547235663972/1203739238886277150 , and he will take a look if it's possible to find a clean solution for that on the anywidget side.

As this solution might be platform dependent (Google Coolab, VS Code Notebook, JupyterLab notebooks, notebook classic) I think it would be a good idea to focus on only the most important platforms right now, which I think are VS Code Notebook and JupyterLab.

The best workaround so far would be to add `time.sleep(0.5)` into every cell that has computation intense JS code.

<details>

<summary>For reference, here's the current implementation of the setter methods (Click here to expand)</summary>

```py 
import anywidget
import pathlib

class AnyNiivue(anywidget.AnyWidget):
    path_root = pathlib.Path.cwd()
    _esm = path_root / "src" / "ipyniivue_experimental" / "static" / "widget_send.js"

    def load_volumes(self, volume_list):
        self.send({ "type": "api", "func": "loadVolumes", "args": [volume_list] })

    def set_opacity(self, opacity=1):
        self.send(
            {"type": "api", "func": "setOpacity", "args": [[0], [opacity]]}
        )


    def set_crosshair_color(self, color):
         self.send(
            {"type": "api", "func": "setCrosshairColor", "args": [color]}
         )

    def set_crosshair_color(self, color):
         self.send(
            {"type": "api", "func": "setCrosshairColor", "args": [color]}
         )

    def set_crosshair_width(self, width):
         self.send(
            {"type": "api", "func": "setCrosshairWidth", "args": [width]}
         )
```

which are received like this on JS side:

```js	
import "./widget.css";

import { Niivue } from "@niivue/niivue";

async function render({ model, el }) {
  let canvas = document.createElement("canvas");
  let container = document.createElement("div");
  container.style.height = "300px";
  container.appendChild(canvas);
  el.appendChild(container);
  let nv = new Niivue();
  nv.attachToCanvas(canvas);

  model.on("msg:custom", (msg) => {
    if (msg.type === "api") {
      console.log("API message received!");
      let funcname = msg.func;
      nv[funcname](...msg.args);
    }
  });
}

export default { render };
```

**Comment by hanayik** [comment]
@kolibril13 , I'm closing this here since it seems a bit open ended. If you want, it might be best to copy this to the ipyniivue repo as a new issue.
