### ISSUE TITLE
A pip installable package for ipyniivue using anywidget

### ISSUE THREAD

**Issue by kolibril13** [niivue/niivue#868]
Here's now a pip installable package for ipyniivue with anywidget :

https://pypi.org/project/ipyniivue-experimental

Installation:
```sh
python3.11 -m venv .venv && source .venv/bin/activate
pip install ipyniivue_experimental
pip install jupyterlab
```

Running the script:
```
from ipyniivue_experimental import AnyNiivue

nv = AnyNiivue()
nv
```

```
# second cell, wait for one second till the frontend code from cell1 is done loading.
my_volumes = [
           { "url": "https://niivue.github.io/niivue/images/mni152.nii.gz" }
        ]
nv.load_volumes(my_volumes)
```

Feel free to test it, so we can figure out if it works on your side as well!

Right now, it's shipping only 4 setter methods mentioned in https://github.com/niivue/niivue/issues/867
`load_volumes`, `set_opacity`, `set_crosshair_width` and `set_crosshair_color`.

As a screen recording:

https://github.com/niivue/niivue/assets/44469195/ba261876-1139-4a1a-82ca-fb44acc13f19

**Comment by hanayik** [comment]
@kolibril13 , closing this since there is no action to take, and this work is not happening in the ipyniivue repo.
