### ISSUE TITLE
Making code snippets in niivue demos more accessible?

### ISSUE THREAD

**Issue by kolibril13** [niivue/niivue#869]
the niivue demo page is great!
However, it takes a few clicks to associate an example with the corresponding code block.
It would be great if example + code block would be directly linked to each other!
Are there plans to make these more accessible?
Here's a napari https://napari.org/stable/gallery.html gallery for reference.

I've also made a quick prototype using some GPT4 prompt engineering, and came up with this left-right view:
https://kolibril13.github.io/niivue-vite-vanillajs-app/
<img width="1711" alt="image" src="https://github.com/niivue/niivue/assets/44469195/9e5ea1e5-05c5-4635-83c5-bab662138224">

**Comment by hanayik** [comment]
@kolibril13 , I like the side-by-side look a lot. I think this would be a great thing to add to the demos once #865 is merged in. The demos will have HMR available after that PR is merged, and it requires some updates to the github actions used to publish the static demos. 

Let's leave this issue open as a reference for the work to be done. 

Really cool idea.

**Comment by kolibril13** [comment]
Glad you like it!

One layout that I have in mind:
This side-by-side idea could replace the https://niivue.github.io/niivue/ page.

Instead of interactive examples on the right side, I think that screenshots would be also a good idea. With  screenshots the page will load faster, and scrolling up and down would be easier, as the app would not be selected.
As soon as one clicks the screenshot, this could forward to the link to the corresponding interactive example.

**Comment by kolibril13** [comment]
Quick update on this:
I've now created a Markdown document with a table, where the image is on the left and the code on the right.
This will make navigating through the examples much easier, and also now search all the example code with "Command+F"
https://github.com/niivue/ipyniivue-experimental/blob/main/original_gallery.md

<img width="1055" alt="image" src="https://github.com/niivue/niivue/assets/44469195/9da67268-5c41-4d73-9bd4-a807336b7e5b">
It's also possible to create Hyperlinks to subsections, e.g. to this one:

https://github.com/niivue/ipyniivue-experimental/blob/main/original_gallery.md#color-maps-for-meshes
