### ISSUE TITLE
Niivue has 255 methods. Which ones should be accessible from ipyniivue?

### ISSUE THREAD

**Issue by kolibril13** [niivue/niivue#873]
I'm right now implementing setter methods for ipyniivue and I wonder which ones are useful for an everyday workflow when using niivue in a Jupyter Notebook.

From the example demo I saw that some often used ones are e.g. `loadVolumes, setOpacity, setColorMap, loadMeshes, setClipPlane`

On https://niivue.github.io/niivue/devdocs/classes/Niivue.html I found the below listed 255 methods.
I guess not all of them are meant to be user facing, therefore the question: which of these should be there in the niivue python binding? 

`addColormap, addColormapList, addLabel, addMesh, addMeshFromUrl, addVolume, addVolumeFromUrl, arrayEquals, attachTo, attachToCanvas, binarize, broadcastTo, calculateMinMaxVoxIdx, calculateModelMatrix, calculateMvpMatrix, calculateMvpMatrix2D, calculateNewRange, calculateRayDirection, calculateScreenPoint, canvasPos2frac, checkMultitouch, cloneVolume, closeDrawing, colormap, colormapFromKey, colormaps, createColormapTexture, createCustomMeshShader, createEmptyDrawing, createOnLocationChange, deleteThumbnail, depthPicker, detectPartialllyLoaded4D, dragEnterListener, dragForCenterButton, dragForPanZoom, dragForSlicer3D, dragOverListener, draw2D, draw3D, draw3DLabel, draw3DLabels, draw3DLine, drawAddUndoBitmap, drawChar, drawCircle, drawClearAllUndoBitmaps, drawColorbar, drawColorbarCore, drawCrossLines, drawCrossLinesMM, drawCrosshairs3D, drawDottedLine, drawFloodFill, drawFloodFillCore, drawGraph, drawGraphLine, drawGrowCut, drawImage3D, drawLabelLine, drawLine, drawLoadingText, drawMeasurementTool, drawMesh3D, drawMosaic, drawOrientationCube, drawOtsu, drawPenFilled, drawPenLine, drawPt, drawRect, drawRuler, drawRuler10cm, drawScene, drawSceneCore, drawSelectionBox, drawSliceOrientationText, drawText, drawTextBelow, drawTextBetween, drawTextLeft, drawTextRight, drawTextRightBelow, drawThumbnail, drawUndo, dropListener, effectiveCanvasHeight, effectiveCanvasWidth, findOtsu, frac2mm, frac2vox, generateHTML, generateLoadDocumentJavaScript, generateMouseUpCallback, getAllLabels, getBulletMarginWidth, getDescriptives, getFileExt, getFrame4D, getLabelAtPoint, getLegendPanelHeight, getLegendPanelWidth, getMaxVols, getMediaByUrl, getMeshIndexByID, getNoPaddingNoBorderCanvasRelativeMousePosition, getOverlayIndexByID, getRadiologicalConvention, getRelativeMousePosition, getVolumeIndexByID, gradientGL, handleNodeAdded, handlePinchZoom, inGraphTile, inRenderTile, init, initFontMets, initRenderShader, initText, isMeshExt, json, keyDownListener, keyUpListener, loadBmpTexture, loadConnectome, loadConnectomeFromUrl, loadDefaultFont, loadDefaultMatCap, loadDeferred4DVolumes, loadDocument, loadDocumentFromUrl, loadDrawing, loadDrawingFromUrl, loadFont, loadFontTexture, loadFreeSurferConnectome, loadFreeSurferConnectomeFromUrl, loadMatCapTexture, loadMeshes, loadPngAsTexture, loadVolumes, meshShaderNameToNumber, meshShaderNames, mm2frac, mouseCenterButtonHandler, mouseClick, mouseContextMenuListener, mouseDown, mouseDownListener, mouseLeftButtonHandler, mouseMove, mouseMoveListener, mouseRightButtonHandler, mouseUpListener, moveCrosshairInVox, moveVolumeDown, moveVolumeToBottom, moveVolumeToTop, moveVolumeUp, off, on, overlayRGBA, r16Tex, r8Tex, readDirectory, refreshColormaps, refreshDrawing, refreshLayers, registerInteractions, removeHaze, removeMesh, removeMeshByUrl, removeVolume, removeVolumeByIndex, removeVolumeByUrl, requestCORSIfNotSameOrigin, reserveColorbarPanel, resetBriCon, resizeListener, reverseFaces, rgbaTex, saveDocument, saveHTML, saveImage, saveScene, scaleSlice, sceneExtentsMinMax, screenFieldOfViewExtendedMM, screenFieldOfViewExtendedVox, screenFieldOfViewMM, screenFieldOfViewVox, screenXY2TextureFrac, screenXY2mm, setAdditiveBlend, setAtlasOutline, setClipPlane, setClipPlaneColor, setColorMap, setColormap, setColormapNegative, setCornerOrientationText, setCrosshairColor, setCrosshairWidth, setCustomMeshShader, setDefaults, setDragEnd, setDragStart, setDrawColormap, setDrawOpacity, setDrawingEnabled, setFrame4D, setGamma, setHighResolutionCapable, setInterpolation, setMesh, setMeshLayerProperty, setMeshProperty, setMeshShader, setMeshThicknessOn2D, setModulationImage, setMultiplanarLayout, setMultiplanarPadPixels, setOpacity, setPan2Dxyzmm, setPenValue, setPivot3D, setRadiologicalConvention, setRenderAzimuthElevation, setRenderDrawAmbientOcclusion, setScale, setSelectionBoxColor, setSliceMM, setSliceMosaicString, setSliceType, setVolume, setVolumeRenderIllumination, sliceScale, sliceScroll2D, sliceScroll3D, sph2cartDeg, swizzleVec3MM, sync, syncWith, textHeight, textWidth, tileIndex, touchEndListener, touchMoveListener, touchStartListener, updateGLVolume, updateInterpolation, vox2frac, vox2mm, wheelListener, xyMM2xyzMM`

**Comment by hanayik** [comment]
I’m actively working on updating the docs to remove the methods and properties that don’t need to be exposed publicly. The list should be much cleaner soon.

**Comment by kolibril13** [comment]
good to hear!

Follow-up question regardings this snippet:
```js
nv.setOpacity(0, 0.4);
nv.setColorMap(nv.volumes[0].id, "red");
```

I've noted that there's a difference on how setOpacity and setColorMap receive the volume.
One is via `0` , other one is via `nv.volumes[0].id`.

How should this look like in python? 
Feel free to send me a boilerplate pseudocode, and I'll try to make it work :)

context:
<img width="1205" alt="image" src="https://github.com/niivue/niivue/assets/44469195/e8060809-1ea7-4d7d-bd76-f681f173f6f9">

**Comment by hanayik** [comment]
@kolibril13 , closing this issue since it is probably better to have it in the ipyniivue repo. Please copy any relevant info to a new issue there if you want.
