### ISSUE TITLE
add method to close meshes (release resources)

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#877]

**Comment by neurolabusc** [comment]
I think @jens-ox might know the correct way to do this. As our meshes use a lot of resources, it does seem like we want to have a way to release these. I am not sure what we want to call this, as JavaScript has constructors, but as a managed language it does not define destructors. So I am not sure if we would call the function `unloadMesh`, `freeMesh`, `destroyMesh`, `releaseMesh`, etc. I would think that if we null the mesh, we would dereference all the arrays, but it does seem like good practice to explicitly null the WebGL resources. So again, not sure how explicit we need to be, but perhaps:


```
//freeWebGL resources
gl.bindBuffer(gl.ARRAY_BUFFER, null)
gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, null)
gl.bindVertexArray(null)
gl.deleteBuffer(this.vertexBuffer)
gl.deleteBuffer(this.indexBuffer)
gl.deleteVertexArray(this.vao)
gl.deleteVertexArray(this.vaoFiber)
//presumably, if we null the mesh we dereference all the array, or do we have to explicitly null arrays
offsetPt0 = null
this.tris = null
this.pts = null
if (this.layers && this.layers.length > 0) {
    for (let i = 0; i < this.layers.length; i++) {
        this.layers[i].values = null
    }
}
if (this.dpg && this.dpg.length > 0) {
    for (let i = 0; i < this.dpg.length; i++) {
        this.dpg[i].vals = null
    }
}
if (this.dps && this.dps.length > 0) {
    for (let i = 0; i < this.dps.length; i++) {
        this.dps[i].vals = null
    }
}

```

**Comment by hanayik** [comment]
@neurolabusc , I'm in favour of `unloadMesh` since it matches the `loadMesh` terminology we already use. 

I think if we null all arrays and typed arrays then it makes them eligible for garbage collection. 

Do you want the proposed `unloadMesh` function to be part of a niivue instance, or should `unloadMesh` be a method of a mesh object?

**Comment by neurolabusc** [comment]
@hanayik sounds reasonable. Perhaps we can develop a consensus today and implement. The other option seems to be `removeMesh()` to match the existing voxel-based `removeVolume()`, `removeVolumeByIndex()` and `removeVolumeByUrl()`.

**Comment by hanayik** [comment]
Ah, yes. `removeMesh` seems like a better name.
