### ISSUE TITLE
Converting Uint8Array Response to Blob for API Posting

### ISSUE THREAD

**Issue by anjugajbhiye91** [niivue/niivue#888]
I have been working on a feature where we receive a response in Uint8Array format from an saveImage(). However, we are unable to directly post this response through another API call due to constraints in the target API. Instead, we need to convert the Uint8Array response into a Blob and then post this Blob using form data. Unfortunately, despite our efforts, we are encountering difficulties in successfully posting the form data through the API call.

Here's a summary of the steps we're following:

Receive response in Uint8Array format.
Convert the Uint8Array response to a Blob.
Construct form data with the Blob.
Attempt to post the form data using an API call.
However, we are facing issues with step 4. Despite constructing the form data correctly, it seems that the API call is not successfully posting the data.

We would greatly appreciate any guidance or assistance you could provide in troubleshooting this issue. If you have experience with converting Uint8Array responses to Blobs and posting them using form data in API calls, your insights would be invaluable.

Additionally, if you require more specific information about our implementation or the APIs involved, please let us know, and we will be happy to provide further details.

**Comment by neurolabusc** [comment]
There are several ways to tackle this problem. The test for using saveImage without a filename is [illustrated here](https://github.com/niivue/niivue/blob/7ed03af4163f167ac6a4ef1243538f6b76aa911d/playwright/e2e/test.niivue.saveImageNoDownload.spec.js#L29). You could also look at [saveToUint8Array()](https://github.com/niivue/niivue/blob/7ed03af4163f167ac6a4ef1243538f6b76aa911d/src/nvimage/index.ts#L2508).If your different images only differ in image data, not header properties, you could also simply clone a dataset. This [code](https://github.com/niivue/niivue-niimath/blob/main/main.js) demonstrates this approach and is leveraged by this [live demo](https://niivue.github.io/niivue-niimath/).

**Comment by hanayik** [comment]
@anjugajbhiye91, it would be good to see a minimal code example of the steps you outlined above so that we can help debug.

**Comment by anjugajbhiye91** [comment]
Plase follow below location to refer
Location: https://bitbucket.org/gajbhiyeanju/niivue-test/
saveImage() {
    let imgUnint8Arry = this.nv.saveImage('', false);
    const blob = new Blob([imgUnint8Arry.buffer], {
      type: "application/x-gzip"
    });
    const formData = new FormData();
    formData.append('files', blob);
    console.log(blob)
    this.globalSharedService.postUint8Arry('http://127.0.0.1:5000/save_ui_responses', formData).subscribe(data => {
        console.log("data", data)
      });
   
  }

in this saveImage method I want to convert uint8array to blob so that I can post the file data through API. but that api is not attaching blob to form data it’s going as blank.
Please guide me and let me what is wrong in my code

**Comment by neurolabusc** [comment]
@anjugajbhiye91 perhaps @hanayik can improve on this, but here is a demo that can copy image data either from disk or from an open overlay and paste the image data as a new layer. Notice I use `fileHandle.getFile()` to get the raw image data from the blob `fileHandle`.


```
git clone git@github.com:niivue/niivue.git
cd niivue
npm install
# replace /src/index.html with code below
npm run dev
```
Here is the live demo code:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>Basic Multiplanar</title>
    <link rel="stylesheet" href="niivue.css" />
  </head>
  <body>
    <noscript>
      <strong>niivue requires JavaScript.</strong>
    </noscript>
    <header>
      <button id="loadBtn">Load From Disk</button>
      <button id="copyBtn">Copy</button>
      <button id="closeBtn">Close</button>
      <button id="pasteBtn">Paste</button>
    </header>
    <main id="container">
      <canvas id="gl1"></canvas>
    </main>
    <footer id="intensity">&nbsp;</footer>
  </body>
</html>
<!-- <script type="module" async></script> -->
<script type="module" async>
  import { Niivue, NVImage, NVMesh, NVMeshLoaders, NVImageFromUrlOptions } from "./niivue/index.ts";
  loadBtn.onclick = async function () {
      const options = {
        types: [
          {
            description: "NIfTI",
            accept: {
              "application/NIfTI": [".nii",".gz"],
            },
          },
        ],
      };
      const [fileHandle] = await window.showOpenFilePicker(options);
      const file = await fileHandle.getFile();
      const buffer =  await file.arrayBuffer();
      const u8 = new Uint8Array(buffer)
      let imageOptions = NVImageFromUrlOptions(u8)
      imageOptions.colormap = "viridis"
      let volume = await NVImage.loadFromUrl(imageOptions)
      nv1.addVolume(volume)
  }
  copyBtn.onclick = async function () {
    let opts = {
        filename: '',
        isSaveDrawing: false,
        volumeByIndex: 1
    }
    if (nv1.volumes.length < 2)
        window.alert("Unable to copy overlay (only background loaded).")
    else
        imgUnint8Array = await nv1.saveImage(opts);
  }
  closeBtn.onclick = function () {
    if (nv1.volumes.length < 2)
        window.alert("Unable to close overlay (only background loaded).")
    else
        nv1.removeVolume(nv1.volumes[1].id)
  }
  pasteBtn.onclick = async function () {
    if (!imgUnint8Array)
        window.alert("Image buffer is empty (copy before paste).")
    else {
        let imageOptions = NVImageFromUrlOptions(imgUnint8Array)
        if (nv1.volumes.length === 1)
            imageOptions.colormap = "red"
        if (nv1.volumes.length === 2)
            imageOptions.colormap = "green"
        if (nv1.volumes.length === 3)
            imageOptions.colormap = "blue"
        if (nv1.volumes.length > 3)
            imageOptions.colormap = "actc"
        let volume = await NVImage.loadFromUrl(imageOptions)
        nv1.addVolume(volume)
    }
  }
  function handleIntensityChange(data) {
    document.getElementById("intensity").innerHTML =
      "&nbsp;&nbsp;" + data.string;
  }
  var volumeList1 = [
    { 
      url: "../demos/images/mni152.nii.gz",
      colormap: "gray",
      visible: true,
      opacity: 1
    }, 
    {
      url: "../demos/images/hippo.nii.gz", 
      colormap: "red",
      visible: true,
      opacity: 1
    }
  ];
  var nv1 = new Niivue({
    dragAndDropEnabled: true,
    onLocationChange: handleIntensityChange,
  });
  nv1.attachTo("gl1");
  await nv1.loadVolumes(volumeList1);
  let imgUnint8Array = null;
</script>
```
