### ISSUE TITLE
Are FreeSurfer color maps included in Niivue by default?

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#889]
https://github.com/niivue/niivue/issues/613

I see that Niivue supports the FreeSurfer color maps. Are they included in Niivue by default? The color map named `freesurfer` seems to be a different color set than what we expect.

Here's Freeview:

![image](https://github.com/niivue/niivue/assets/20404439/3039ad90-16fb-4a0b-9a80-880505c1bb42)

Niivue's "freesurfer" color map:

![image](https://github.com/niivue/niivue/assets/20404439/ec2476e5-6ae8-4835-a9c1-42435d03c4de)

**Comment by neurolabusc** [comment]
Looks like you want the colormap `FreeSurferColorLUT`. You can run the Python script from [fs2NiiVueColormaps](https://github.com/niivue/fs2NiiVueColormaps) to convert it (and other FreeSurfer colormaps) to NiiVue format.

**Comment by jennydaman** [comment]
Thank you, I still have two questions.

1. How come the colormap `FreeSurferColorLUT` is not included in Niivue by default?
2. What does the existing colormap called `freesurfer` represent?

**Comment by neurolabusc** [comment]
1. The vast majority of colormaps included with NiiVue are for continuous images. We tried to curate the default sets to show the capabilities of NiiVue, be sensitive to anomalous color vision, and not overwhelm people. Feel free to load additional colormaps for your custom implementations. Labelled and indexed colormap palettes for drawing have the underscore prefix (`_itksnap.json` and `_slicer3d.json`). You can see a nice example with the [drawing UI live demo](https://niivue.github.io/niivue/features/draw.ui.html). Note choosing one of these from the `Draw` menu changes not only the palette used for the drawings, but also the label shown in the status bar at the bottom when the user clicks a location.
1. I believe that the FreeSurferColorLUT is there for [AFNI/Suma](https://github.com/afni/afni/blob/421e2dd6edff5904912c9d96c235b9ad702c87be/src/SUMA/SUMA_MakeColorMap.c#L44) compatibility. It is very close the the color scheme $FREESURFER_HOME/FreeSurferColorLUT.txt

**Comment by jennydaman** [comment]
@neurolabusc can you clarify what you mean by (2)? As you can see in the screenshots https://github.com/niivue/niivue/issues/889#issue-2139499255 the color scheme of the color map called "freesurfer" is not accurate to `FreeSurferColorLUT`.

**Comment by neurolabusc** [comment]
@jennydaman note that the NiiVue `FreeSurfer` colormap is the same scheme as $FREESURFER_HOME/FreeSurferColorLUT.txt for indices 0..255, though the latter contains indices larger than 255:
```
# This is for keeping track of voxel changes
256 Voxel-Unchanged                         0   0   0   0

257 CSF-ExtraCerebral                      60  60  60  0
258 Head-ExtraCerebral                    150 150 200  0
...
```
The reason everything appears blue in NiiVue is that you are applying an indexed colormap to a scalar image. You can correct this one of at least 4 ways (though I recommend option 3):
 1. Set the cal_min and cal_max when you load an image, as seen in the [alphathreshold live demo](https://niivue.github.io/niivue/features/alphathreshold.html).
 2. Set the cal_min and cal_max after loading the image, as seen when a slider is moved in the [alphathreshold live demo](https://niivue.github.io/niivue/features/alphathreshold.html).
 3. If the voxel based image is in NIfTI format, set the image intention to be a [NIFTI_INTENT_LABEL](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) as seen in the [atlas live demo](https://niivue.github.io/niivue/features/atlas.html)
 4. Set the intention to NIFTI_INTENT_LABEL after loading an image of any supported voxel -based format (including FreeSurfer .mgh format) and call nv.updateGLVolume() to have NiiVue interpret the image as such.

The documentation for [setting colors for atlases and labeled images is here](https://github.com/niivue/niivue/blob/main/docs/development-notes/colormaps.md#atlases-and-labeled-images).

**Comment by jennydaman** [comment]
That clears everything up for me, thanks!

**Comment by jennydaman** [comment]
Adding a comment for future users who stray here: colormaps for label volumes should be loaded using `NVImage.setColormapLabel`
