### ISSUE TITLE
the visible property of NVImage is not used

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#892]
@manzt [noted](https://github.com/niivue/ipyniivue/issues/52) that `visible` is not used at all to change a `volume`'s behaviour when rendered in Niivue. We typically hide volumes in Niivue by setting the `opacity` to zero. I recommend that we remove the `visible` property from `NVImage`.

**Comment by neurolabusc** [comment]
@hanayik I agree we should remove `visible` from volumes. It is worth noting that `visible` does toggle whether a [mesh is rendered](https://github.com/niivue/niivue/blob/bef7941124538e3e593fbce632b7d67826c9bc1e/src/niivue/index.ts#L8492). I am pretty sure we can remove `opacity` from the base mesh (mesh layers use opacity for color blending, but I think the meshes themselves are categorically visible or not).
