### ISSUE TITLE
Colormaps I property is not optional

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#893]
https://github.com/niivue/niivue/blob/bef7941124538e3e593fbce632b7d67826c9bc1e/docs/development-notes/colormaps.md?plain=1#L126

In the documentation, it is mentioned:

>  The `I` field is optional: if it is not provided the labels are considered to be in the range of 0..n-1. Therefore, it is only required if the labels are sparse or do not begin from 0. 

This doesn't seem true. Go to https://niivue.github.io/niivue/features/colormaps.html and set the custom color map

```javascript
let cmap = {
 R: [0, 255, 0],
 G: [0, 0, 255],
 B: [0, 0, 0],
 A: [0, 64, 64],
};
```

In the console, you get an error:

```
Uncaught TypeError: source is undefined
    makeLut colortables.ts:219
    colormap colortables.ts:85
    colormap index.ts:6034
    refreshColormaps index.ts:6172
    updateGLVolume index.ts:5173
    <anonymous> colormaps.html line 83 > eval:8
    doCustom colormaps.html:83
colortables.ts:219:31
```

Different behavior is observed with an empty array for `I`. Example:

```javascript
let cmap = {
 R: [0, 255, 0],
 G: [0, 0, 255],
 B: [0, 0, 0],
 A: [0, 64, 64],
 I: [],
};
```

Warning message:

```
niivue-warn colormap issue: indices expected to start with 0 not  undefined
```

**Comment by neurolabusc** [comment]
@jennydaman that section of the colormaps document was specific for indexed colormaps. However, my latest commit will infer both index and alpha if they are not specified for scalar colormaps.
