### ISSUE TITLE
Mouse hover

### ISSUE THREAD

**Issue by neurolabusc** [niivue/niivue#910]
The status bar at the bottom of the [atlas live demo](https://niivue.github.io/niivue/features/atlas.html) currently reports the location of the last click. This demo will be extended to respond to where the mouse is hovering, specifically it will also report the region where the mouse is hovering and highlight the region by either making it white or hiding it (depending on the `Hide Hover` checkbox).

It should be noted that devices with a mouse and touchpad often show a cursor and therefore support the notion of a hover, while touch devices typically do not have a cursor. 

![hover](https://github.com/niivue/niivue/assets/8930807/6887a66c-a81d-4f5d-987e-3c1d32c6e671)

**Comment by hanayik** [comment]
@neurolabusc , it might also be neat to make the hovered region 100% opaque and make all other regions slightly dimmer. No hover could then use the default or user supplied opacity value.
