### ISSUE TITLE
Undo the effects of nv.attachToCanvas

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#912]
In most cases, it's not necessary to "clean up" after Niivue. However, in some situations, it is necessary to "dettach."

https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-strict-mode

Using Niivue with React 18 in a `<React.StrictMode>` can result in rare bugs. Almost everything works, but weird things happen on mouse up and when drag mode is measurement.

How can `nv.attachToCanvas` be "undone" for proper cleanup?

**Comment by hanayik** [comment]
Could you describe the weird things a bit so that we can have more info? I think we could definitely do some cleanup by removing some event listeners via a new method. That method could be called when a component is unmounted in React. What do you think?

**Comment by hanayik** [comment]
@jennydaman, is this giving you problems? Reopen the issue if so. In our Niivue Desktop app, we have used `useContext` for the `Niivue` instance data. Have you tried this approach?

https://github.com/niivue/desktop
