### ISSUE TITLE
Help configuring vitest for importing Niivue

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#913]
With the @niivue/niivue@0.40.0 upgrade, my unit tests for https://github.com/niivue/niivue-react broke. The new dependency on `fflate/browser` is problematic for node. To reproduce the error, create a project and install the dependencies

1. `npm init -y`
2. `npm i @niivue/niivue@0.40.0 vitest happy-dom`

Contents of `vitest.config.js`:

```javascript
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: 'happy-dom',
  },
});
```

Contents of `tests/thing.test.js`:

```javascript
import { expect, it } from "vitest";
import { Niivue } from "@niivue/niivue";

it('should work', () => {
  expect(new Niivue()).toBeTruthy();
});
```

Result:

```
SyntaxError: Named export 'Decompress' not found. The requested module 'fflate/browser' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'fflate/browser';
const { Decompress, decompressSync: decompressSync3, gzipSync } = pkg;

 ❯ tests/thing.test.js:2:31
      1| import { expect, it } from "vitest";
      2| import { Niivue } from "@niivue/niivue";
       |                               ^
      3| 
      4| it('should work', () => {
```

**Comment by hanayik** [comment]
@jennydaman, here is an example of using niivue in vitest from the main niivue repo:
https://github.com/niivue/niivue/blob/main/tests/unit/niivue.test.ts

and our vitest config file is [here](https://github.com/niivue/niivue/blob/main/vitest.config.ts)

Hopefully that helps. 

Please reopen if you think we need specific changes in Niivue to facilitate vitest. In our unit tests, things are working well.
