### ISSUE TITLE
Input Xray type DICOM file, can not load out graphics, console will appear warning

### ISSUE THREAD

**Issue by feng-1** [niivue/niivue#916]
index.js:136859 WebGL: INVALID_VALUE: texSubImage3D: width, height or depth out of range
index.js:137135 WebGL: INVALID_OPERATION: bindTexture: attempt to use a deleted object
[.WebGL-000061A000714E00] GL_INVALID_VALUE: Desired resource size is greater than max texture size.
[.WebGL-000061A000714E00] GL_INVALID_VALUE: Desired resource size is greater than max texture size.
[.WebGL-000061A000714E00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete: Attachment has zero size.
This is the example used[https://niivue.github.io/niivue/features/draganddrop.html](https://niivue.github.io/niivue/features/draganddrop.html)
[Lateral_Xray.zip](https://github.com/niivue/niivue/files/14595454/Lateral_Xray.zip)
Use the Lateral Xray.dcm file inside the unzipper
How can this situation be resolved

**Comment by neurolabusc** [comment]
This is a 2544x3056x1 2D XRay. NiiVue is designed for 3D volumes. Most WebGL2 implementations put [strict limits on the maximum resolution of textures](https://webgl2fundamentals.org/webgl/lessons/webgl-cross-platform-issues.html#:~:text=2048%20or%204096%20seems%20to,only%2050%25%20support%20%3E%204096.). Therefore, your image's in-plane seems to exceed that of your hardware. I would suspect that a tile-based viewing tool like neuroglancer would be able to handle this.

**Comment by feng-1** [comment]
> This is a 2544x3056x1 2D XRay. NiiVue is designed for 3D volumes. Most WebGL2 implementations put [strict limits on the maximum resolution of textures](https://webgl2fundamentals.org/webgl/lessons/webgl-cross-platform-issues.html#:~:text=2048%20or%204096%20seems%20to,only%2050%25%20support%20%3E%204096.). Therefore, your image's in-plane seems to exceed that of your hardware. I would suspect that a tile-based viewing tool like neuroglancer would be able to handle this.

Thank you for your answer
