### ISSUE TITLE
Labelmap intensity range not set correctly when cal_min and cal_max are incorrect

### ISSUE THREAD

**Issue by fk128** [niivue/niivue#944]
Hi,

I have a bunch of nifti labelmap images that seem to have incorrect metadata, mainly the values of `cal_min` and `cal_max` are both set to zero. This creates a problem for correctly displaying labelmaps as they all appear mapped to 1 even if the image contains multiple labels.

The problem is fixed if I overwrite the values in `hdr` with the min and max computed by 

https://github.com/niivue/niivue/blob/f842c12048216c1b1cc70b6b09038e7eb4575b3f/src/nvimage/index.ts#L2337

Perhaps when the flag `trustCalMinMax` is set to `false`, it could overwrite the header so that it can display the image correctly?

**Comment by neurolabusc** [comment]
@fk128 can you create a minimal demo to showcase this issue or share your images. The [logic](https://github.com/niivue/niivue/blob/f842c12048216c1b1cc70b6b09038e7eb4575b3f/src/nvimage/index.ts#L2359)"
```
cmMin === cmMax &&
      this.trustCalMinMax &&
      isFinite(this.hdr.cal_min) &&
      isFinite(this.hdr.cal_max) &&
      this.hdr.cal_max > this.hdr.cal_min
```
should ignore the header's cal_min and cal_max unless the maximum is larger than the minimum. You describe a situation where they are identical (both zero) so I would suggest it should use the robust range.

For label maps you make want to consider setting the intention to [NIFTI_INTENT_LABEL](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) as an interpolation [hint](https://github.com/niivue/niivue/blob/f842c12048216c1b1cc70b6b09038e7eb4575b3f/src/niivue/index.ts#L5414). Also see the developer notes for [Atlases and Labeled Images](https://github.com/niivue/niivue/blob/main/docs/development-notes/colormaps.md#atlases-and-labeled-images).

Another thing to note is that some colormaps provide [explicit minimum and maximum values](https://github.com/niivue/niivue/blob/main/docs/development-notes/colormaps.md#atlases-and-labeled-images), which can be helpful if you want them but do take precedence over the automatic calculations. These are helpful for CT images and labeled images where the intensity is known a priori.

**Comment by fk128** [comment]
@neurolabusc here's an example image where this seems to occur 
[labelmap.nii.gz](https://github.com/niivue/niivue/files/14888631/labelmap.nii.gz) It contains two labels, but then the range appears as 0..1 in niivue

![image](https://github.com/niivue/niivue/assets/6595674/bf62e3cb-f6a8-43d4-8a07-799c641f716e)

below is from opening up the labelmap in 3D slicer, which it interprets correctly

![image](https://github.com/niivue/niivue/assets/6595674/c8af90d7-bd8f-481f-9fed-13af99654d90)

**Comment by neurolabusc** [comment]
@fk128 NiiVue uses FSL's [robust range](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;31f309c1.1307) calculation for estimating the default image brightness and contrast. For most data, this uses the 2nd and 98th percentile for image intensity range. This formula is generally very stable for continuous contrast MRI, CT, PET, SPECT, US modalities. However, your segmented lung image only has a few non-zero voxels, virtually all voxels are zero with a few 1s and a few 2s. Therefore, the robust range for your image is 0..1. In brief, using the FSL robust range ensures behavior with other tools and works for most scalar datasets. However, it is not the ideal option for all situations.

In your case, where you are creating a viewer that knows it is loading segmented images, you can simply specify using the entire range for your image. You can take advantage of the fact that NiiVue calculates the global maximum intensities when it loads an image:

```
await nv1.loadVolumes(volumeList1);
nv1.volumes[0].cal_min = nv1.volumes[0].global_min
nv1.volumes[0].cal_max = nv1.volumes[0].global_max
nv1.updateGLVolume();
```

**Comment by fk128** [comment]
Ah, I see. I'll do that. Thanks for getting back to me so quickly!

**Comment by neurolabusc** [comment]
Latest version does attempt to deal with many situations like this (where a huge proportion of voxels are zero).
