### ISSUE TITLE
Dicom Segmentation not supported

### ISSUE THREAD

**Issue by helghast79** [niivue/niivue#948]
Although segmentation masks can load well as nifti volumes, they seem to fail to load as dicom. I'm using the manifest approach to load the dicoms (just 1 since it's a multiframe dicom-seg) like:
```
NVImage.loadFromUrl({
   url: seg.manifestUrl,
   isManifest: true,
   ...
})
```
This works for all dicoms I have tested with, except for segmentations that produce the following error

<img width="451" alt="Captura de ecrã 2024-04-09, às 12 27 33" src="https://github.com/niivue/niivue/assets/16775681/67b98c9f-83b2-4025-9ec6-6346486e6d18">

3 and 1 are respectively obtained with
```
dt = this.series.images[0].getDataType()    and
bpv = this.series.images[0].getBitsAllocated()
```
in **readDICOM(buf)** method. Datatype 0 is because there are no defined datatype for dt=3 and bpv=1 I guess

Is there a way to correct this? or am I doing something wrong to load this kind of images?

**Comment by neurolabusc** [comment]
@helghast79 NiiVue supports grayscale (8, 16, 32-bit) and RGB (24-bit) DICOM images. However, it does not currently support binary (1 bit) images. Feel free to add support yourself, or share an example image with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

While NiiVue handles many DICOM medical images, it is more focused on the research neuroimaging formats of voxels (e.g. NIfTI), meshes, connectomes and streamlines. If your primary aim is to work with DICOM images, you may be better served by the [OHIF Viewer](https://github.com/OHIF/Viewers) which is built on the terrific cornerstone library.

**Comment by neurolabusc** [comment]
To replicate this issue, see the [TCIA, SEG (binary images, file with two segmentations)](https://www.aliza-dicom-viewer.com/download/datasets) dataset.

**Comment by neurolabusc** [comment]
This format is supported from NiiVue 0.42.0

**Comment by helghast79** [comment]
Although it now supports and loads binary (1 bit) images, something is not quite right since when multiple segments exists, not all of them display correctly. Maybe I need to set it differently while loading but have no ideia what to change in order to load different labels in different colors. I noticed that in this [example](https://niivue.github.io/niivue/features/atlas.html) it shows nicely the different segmented volumes and that loads from a nifti file. Is that only available for nifti and not for dicom? 

With the example from [TCIA, seg](https://www.aliza-dicom-viewer.com/download/datasets), 

This is how it loads in Ohif viewer
<img width="688" alt="Captura de ecrã 2024-05-09, às 13 41 16" src="https://github.com/niivue/niivue/assets/16775681/8ac759ec-9731-44a5-81ea-710bd31732cd">

and this is how it loads using niivue 
<img width="716" alt="Captura de ecrã 2024-05-09, às 13 53 22" src="https://github.com/niivue/niivue/assets/16775681/f6726ecc-8ddb-44d4-ba9e-e2e6ddcfe8d4">

I try setting colormapLabel with appropriate values for the 2 segments in case above but still display only the first one

how can we display all the different segments in different colors?
