### ISSUE TITLE
render view broken in saved HTML scene

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#966]
When saving a scene as html (such as in our demo [here](https://niivue.github.io/niivue/features/save.html.html)), the render view is broken and gives the following error in the console:

`Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed')`

from this line: 

`const c = "azimuth: " + this.scene.renderAzimuth.toFixed(0) + " elevation: " + this.scene.renderElevation.toFixed(0);`

@cdrake , were there any changes to the scene format related to the render view?

All other non-render views work as they should.

**Comment by cdrake** [comment]
@hanayik -  There were no changes to scene data format.  The scene data is now accessed through the document instance. INITIAL_SCENE_DATA was added to populate the scene data.
