### ISSUE TITLE
Loading binary (1 bit) images with more than 1 segment

### ISSUE THREAD

**Issue by helghast79** [niivue/niivue#971]
Since version 0.42.0 Niivue can load binary (1 bit) images in dicom format but, something is not quite right since when multiple segments exists, not all of them display correctly. Actually, it seems all segments display with the same value of 1 and the ones originally with value > 1 are displayed in wrong order. The problem does not exist, If we load the same images in nifti format.

With the example from [TCIA, seg](https://www.aliza-dicom-viewer.com/download/datasets), 

This is how it loads in Ohif viewer
<img width="688" alt="Captura de ecrã 2024-05-09, às 13 41 16" src="https://github.com/niivue/niivue/assets/16775681/8ac759ec-9731-44a5-81ea-710bd31732cd">

and this is how it loads using niivue 
<img width="716" alt="Captura de ecrã 2024-05-09, às 13 53 22" src="https://github.com/niivue/niivue/assets/16775681/f6726ecc-8ddb-44d4-ba9e-e2e6ddcfe8d4">

how can we display all the different segments in different colors?

**Comment by neurolabusc** [comment]
This is not a limitation of NiiVue, but rather the [Daikon](https://github.com/rii-mango/Daikon) library and therefore must be resolved there. I note that [both](https://github.com/rii-mango/Daikon/blob/41e902bbde09303e56d86fad6bf8fea6e0e45a89/src/series.js#L528) `validatePixelDataLength()`  and `image.getPixelDataBytes().byteLength` report 10747904 bytes which is consistent with a single volume of 512x512x328 voxels at 1 bit per voxel. An image with two volumes should have twice as many voxels. The Diakon library is in maintenance mode, so if you want to see this resolved, I would suggest you develop a patch and generate a pull request. The DICOM format is very complex, and this is a pretty atypical usage. It may be wiser to distribute DICOM images in more conventional styles - I note that most of the DICOM tools I use did not support this image.
