### ISSUE TITLE
Support gzipped NVDocuments

### ISSUE THREAD

**Issue by cdrake** [niivue/niivue#983]
Allow users to save and load gzipped NVDocuments

**Comment by neurolabusc** [comment]
@cdrake this should be easy, as we already include [fflate](https://github.com/101arrowz/fflate) with NiiVue. Given the size of scenes, using the asynchronous variants that use web workers seems appropriate. You could even use the same `.nvd` extension when writing either compressed or uncompressed data, and use the [first two bytes](https://github.com/niivue/niivue/blob/d5fd3750d60b8f24f45cd454f4d46bc94ee221a5/src/nvmesh-loaders.ts#L1716) to detect the [magic number 0x1F8B](https://en.wikipedia.org/wiki/Gzipr) as the signature of gzipped data.

**Comment by cdrake** [comment]
@neurolabusc - Will do.  I'm working on it now.
