### ISSUE TITLE
switch to itk.js for nifti i/o so that we can read and write data

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#99]
nifti-reader.js does not provide an easy way to write data (if we needed it). ITK.js does, and it can read from Files, Blobs, and array buffers which seems perfect for what we wanted. It also returns types arrays (which we want) and does its work via webworkers. 

https://insightsoftwareconsortium.github.io/itk-js/api/browser_io.html

@cdrake and @neurolabusc what do you think of making the switch? I think it should support the IO use cases we cater to.

**Comment by neurolabusc** [comment]
In general, ITK products are well designed and have a strong community. I suspect this will also allow us to access a lot of other useful formats. My big concern would be how large this dependency is. It seems like the niche we are going for is very lightweight and fast to load, install, etc.
